NEW LinkFieldController to handle FormSchema
silverstripe/silverstripe-linkfield pull request #108
Opened 2023-10-24 05:11 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/84

2023-10-31 04:07 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +    public function linkData(): HTTPResponse
I tried to use GraphQL but it stopped making requests once I switched it to only using ID instead of the entire JSON blob of the link to get the description (have since updated endpoint to return all data, not just description) - seems like there's logic (in apollo?) where passing the same param means don't refetch?

2023-10-31 04:08 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +    public function linkDelete(): HTTPResponse
I tried to use GraphQL but could work out apollo so just made this little endpoint instead.  The following query did work in graphql ide - `mutation { deleteLinks(ids: [44]) }`

2023-10-31 23:19 UTC, emteknetnz commented on tests/php/Models/LinkTest.php
> +        $image->setFromLocalFile(dirname(dirname(dirname(__FILE__))) . '/resources/600x400.png');
This is required to be unit-tests to run from both the vendor folder and non-vendor folder installs

2023-11-01 02:50 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +    public function linkData(): HTTPResponse
I tried to use GraphQL but it stopped making requests once I switched it to only using ID instead of the entire JSON blob of the link to get the description (have since updated endpoint to return all data, not just description) - seems like there's logic (in apollo?) where passing the same param means don't refetch?

2023-11-01 02:50 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +     * Delete a Link
I tried to use GraphQL but I couldn't work out how to use apollo so just made this little endpoint instead. The following query did work in graphql ide - mutation { deleteLinks(ids: [44]) }

2023-11-01 02:50 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +     * Get data for a Link
I tried to use GraphQL but it stopped making requests once I switched it to only using ID instead of the entire JSON blob of the link to get the description (have since updated endpoint to return all data, not just description) - seems like there's logic (in apollo?) where passing the same param means don't refetch?

2023-11-01 05:30 UTC, maxime-rainville requested changes
This is just an initial review. I'm planning on having a second pass.

- The re-factored link field doesn't work at all in Elemental.
- This is probably because the Root state management has some problems.
- We've lost the FileLinkModal. I'm fine with spinning this off into it's own card because it is a bit of a headache to get working correctly, but I would like us to at least be confident the new approach can support it.

2023-11-01 05:30 UTC, maxime-rainville commented on _config/config.yml
> -    - SilverStripe\LinkField\Extensions\AjaxField
Note to self: make sure that TreeDropDown and AnchorField still works.

2023-11-01 05:30 UTC, maxime-rainville commented on _graphql/queries.yml
>  'readLinkTypes(keys: [ID])':
Note to self: Make sure there's a card to ditch the registry and get the link types to be communicated as props.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +  const [data, setData] = useState(value);
Setting the initial value of `useState` hook from a prop is wrong.

`onChange` should be updating the parent state and the information should flow back down there.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
Need to handle other errors beyond validation. (e.g. Session time-out, not enough permission, random 500)

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +      actions.toasts.success('Saved link');
Localise this.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +        actions.toasts.success('Deleted link');
Localise this.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +        actions.toasts.error('Failed to delete link');
Localise this.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +    setData({});
This part shouldn't be needed. Only `onChange`.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}/${linkID}`;
We are getting this URL to our section in multiple places. I'm thinking it might be worthwhile having it in one spot.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkPicker/LinkPicker.js
> +  onSelect: PropTypes.func
Seems to me like most of these things should be required.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkPicker/LinkPicker.js
> +  <div className={classnames('link-picker', 'form-control', {'link-picker--selected': typeTitle ? true : false})}>
```suggestion
  <div className={classnames('link-picker', 'form-control', {'link-picker--selected': !!typeTitle})}>
```

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkPicker/LinkPickerTitle.js
>    onClick: PropTypes.func
Most of these props should be required.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  linkTypeTitle: PropTypes.string,
Doesn't match the `typeTitle` prop name above.

For context, we are definitely going to add link type icons down the track. And maybe other niceties like extended link type description. I think we should keep the Link Type as an object here.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/entwine/JsonField.js
> +    handleChange(linkID) {
That's not going to work in Redux form and elemental.

You need to retain this signature for your `onChange` handler.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/entwine/JsonField.js
> +      $('#' + fieldID).val(JSON.stringify({ID: linkID}));
If we're only storing the link ID, why put it in the object.

2023-11-01 05:30 UTC, maxime-rainville commented on client/src/entwine/JsonField.js
> -      this.refresh();
You need to keep calling this thing here to tell you component to update with its new props.

2023-11-01 05:30 UTC, maxime-rainville commented on docs/en/linkable-migration.md
Why are we removing this? I'm pretty sure we will want to keep this migration path.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +class LinkFieldController extends LeftAndMain
I'm OK with using this for now ... with the assumption that we will have a better way of creating API end points down the track.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +        $clientConfig = parent::getClientConfig();
Presumably, we would only need these other client config if we were serving an actual UI through this controller?

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +        return $this->createLinkForm($link);
Shouldn't we making the form ReadOnly the user doesn't have Write permission.

We should check CanCreate as well.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +     * Get data for a Link
I'm happy to split off the GraphQL parts in follow up cards so we can get the Link creation/update part over the line.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +     * Delete a Link
I'm happy to split off the GraphQL parts in follow up cards so we can get the Link creation/update part over the line.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +        if (isset($data['ID'])) {
Shouldn't we be throwing an exception if the ID from the form field doesn't match the ID in our URL parameter?

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +                $this->jsonErorr(400, 'Invalid ID');
I don't have strong feelings either way, but shouldn't this be a 404?

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +            $this->jsonError(400, 'Empty data');
I'm assuming none of these error messages will be visible to the user, so they don't need to be translated?

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +            throw new ValidationException($validationResult);
```suggestion
            throw ValidationException::create($validationResult);
```

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +        // Ideally would use getClientConfig() 'saveUrl' instaed, not sure why that doesn't work
```suggestion
        // Ideally would use getClientConfig() 'saveUrl' instead, not sure why that doesn't work
```

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +        $form->setFormAction("admin/$urlSegment/linkForm/$id?typeKey=$typeKey");
If you customise your admin area to use a URL other than `admin` that will break.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +        $title = $id ? 'Update link' : 'Create link'; // todo: _t()
Translate this.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +            $this->jsonError(400, 'Invalid ID');
If we can't find the link, shouldn't be a 404?

I'm not overly fuss about this.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Form/JsonField.php
> +        $record->$dbColumn = $linkID;
Isn't there a risk that we will create orphan links? Example: You created your link, but didn't save the page.

Happy to spin this off in a separate card.

2023-11-01 05:30 UTC, maxime-rainville commented on src/GraphQL/LinkTypeResolver.php
> -                'handlerName' => $type->LinkTypeHandlerName(),
We're going to need to retain the handlerName to keep the capability to create custom link modals.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Models/FileLink.php
> -        return 'InsertMediaModal';
We need to keep that somehow.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Models/Link.php
> -        $data['TitleRelField'] = $this->relField('Title');
We should have a follow up card so that the link title can be inferred from it's metadata later where appropriate. e.g.: Pointing a link to a Page probably means that the page title would be a suitable title.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Tasks/LinkableMigrationTask.php
I want to retain this for now.

2023-11-01 05:30 UTC, maxime-rainville commented on src/Type/Registry.php
This class will be going away in a follow up card. But happy to keep it around for now.

2023-11-01 05:30 UTC, maxime-rainville commented on tests/php/Models/LinkTest.php
> +        $image->setFromLocalFile(dirname(dirname(dirname(__FILE__))) . '/resources/600x400.png');
I'm surprised that we even need a physical file for this. I would have thought that a File entry in the DB would have been sufficient.

2023-11-01 05:31 UTC, maxime-rainville commented on _config/config.yml
> -    - SilverStripe\LinkField\Extensions\AjaxField
They do.

2023-11-01 11:12 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +  <div className={classnames('link-picker', 'form-control', {'link-picker--selected': typeTitle ? true : false})}>
`!!` is a code smell imo. It's fine if it ends up that way in the dist files but we should aim for no ambiguity in source code.

2023-11-01 20:39 UTC, emteknetnz commented on src/Models/FileLink.php
> -        return 'InsertMediaModal';
We're using FormSchema/FormBuilder for everything now, so the FormBuilderModal is the only viable option. How come we need InsertMediaModal? FileLink works correctly on my local.

2023-11-01 20:45 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            $this->jsonError(400, 'Empty data');
Correct, you only see them in browser developer tools, not in a toast

2023-11-01 20:47 UTC, emteknetnz commented on src/Form/JsonField.php
> +        $record->$dbColumn = $linkID;
Yes that's a possibility, it's just the nature of saving child DataObjects independently of the page save rather than all at once on page save.

The user will at least get a "there are unsaved changes on this page" if you try to navigate away from the page without saving.

2023-11-01 20:50 UTC, emteknetnz commented on src/GraphQL/LinkTypeResolver.php
> -                'handlerName' => $type->LinkTypeHandlerName(),
I'm not sure if that is viable anymore since we have a system that relies on FormSchema/FormBuilder.

Even if it were easily technically doable, I'm not sure that it's a problem that even needs to be solved? What's an actual real world use case where you need a different modal to manage links that FormBuilderModal cannot handle?

2023-11-01 23:25 UTC, maxime-rainville commented on client/src/components/LinkPicker/LinkPicker.js
> +  <div className={classnames('link-picker', 'form-control', {'link-picker--selected': typeTitle ? true : false})}>
You can use `Boolean(typeTitle)` as well.

It's a very minor thing.

2023-11-02 00:13 UTC, maxime-rainville requested changes
I had second pass. I think the approach looks broadly solid.

I'll create some follow up cards for problems that I don't think need to be addressed in this card.

Some key things I think need to be addressed now:
- The link field needs to work in Elemental
- Root state management
- Retain the ability to use different Link modal (I'm fine if the file link modal is broken for now)
- Do we want to store just the ID in the parent input?
- Making sure LinkField still work if you customise your `admin` area url.

Things that need to be addressed, but can be spun off as related card
- [Handling all possible errors form AJAX requests](https://github.com/silverstripe/silverstripe-linkfield/issues/110)
- [Loading UI](https://github.com/silverstripe/silverstripe-linkfield/issues/111)
- File link modal and alternative link modal
- Using GraphQL to for initial link description and clearing link
- Localisation
- Controller for parking API end points and form schema
- Readonly state of form schema

Other things that we can decide later
- Migration from other modules ... just retain the existing one for now.
- Orphan links.
- Inferring Link title 


FYI I didn't look at the fine print of all the test coverage for now, since I presume there's a substantial bit that still needs to be updated.

2023-11-02 00:13 UTC, maxime-rainville commented on src/Form/JsonField.php
> +        $record->$dbColumn = $linkID;
I think we should try to assign the owner at the same time we do the initial save, we can look at this once we pick up reverse ownership again.

2023-11-02 00:13 UTC, maxime-rainville commented on src/GraphQL/LinkTypeResolver.php
> -                'handlerName' => $type->LinkTypeHandlerName(),
We have an immediate use case for creating link for File. The FileInsertModal is design so you can use different form schema inside of it:
- Insert a link to file in the WYSIWYG,
- Insert an image in the in the WYSIWYG,
- Edit file details,
- Edit folder details.


I could imagine complex scenarios where you might want to display a complex form for creating links:
- I want to create a link to GitHub issues and I need to build a search form in my modal so I can get there.

2023-11-02 00:13 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> -  if (loading) {
We should retain the loading logic. There will be time where we are waiting for information to came back from the server.

2023-11-02 00:13 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +    return Promise.resolve();
We're mixing promises and await/async. Do we want to normalise everything to use the same syntax?

2023-11-02 00:13 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
Can we look at moving all the methods that do HTTP request to their own file?

It's somewhat manageable now, but once we throw in Link lists in there I think it's going to became a bit more difficult.

Having them as individual method will also make it easier to write JEST test for them.

2023-11-02 00:56 UTC, emteknetnz commented on src/Form/JsonField.php
> +        $record->$dbColumn = $linkID;
I don't think this is possible if as we're using has_one relations e.g. MyPage.has_one = [MyLink => Link::class].  Reason being that we'd need to call $page->write() in order to save the relation since the foriegn key is on the Page, not the Link.  It's simply wrong to do this in an XHR request to save a Link, the correct time is when you click the save button on the Page edit form.

2023-11-02 01:12 UTC, emteknetnz commented on src/GraphQL/LinkTypeResolver.php
> -                'handlerName' => $type->LinkTypeHandlerName(),
> We have an immediate use case for creating link for File

... FileLink works in this PR using the FormBuilderModal, id it not work on your local?

Using the FormBuilderModal it renders the File relation as a regular UploadField (consistent with Page edit form). It's possibly better than before previously the InsertMediaModal the Link.Title field wasn't being shown on the Link edit form (because there wasn't a form), now it is.

2023-11-02 01:34 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
Not sure what quite what you mean. HTTP request are:
- GraphQL query to get link types
- fetch() (lib/Backend) query to fetch data
- fetch() (lib/Backend) query to delete link

I'm not sure why we'd split them off to a different file, the queries are simple and don't take up much in the file. Splitting things across files seems like it's needlessly increasing complexity.

For the 2x fetch() requests we can mock in jest them pretty easily - e.g. https://github.com/silverstripe/silverstripe-session-manager/blob/2/client/src/components/LoginSession/tests/LoginSessionContainer-test.js#L10

For GraphQL, I don't know how to mock the responses

2023-11-02 01:39 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +    return Promise.resolve();
There's a convoluted stack of callback handler being passed around LinksField.js, FormBuilderLoader.js and FormBuilder.js (maybe others?) What we have now works and I don't want change it

2023-11-02 01:44 UTC, emteknetnz commented on src/Tasks/LinkableMigrationTask.php
Reverted

2023-11-02 03:07 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const [data, setData] = useState(value);
Updated

2023-11-02 03:08 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +    setData({});
Keeping the setData({}) as data is managed on the LinkField. Have removed the setLinkID(0), as managing the LinkID on the parent JsonField.

2023-11-02 03:09 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +  <div className={classnames('link-picker', 'form-control', {'link-picker--selected': typeTitle ? true : false})}>
Will just leave as is

2023-11-02 03:09 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +  onSelect: PropTypes.func
Updated

2023-11-02 03:10 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  linkTypeTitle: PropTypes.string,
Updated to linkType.

We can update the prop / propType in a later PR when we add icons

2023-11-02 03:10 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
>    onClick: PropTypes.func
Updated

2023-11-02 03:10 UTC, emteknetnz commented on client/src/entwine/JsonField.js
> -      this.refresh();
Updated

2023-11-02 03:10 UTC, emteknetnz commented on client/src/entwine/JsonField.js
> +      $('#' + fieldID).val(JSON.stringify({ID: linkID}));
Updated

2023-11-02 03:12 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $clientConfig = parent::getClientConfig();
It's standard to merge the config with parent::getClientConfig() in other places in the codebase where we define getClientConfig();

2023-11-02 03:20 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        return $this->createLinkForm($link);
Updated to check for these and set to readonly in createLinkForm()

2023-11-02 03:26 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        if (isset($data['ID'])) {
Updated

2023-11-02 03:27 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +                $this->jsonErorr(400, 'Invalid ID');
Updated all of the 'Invalid ID' / 'Invalid typeKey' errors to 404

2023-11-02 04:20 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        // Ideally would use getClientConfig() 'saveUrl' instaed, not sure why that doesn't work
Updated

2023-11-02 04:24 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $form->setFormAction("admin/$urlSegment/linkForm/$id?typeKey=$typeKey");
Updated

2023-11-02 21:34 UTC, emteknetnz commented
@maxime-rainville I've split off a separate card for elemental support, looks like it's non-trivial - https://github.com/silverstripe/silverstripe-linkfield/issues/116

2023-11-02 21:44 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            throw new ValidationException($validationResult);
Updated

2023-11-02 21:50 UTC, emteknetnz commented on client/src/entwine/JsonField.js
> +    handleChange(linkID) {
I don't understand why this is relevant for redux-form or elemental. The handleChange/onChange callback is only shared between JsonField and LinkField, it's not passed down to any child components

2023-11-02 21:52 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      actions.toasts.success('Saved link');
Will do in https://github.com/silverstripe/silverstripe-linkfield/issues/113

2023-11-02 21:52 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +        actions.toasts.success('Deleted link');
Will do in https://github.com/silverstripe/silverstripe-linkfield/issues/113

2023-11-02 21:52 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +        actions.toasts.error('Failed to delete link');
Will do in https://github.com/silverstripe/silverstripe-linkfield/issues/113

2023-11-02 21:52 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}/${linkID}`;
It's currently a one liner, I don't think it needs to be optimised any further

2023-11-02 21:53 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $title = $id ? 'Update link' : 'Create link'; // todo: _t()
Will do in https://github.com/silverstripe/silverstripe-linkfield/issues/113

2023-11-02 21:53 UTC, emteknetnz commented on src/GraphQL/LinkTypeResolver.php
> -                'handlerName' => $type->LinkTypeHandlerName(),
Have reverted

2023-11-02 21:54 UTC, emteknetnz commented on src/Models/FileLink.php
> -        return 'InsertMediaModal';
Can look at reimplementing in https://github.com/silverstripe/silverstripe-linkfield/issues/112

2023-11-02 21:54 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> -  if (loading) {
Can reimplement in https://github.com/silverstripe/silverstripe-linkfield/issues/111

2023-11-02 21:55 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
Can implement in https://github.com/silverstripe/silverstripe-linkfield/issues/110

2023-11-06 02:06 UTC, maxime-rainville commented on client/src/entwine/JsonField.js
> +    handleChange(linkID) {
The redux onChange handler expect a different method signature.

If we have one method signature for entwine and one for redux form, the field will have to be aware of how its being rendered and uddate the return value accordingly.

Much easier to just have the entwine unchange handler expect the same thing as redux form.

2023-11-06 03:05 UTC, emteknetnz commented on client/src/entwine/JsonField.js
> +    handleChange(linkID) {
I don't see how this is easier? I'm really confused as to how redux-form is relevant here. This handler is only used between JsonField and LinkField

> the field will have to be aware of how its being rendered

By that do you mean the parent component on LinkField is, i.e it could be something that is NOT JsonField?

I can kind of see how passing `event` as the first param makes sense, since that's fairly standard for event handlers, however in the context on onModalSubmit() we don't actually have an event passed down as an argument.  I think the code that consumes onModalSubmit() is https://github.com/silverstripe/silverstripe-admin/blob/2/client/src/components/FormBuilder/FormBuilder.js#L249

2023-11-06 03:35 UTC, maxime-rainville requested changes
>  I've split off a separate card for elemental support, looks like it's non-trivial

Making sure this new approach works with Elemental is pretty fundamental. I think getting it working in Elemental is mostly a question of stealing some bits from my `silverstripe-react` module.

I had a go to try to get it working in this PR and mostly got there. I'm confident the new approach can be made to work with the new form schema approach.

It took me a couple days to wrap my head around getting a form field working in React and Entwine. Probably best if I pick the elemental follow up card.

2023-11-06 03:35 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
Having played with the thing a bit more, the `const match = formSchema.id.match(/\/linkForm\/([0-9]+)/)` logic doesn't seem robust.

I'm thinking this could be substantially better.

- If you're form validation that should return a 400 along with a form schema.
- If you're form submission is successful, then it shouldn't return a form schema at all. It should return the ID of the successfully created record. That would mimic tho behaviour of a regular Form object where we return a view with a success message.

2023-11-06 03:35 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +  linkID: PropTypes.number.isRequired,
I think we need to agree with some convention up front.

`linkID` should be called `value`. This is not just an academic argument. Redux-form will call it `value` when it passes it in the form schema.

Equally, `id` should be reserved for the id of the form field.

2023-11-06 03:35 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}/${linkID}`;
Looking at the fine print of this, when we're in the process of creating a new entry, it uses an id of `0` for the URL. `/admin/linkfield/schema/linkForm/0?typeKey=phone`

I'm wondering if we should use something like `new` or maybe nothing at all?

If we want to be REST purists, we could say that the endpoint for updating an existing link should be a `PUT`. Creation would occur on `POST`. 

Probably doesn't matter on the grander scheme of things. But if we want this to be the basis for a more generic approach, it's probably worth sorting it now.

2023-11-06 03:35 UTC, maxime-rainville commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  linkTypeTitle: PropTypes.string,
If it was already like that I would be fine with it. But we are literally removing something we are planning to bring back in a not too distant PR.

2023-11-06 03:35 UTC, maxime-rainville commented on src/Controllers/LinkFieldController.php
> +        $form->setFormAction("$adminRoot/$urlSegment/linkForm/$id?typeKey=$typeKey");
```suggestion
        $typeKey = Registry::create()->keyByClassName($link->ClassName);
        $form->setFormAction($this->Link("linkForm/$id?typeKey=$typeKey"));
```

2023-11-06 04:07 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}/${linkID}`;
> If we want to be REST purists, we could say that the endpoint for updating an existing link should be a PUT. Creation would occur on POST.

FormSchema is not REST :-) e.g. we POST x-form-urlencoded data to the endpoint, not application/json.  FormSchema is its own weird little standard.  If we try to make this more RESTful then we'll just end up doing a bunch of stuff to get it more compliant, little of which has any real world benefit IMO. Let's not even bother to try to get this more RESTful.

>> I'm wondering if we should use something like new or maybe nothing at all?

`/admin/linkfield/schema/linkForm?typeKey=phone` without the zero for new records would make more sense.  It'll work the same as zero as we just test for a falsey $ItemID request param which should be null instead of 0

2023-11-06 04:24 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
>> If you're form validation that should return a 400 along with a form schema.

I can't find the exact commit (it's been forced pushed over so many times), though I do remember there was a technical reason why I chose to not return a 400 on validation failure, which I'd definitely prefer to do.

From memory it's because in lib/Backend (Silverstripe wrapper for fetch()) we have some custom code to throw Errors on 400+ status codes (i.e. !response.ok) so that we can then use fetch's  `.catch()` to handle these.  However there's [this code in FormBuilder](https://github.com/silverstripe/silverstripe-admin/blob/2/client/src/components/FormBuilder/FormBuilder.js#L245) that will then just throw these Errors again and won't get the FormSchema returned, meaning that now validation messages don't show in the FormBuilder form

You can test this by updating the last bit of `$form->setValidationResponseCallback` in `LinkFieldController::createLinkForm()`

```php
            $response = $this->getSchemaResponse($schemaId, $form, $errors);
            $response->setStatusCode(400);
            return $response;
```

You'll get a 400 returned on validation failure, however you'll also get javascript errors in FormBuilderModal.js and Backend.js in browser developer tools

2023-11-06 04:29 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
> If you're form submission is successful, then it shouldn't return a form schema at all. It should return the ID of the successfully created record.

I don't agree.  To the best of my knowledge the existing FormBuilder/FormSchema "standard" is designed for expect a FormSchema with no errors returned on success.  Having a quick look at campaign admin it returns a FormSchema on success.

We absolutely should NOT be tinkering with FormBuilder/FormSchema at this stage IMO. While it's a kind of weird standard it does work pretty great and we should just implement it as is

2023-11-06 21:05 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}/${linkID}`;
As mentioned in standup, will leave as is for now, we switch this out to something different later on before tagging stable if we want

2023-11-06 21:18 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  linkID: PropTypes.number.isRequired,
I've changed the prop to value which does make sense as it is the value of the FormField, though I've also kept a local variable `const linkID = value`; - it's simply a lot easier to follow the code as linkID is a more descriptive name

2023-11-06 21:20 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $form->setFormAction("$adminRoot/$urlSegment/linkForm/$id?typeKey=$typeKey");
Updated

2023-11-09 05:36 UTC, maxime-rainville approved these changes
Not quite happy with everything. But happy enough to merge in the interest of keeping things moving and unblocking follow up cards.

2023-11-09 05:36 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +  const onModalSubmit = async (modalData, action, submitFn) => {
Looking at Campaign Admin, on success it it's stick a `message` attribute on success that then gets displayed on the front end.

I don't like that behaviour. It should be displaying a toast instead.

I've added a few ACs to https://github.com/silverstripe/silverstripe-admin/issues/1589:
> - There's a standardised and documented way of creating new FormSchema endpoints in the CMS.
>   - This accounts for form validation
>   - *This accounts for communicating success to the front end (e.g. Displaying success message)*
>   - *Extra context about the success of the form submission can be communicated to the parent JS process*

Created a follow up card.

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/cb17b50d-734d-4a8f-8098-d3ea8ce371ba)
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/4e4371ab-7d67-4c85-93d5-5efe46adb56e)

2023-11-09 05:36 UTC, maxime-rainville commented on _graphql/queries.yml
>  'readLinkTypes(keys: [ID])':
https://github.com/silverstripe/silverstripe-linkfield/issues/15

2023-11-09 05:36 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> +    return Promise.resolve();
Promises and await/async are the same thing under the hood. 

More senior JS dev will understand this, but junior dev might get confused.

That might be a wider discussion about our JS coding standards.

2023-11-09 05:37 UTC, merged