ENH Add localisation support
silverstripe/silverstripe-linkfield pull request #119
Opened 2023-11-13 06:26 UTC by sabina-talipova

## Description

2023-11-13 22:58 UTC, emteknetnz requested changes

2023-11-13 22:58 UTC, emteknetnz commented on lang/en.yml
> +    UPDATELINK: 'Update link'
There isn't a clear standard around translation keys. While uppercase without underscores is the most common, is also hard to read

Could you please put underscores in the keys e.g. `UPDATE_LINK`

2023-11-13 22:58 UTC, emteknetnz commented on src/Models/ExternalLink.php
> +        $this->beforeUpdateCMSFields(static function (FieldList $fields) {
Could you please change `static function` to just `function` for all of the anonymous methods in the getCMSFields for all of the subclasses on Link

2023-11-14 01:38 UTC, sabina-talipova commented on lang/en.yml
> +    UPDATELINK: 'Update link'
Updated

2023-11-14 01:39 UTC, sabina-talipova commented on src/Models/ExternalLink.php
> +        $this->beforeUpdateCMSFields(static function (FieldList $fields) {
Updated

2023-11-14 02:18 UTC, emteknetnz approved these changes

2023-11-14 02:18 UTC, merged