NEW Add MultiLinkField
silverstripe/silverstripe-linkfield pull request #120
Opened 2023-11-28 03:53 UTC by GuySartorelli

## TODO
- Refactor so there's less code duplication
- Make it looks more like Max's original PR
- Docs and unit tests

## Issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/107

2023-11-28 03:59 UTC, GuySartorelli commented on client/src/entwine/LinkField.js
> +      }
I was sometimes getting console errors about unmount not being a function on undefined.
See https://docs.silverstripe.org/en/5/changelogs/5.0.0/#reactdom-render-replaced-with-reactdom-createroot-render where this pattern of checking for the root before unmounting is documented as best practice anyway.

2023-11-28 22:13 UTC, GuySartorelli commented on babel.config.json
These presets are already defined in the global webpack config.
See https://github.com/silverstripe/webpack-config/blob/5832637ef465be20afd50407cdae0185880166b5/js/modules.js#L15-L25

2023-11-28 22:15 UTC, GuySartorelli commented on .eslintrc.js
> +  },
Null coallescing (`x ?? y`) and optional chaining (`x?.y`) are well supported now - the build would have failed if they weren't supported by the browsers we target, due to the browser config in package.json

2023-11-28 22:16 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
This component now handles single and multi link fields.
I originally had them as two separate components, but the differences were so minimal it just made more sense to have a `isMulti` boolean prop and let the one component handle both scenarios.

2023-11-28 22:21 UTC, GuySartorelli commented on client/src/components/LinkModal/LinkModal.js
> +  const onSubmit = async (modalData, action, submitFn) => {
Moved a bunch of this logic from linkfield into here - linkfield doesn't care that the modal was submitted, it only cares about success. Similarly, the modal should be responsible for knowing about validation errors - linkfield itself doesn't care about them.

2023-11-28 22:22 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPickerTitle.js
The only change to `LinkPickerTitle` was to give it the classnames necessary for it to look correct when rendered outside of the picker component.

2023-11-28 22:23 UTC, GuySartorelli commented on package.json
> +    "@silverstripe/webpack-config": "^2.0.0",
Shouldn't be using alpha anymore.

2023-11-28 23:35 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +  value: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.number), PropTypes.number]),
Can't be required, because the value is `undefined` when no links are in the field and the field is rendered in an elemental block.
The component handles `undefined` perfectly so that's not a problem.

2023-11-29 00:10 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPicker.scss
I've reduced all of the `&__` down to their full `.link-picker__` forms so that we can easily do a text search for any given CSS class and find the style here.

2023-11-29 00:11 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPickerMenu.js
> +      <DropdownToggle className="link-picker__menu-toggle font-icon-plus-1" caret>{i18n._t('LinkField.ADD_LINK', 'Add Link')}</DropdownToggle>
Now that we are rendering links below the picker, it makes way more sense to have a `+` symbol for the picker, and a link symbol for the links. It's a super quick visual distinction.

2023-11-29 01:49 UTC, ChloeSartorelli commented on README.md
> -```
This branch is only valid for CMS 5

2023-11-29 01:49 UTC, GuySartorelli commented on README.md
> -EG: `SilverStripe_LinkField_Models_Link` needs to be migrated to `LinkField_Link`.
These are old and don't apply to the jump from 2.x/3.x to 4.x

2023-11-29 22:20 UTC, emteknetnz requested changes

2023-11-29 22:20 UTC, emteknetnz commented on README.md
> +    ];
```suggestion
    private static $has_many = [
        'HasManyLinks' => Link::class
    ];
```
Should be has many since that's the normal use case (and I'm not sure we're even attempting to support many_many given ownership model). Doesn't matter that it won't work just yet.  Name field consistently with 'HasOneLink'

2023-11-29 22:20 UTC, emteknetnz commented on README.md
> +                MultiLinkField::create('Links'),
```suggestion
                MultiLinkField::create('HasManyLinks'),
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  }
```suggestion
  let linkIDs = value;
  if (!Array.isArray(linkIDs)) {
    linkIDs = [];
    if (typeof value === 'number') {
      linkIDs = [value];
    }
  }
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +        query.push(`itemID[]=${id}`);
This results in really strange looking requests
/admin/linkfield/data/?itemID[]=2&itemID[]=4 

Should be
/admin/linkfield/data/2,4

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  }, [editingID, value && value.length]);
```suggestion
  }, [editingID]);
```
There's already a conditional to check linkIDs.length within the useEffect block

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      let ids = [...linkIDs];
```suggestion
      const ids = [...linkIDs];
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +    const endpoint = `${Config.getSection(section).form.linkForm.deleteUrl}/${id}`;
```suggestion
  const onClear = (linkID) => {
    const endpoint = `${Config.getSection(section).form.linkForm.deleteUrl}/${linkID}`;
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +  const onClosed = () => {
```suggestion
  const handleClosed = () => {
```
React convention

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +  const onSuccess = (value) => {
```suggestion
  const handleSuccess = (value) => {
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +          onClosed={onClosed}
```suggestion
          onSuccess={handleSuccess}
          onClosed={handleClosed}
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +  const doSelect = (key) => {
```suggestion
  const handleSelect = (key) => {
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +  const shouldOpenModal = Boolean(typeKey);
```suggestion
  const shouldOpenModal = typeKey !== '';
```
Save having to go up and check cases when this would be true/false

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +      <LinkPickerMenu types={Object.values(types)} onSelect={doSelect} />
```suggestion
const types = Object.values(types);
const className = classnames('link-picker', 'form-control');

  return (
    <div className={className}>
      <LinkPickerMenu types={types} onSelect={handleSelect}/>
```

A bit easier to read

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.scss
> +%link-row {
What is the % sign? Should be dot instead?

2023-11-29 22:20 UTC, emteknetnz commented on client/src/containers/LinkModalContainer.js
> +  const type = types.hasOwnProperty(typeKey) ? types[typeKey] : {};
How do things work if typeKey is not in types?  Should we just return false if that happens?

2023-11-29 22:20 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $itemIDs = $request->getVar('itemID');
Don't use getVar('itemID'), it means we have weird looking URLs such as

/admin/linkfield/data/?itemID[]=2&itemID[]=4 , instead of:
/admin/linkfield/data/2,4

Use $request->param('ItemID') instead and split on ','

2023-11-29 22:20 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +        return $this->cooerceValueToArray($this->Value());
```suggestion
        return $this->convertValueToArray($this->Value());
```

2023-11-29 22:20 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +    private function cooerceValueToArray(mixed $value): array
```suggestion
    private function convertValueToArray(mixed $value): array
```

2023-11-29 22:20 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +        throw new LogicException('Unexpected value type ' . gettype($value));
```suggestion
        if (is_string($value)) {
            $value = $this->convertCommaSeparatedString(trim($value));
        }
        if (empty($value)) {
            return [];
        }
        if ($value instanceof SS_List) {
            return $value->column('ID');
        }
        if (!is_iterable($value)) {
            return [$value];
        }
        if (is_iterable($value) && !is_array($value)) {
            return [...$value];
        }
        if (is_array($value)) {
            return array_values($value);
        }
        throw new LogicException('Unexpected value type ' . gettype($value));
```
All the blank lines aren't needed since there's closing brackets to visually split everything up

2023-11-29 22:20 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +        throw new LogicException('Unexpected value type ' . gettype($value));
Need to unit test this

2023-11-29 22:20 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +    private function coeerceCommaSeparatedString(string $string): string|array
```suggestion
    private function convertCommaSeparatedString(string $string): string|array
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      for (const id of linkIDs) {
```suggestion
      for (const linkIDs of linkIDs) {
```

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const [editingID, setEditingID] = useState(null);
```suggestion
  const [editingID, setEditingID] = useState(-1);
```
Are we using null because 0 is reserved for editing new unsaved Links?

`-1` is better than `null` because it's easy to make errors by testing the truthiness of editingID when 0 is a valid value. Instead explicitly test for `!== -1` similar to `indexOf()`.

2023-11-29 22:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +    for (const id of linkIDs) {
There's a real mixtures of 'id' and 'linkID' being used interchangably.  Previously it was almost exclusively linkID, because id cannot be used as prop as it's reserved by react, so linkID was used instead.

Could you update all of the `id` to `linkID` in various places in JS

2023-11-29 22:20 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        if ($request->param('ID')) {
Use of $request->param('ID') is confusing as it's not in part of `private static $url_handlers` - `'linkForm/$ItemID' => 'linkForm'`, instead it's one of the default request params?  What part of the URL does 'ID' actually refer to in this case?

2023-11-29 22:20 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        return $link;
```suggestion
        $links = Link::get()->byIDs($itemIDs);
        if (!$links->exists()) {
            $this->jsonError(404, _t('LinkField.INVALID_ID', 'Invalid ID'));
        }
        return $links;
```
Though I think the use of DataList::exists() isn't quite right, since that will `Returns true if this DataList has items` - need to check the number of items returns is the same as the length of $itemIDs

2023-11-29 22:20 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +        $ids = $this->cooerceValueToArray($value);
```suggestion
        $ids = $this->convertValueToArray($value);
```

2023-11-29 23:24 UTC, ChloeSartorelli commented on README.md
> +    ];
Sure. Done. Added note about adding a `has_one` to the `Link` model via yaml because that's what's required currently. I'm not going to document this to what we want to eventually have - the documentation is for the current state. When we change the way ownership works, we can update the docs for that new state.

2023-11-29 23:24 UTC, ChloeSartorelli commented on README.md
> +                MultiLinkField::create('Links'),
Done

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +  }
Done. I think the `if (!linkIDs)` condition was originally meant to go after the value check but this works just as well.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +        query.push(`itemID[]=${id}`);
`?itemID[]=2&itemID[]=4` is not strange looking - it's the correct way to handle array query strings for PHP `GET` requests. PHP converts it into an array for us. I don't think it makes sense to pass multiple IDs as a comma-separated param. I won't be making this change as `/2,4` is not a normal way to pass these, but the array `GET` query string _is_.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +  }, [editingID, value && value.length]);
We have to check the value and value length in order to trigger the effect when _new_ links are added. `editingID` is only for editing _existing_ links.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +      let ids = [...linkIDs];
Done

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +    const endpoint = `${Config.getSection(section).form.linkForm.deleteUrl}/${id}`;
Why?

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +  const onClosed = () => {
Done

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +  const onSuccess = (value) => {
Done

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +    const endpoint = `${Config.getSection(section).form.linkForm.deleteUrl}/${id}`;
Done to avoid ping pong but this just seems unnecessary.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +          onClosed={onClosed}
Done

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +  const doSelect = (key) => {
Done

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +  const shouldOpenModal = Boolean(typeKey);
I don't understand the reasoning but it doesn't make any material difference so I've changed it to avoid ping pong.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +      <LinkPickerMenu types={Object.values(types)} onSelect={doSelect} />
Can't reassign types so that's now `const typeArray`.
Done.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.scss
> +%link-row {
`%` is a scss template - basically means "this is for use with `@extend` but won't be output in the final css on its own".
We don't need a `.link-row` in the final css.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/containers/LinkModalContainer.js
> +  const type = types.hasOwnProperty(typeKey) ? types[typeKey] : {};
That logic was pre-existing in linkfield, I've just carried it over to here instead. Dunno what it was doing there but I didn't want to mess with it. Probably changing how that's handled would be a separate card.

2023-11-29 23:24 UTC, ChloeSartorelli commented on src/Controllers/LinkFieldController.php
> +        $itemIDs = $request->getVar('itemID');
Any discussion about this will be in https://github.com/silverstripe/silverstripe-linkfield/pull/120#discussion_r1409874663

2023-11-29 23:24 UTC, ChloeSartorelli commented on src/Form/MultiLinkField.php
> +        return $this->cooerceValueToArray($this->Value());
We're not converting, we're coeercing.... but I'll change this to avoid pingpong.

2023-11-29 23:24 UTC, ChloeSartorelli commented on src/Form/MultiLinkField.php
> +        throw new LogicException('Unexpected value type ' . gettype($value));
> All the blank lines aren't needed since there's closing brackets to visually split everything up

We don't have any standards around that - that's entirely subjective and comes up time and again where one person wants new lines and another person doesn't. I don't think we should bother pulling each other up on these sorts of changes where we don't actually have any rules about how it should be done.

In this case I've made the change to avoid ping pong, but in the future I might push back because it really shouldn't be mentioned in the first place unless/until we have rules about it.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +      for (const id of linkIDs) {
Done to avoid ping pong. We know what the ID is though so seems unnecessary.

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +  const [editingID, setEditingID] = useState(null);
We're using null because it's unset, and we can easily just do a truthy check against it. If there's an ID, it'll be truthy. I'll change to `0` if you want but `-1` is nonsensical and isn't what we use _anywhere_ to denote "not an ID".

2023-11-29 23:24 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +    for (const id of linkIDs) {
I'm not gonna go through and look for them all because I don't think it's worth my time. We know it's a link ID. We don't need to be so explicit about it.

I've changed this instance of it to avoid ping pong.

2023-11-29 23:24 UTC, GuySartorelli commented on src/Form/MultiLinkField.php
> +        return $this->cooerceValueToArray($this->Value());
I've changed all of these - not bothering to comment "done" on them all.

2023-11-29 23:24 UTC, ChloeSartorelli commented on src/Controllers/LinkFieldController.php
> +        if ($request->param('ID')) {
Was meant to be `ItemID` - fixed.

2023-11-29 23:24 UTC, ChloeSartorelli commented on src/Controllers/LinkFieldController.php
> +        return $link;
Updated to `$links`. Also, `exists()` is correct here because we do only care if there are items in the list, not how many items there are. We explicitly passed in the array of IDs from the request. There will never be _more_ than that number of links. If there are fewer, it means that the relation was outdated and had some links in it that don't exist. Only the links that exist will be displayed, and when the user clicks save the missing link IDs will disappear.

2023-11-29 23:24 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +  }
Oops nope that actually broke the single link field. Moved the if not condition to be after the numeric check.

2023-11-29 23:24 UTC, ChloeSartorelli commented on src/Form/MultiLinkField.php
> +        throw new LogicException('Unexpected value type ' . gettype($value));
Added unit test

2023-11-30 00:04 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  }, [editingID, value && value.length]);
OK, set it to `[editingID, linkIDs.length]` since we've converted value to linkIDs

2023-11-30 00:05 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +  }, [editingID, value && value.length]);
That results in an infinite loop, since we're manipulating the value of `linkIDs`.

2023-11-30 21:07 UTC, emteknetnz requested changes
The regular singlelink field wasn't working when I tested with the latest changes, though the multilink field was working

2023-11-30 21:07 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const [editingID, setEditingID] = useState(null);
OK `0` makes sense

2023-11-30 21:07 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}/?${query.join('&')}`;
```suggestion
      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}?${query.join('&')}`;
```
Don't need the trailing slash since there's no params being used on the endpoint

Changes 
/admin/linkfield/data/?itemID[]=6&itemID[]=10&itemID[]=11&itemID[]=12
to
/admin/linkfield/data?itemID[]=6&itemID[]=10&itemID[]=11&itemID[]=12

2023-11-30 21:07 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +        query.push(`itemID[]=${linkID}`);
```suggestion
        query.push(`itemIDs[]=${linkID}`);
```

2023-11-30 21:07 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $itemIDs = $request->getVar('itemID');
```suggestion
        $itemIDs = $request->getVar('itemIDs');
```

2023-11-30 21:55 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +  const [editingID, setEditingID] = useState(null);
Done

2023-11-30 21:55 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +      const endpoint = `${Config.getSection(section).form.linkForm.dataUrl}/?${query.join('&')}`;
Removed to avoid ping pong, though it doesn't affect anything one way or another.

2023-11-30 21:55 UTC, ChloeSartorelli commented on client/src/components/LinkField/LinkField.js
> +        query.push(`itemID[]=${linkID}`);
Because we don't have behat tests yet small unnecessary changes like this are more likely to break things than to be useful. I don't want to keep making these small changes that don't actually affect anything - it means I have to test every bit of functionality every time it goes through a review.

Done.

2023-11-30 21:56 UTC, GuySartorelli commented
> The regular singlelink field wasn't working when I tested with the latest changes, though the multilink field was working

It's working for me locally with this set of changes - hopefully something I did fixed whatever was broken, but if there's still something about it that isn't working please describe the actual faulty behaviour so I know what specifically needs fixing.

2023-11-30 21:56 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        $itemIDs = $request->getVar('itemID');
Done

2023-11-30 22:26 UTC, emteknetnz approved these changes
Tested locally, worked good

2023-11-30 22:27 UTC, merged