NEW Default link title for each link type
silverstripe/silverstripe-linkfield pull request #126
Opened 2023-11-30 21:55 UTC by sabina-talipova

## Description
## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/20

2023-12-03 23:02 UTC, GuySartorelli requested changes
Note that I haven't tested this locally or looked at the tests yet since there will be some fairly large implementation changes based on these requested changes.

2023-12-03 23:02 UTC, ChloeSartorelli commented on README.md
> +### Default title for each link type
```suggestion
## Default title for each link type
```
This is not a sub-heading under the "Sample usage" section - it's its own section.

2023-12-03 23:02 UTC, ChloeSartorelli commented on README.md
> +```
This doesn't feel like it is in scope - I don't think we need this functionality, please remove it.

2023-12-03 23:02 UTC, ChloeSartorelli commented on README.md
> +  default_link_title: 'My Phone Link'
The default link title should be defined in a method, not via configuration - it will most likely be drawn from elements in the link such as the URL, page title, etc. What's more, configuration values can't be localised which makes its usefulness in this context limited at best. Please remove this configuration option.

2023-12-03 23:02 UTC, ChloeSartorelli commented on README.md
> +*app/_config/mylink.yml*
```suggestion
```
The file name/location isn't helpful in this documentation, please remove it and all other file names.

If you _do_ want to include it, it should be as a comment within the code block. See https://docs.silverstripe.org/en/5/contributing/documentation/#writing-style:

> - If it's useful to include the filename that a code block relates to, do so in a comment in the first line of the code block.
>   - Don't place a blank line after this comment, unless the next line is also a comment.

2023-12-03 23:02 UTC, ChloeSartorelli commented on README.md
> +}
```suggestion
class ExternalLinkExtension extends DataExtension
{
    public function updateDefaultLinkTitle(&$defaultLinkTitle): void
    {
        $defaultLinkTitle = sprintf('External link: %s', $this->owner->ExternalUrl);
    }
}
```
Always use 4 spaces for indenting PHP code.

2023-12-03 23:02 UTC, ChloeSartorelli commented on README.md
> +class ExternalLinkExtension extends DataExtension
```suggestion
use SilverStripe\Core\Extension;

class ExternalLinkExtension extends Extension
```
We're [going to deprecate `DataExtension`](https://github.com/silverstripe/silverstripe-framework/issues/11050)

2023-12-03 23:02 UTC, ChloeSartorelli commented on README.md
> +EG: `SilverStripe_LinkField_Models_Link` needs to be migrated to `LinkField_Link`.
Why are you adding this back? Please remove it, it's not relevant for v4.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/Link.php
> +        }
```suggestion
    public function getDisplayTitle(): string
    {
        // If we have a title or don't have link, we can just bail out without any changes
        if ($this->Title) {
            return $this->Title;
        }
```

Calling this `getDisplayTitle()` and returning the title if there is one means we can just use `$DisplayTitle` in the template - we don't need any conditional logic there.

It also makes it easier for people to get "the title or the default if there's no title" in their own code or custom templates.

2023-12-03 23:02 UTC, ChloeSartorelli commented on templates/SilverStripe/LinkField/Models/Link.ss
> +</a>
```suggestion
<a href="$URL" <% if $OpenInNew %>target="_blank" rel="noopener noreferrer"<% end_if %>>$DisplayTitle</a>
```

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/Link.php
> +    public function getLinkTypeDefaultTitle(): string
```suggestion
        $defaultLinkTitle = $this->getDefaultTitle();

        $this->extend('updateDefaultLinkTitle', $defaultLinkTitle);

        return $defaultLinkTitle;
    }

    public function getDefaultTitle(): string
```

Please also update the `getLinkTypeDefaultTitle()` method to be called `getDefaultTitle()` in all the subclasses.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/Link.php
> +        return $this->config()->get('default_link_title');
```suggestion
        $default = $this->getDescription() ?: $this->getURL();
        if (!$default) {
            $default = _t(static::class . '.MISSING_DEFAULT_TITLE', 'No link provided');
        }
        return $default;
```

For all subclasses that just use the description as their default title, please remove those implementations. They can just fall back to using this one instead.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/SiteTreeLink.php
> +        $pageExist = $this->Page()->exists() && $this->getURL();
```suggestion
        $pageExist = $this->Page()->exists();
```
This should produce the same result, shouldn't it? If not, please add a code comment explaining why we _also_ need to check `getURL()` here.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/SiteTreeLink.php
> +                'Page missing',
```suggestion
                static::class . '.MISSING_DEFAULT_TITLE',
                'Page missing'
```
Use `static::class` instead of link field - it's standard practice for our localisation strings to be based on a class.
And use `MISSING_DEFAULT_TITLE` for the localisation string since that's nice and generic and can be shared across all link implementations.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/SiteTreeLink.php
> +        return $this->getTitle();
```suggestion
        return $page->Title;
```
The page title is the default.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/SiteTreeLink.php
>          return $page->Title;
Remove this fallback logic - this only belongs in the default title.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/SiteTreeLink.php
> +        $pageExist = $this->Page()->exists() && $this->getURL();
```suggestion
        $page = $this->Page();
        $pageExist = $page->exists();
```
We need this variable to grab the title for the return at the end of the method.

2023-12-03 23:02 UTC, ChloeSartorelli commented on src/Models/SiteTreeLink.php
> +    public function getLinkTypeDefaultTitle(): string
```suggestion
    public function getDefaultTitle(): string
```

2023-12-04 00:40 UTC, sabina-talipova commented on src/Models/SiteTreeLink.php
>          return $page->Title;
Follow method contract we should return either `null` or `string` and it seems a little bit nonlogical to return `null` if page exist. Probably, somebody will use this method for another purpose.

2023-12-04 00:43 UTC, sabina-talipova commented on src/Models/SiteTreeLink.php
>          return $page->Title;
Plus we populate field Title with this value

2023-12-04 01:05 UTC, sabina-talipova commented on README.md
> +### Default title for each link type
Updated

2023-12-04 01:05 UTC, sabina-talipova commented on README.md
> +```
Updated

2023-12-04 01:06 UTC, sabina-talipova commented on README.md
> +  default_link_title: 'My Phone Link'
Updated

2023-12-04 01:06 UTC, sabina-talipova commented on README.md
> +*app/_config/mylink.yml*
Updated

2023-12-04 01:06 UTC, sabina-talipova commented on README.md
> +}
Updated

2023-12-04 01:06 UTC, sabina-talipova commented on README.md
> +class ExternalLinkExtension extends DataExtension
Updated

2023-12-04 01:07 UTC, sabina-talipova commented on README.md
> +EG: `SilverStripe_LinkField_Models_Link` needs to be migrated to `LinkField_Link`.
Updated.

2023-12-04 01:07 UTC, sabina-talipova commented on src/Models/Link.php
> +        }
Updated

2023-12-04 01:07 UTC, sabina-talipova commented on templates/SilverStripe/LinkField/Models/Link.ss
> +</a>
Updated

2023-12-04 01:07 UTC, sabina-talipova commented on src/Models/Link.php
> +    public function getLinkTypeDefaultTitle(): string
Updated

2023-12-04 01:07 UTC, sabina-talipova commented on src/Models/Link.php
> +        return $this->config()->get('default_link_title');
Updated

2023-12-04 01:08 UTC, sabina-talipova commented on src/Models/SiteTreeLink.php
> +        $pageExist = $this->Page()->exists() && $this->getURL();
Updated

2023-12-04 01:08 UTC, sabina-talipova commented on src/Models/SiteTreeLink.php
> +                'Page missing',
Updated

2023-12-04 01:08 UTC, sabina-talipova commented on src/Models/SiteTreeLink.php
> +        return $this->getTitle();
Updated

2023-12-04 01:08 UTC, sabina-talipova commented on src/Models/SiteTreeLink.php
> +        $pageExist = $this->Page()->exists() && $this->getURL();
Updated

2023-12-04 01:08 UTC, sabina-talipova commented on src/Models/SiteTreeLink.php
> +    public function getLinkTypeDefaultTitle(): string
Updated

2023-12-04 02:08 UTC, ChloeSartorelli commented on README.md
> +*app/src/ExternalLinkExtension*
See https://github.com/silverstripe/silverstripe-linkfield/pull/126#discussion_r1413223536

2023-12-04 02:08 UTC, ChloeSartorelli commented on src/Models/Link.php
> +        if ($this->Title && $this->getURL()) {
```suggestion
        if ($this->Title) {
```
We don't care about the URL yet - this is explicitly about the title. If there's a title, display it. If not, use the default title.

The default title might use the URL.

2023-12-04 02:08 UTC, ChloeSartorelli commented on src/Models/Link.php
> +        return $this->getDescription() ?: $this->getURL();
```suggestion
        $default = $this->getDescription() ?: $this->getURL();
        if (!$default) {
            $default = _t(static::class . '.MISSING_DEFAULT_TITLE', 'No link provided');
        }
        return $default;
```

This is important, because if there's no description or URL we still need to display _something_ as the default title to avoid an empty `<a>` tag. People can still change what that is through localisation and through the extension hook, but we _do_ need to provide some default title in this scenario.

See https://github.com/silverstripe/silverstripe-linkfield/pull/126#discussion_r1413227926

2023-12-04 02:08 UTC, GuySartorelli commented on src/Models/SiteTreeLink.php
>          return $page->Title;
> Plus we populate field Title with this value

See this acceptance criteria:
> The Linkfield's title field will stay blank when not provided.

That's 100% why we need to _not_ use the page title in the `getTitle()` method. In fact we should remove that `getTitle()` method altogether.

The page title should _only_ be used as the default title. If it's returned from `getTitle()` it'll be stored in the database. This means if the page title changes, the link title will be outdated.

2023-12-04 02:08 UTC, GuySartorelli commented on src/Models/SiteTreeLink.php
>          return $page->Title;
> Plus we populate field Title with this value

See this acceptance criteria:
> The Linkfield's title field will stay blank when not provided.

That's 100% why we need to _not_ use the page title in the `getTitle()` method. In fact we should remove that `getTitle()` method altogether.

The page title should _only_ be used as the default title. If it's returned from `getTitle()` it'll be stored in the database. This means if the page title changes, the link title will be outdated.

2023-12-04 02:19 UTC, GuySartorelli requested changes

2023-12-04 02:19 UTC, GuySartorelli commented on src/Models/EmailLink.php
> +    }
```suggestion
```
Not needed - the implementation in `Link` is better.

2023-12-04 02:19 UTC, ChloeSartorelli commented on src/Models/ExternalLink.php
> +    }
```suggestion
```
Not needed - the implementation in `Link` is better.

2023-12-04 02:19 UTC, ChloeSartorelli commented on src/Models/FileLink.php
> +    }
```suggestion
```
Not needed - the implementation in `Link` is better.

2023-12-04 02:19 UTC, ChloeSartorelli commented on src/Models/FileLink.php
> +        return $file->exists() ? (string) $file->getFilename() : '';
Why did you make this change?

2023-12-04 02:19 UTC, GuySartorelli commented on src/Models/Link.php
> +            $titleField->setDescription(_t('LinkField.LINK_FIELD_TITLE_DESCRIPTION', 'If left blank, default title will be used'));
```suggestion
            $titleField->setDescription(_t(static::class . '.LINK_FIELD_TITLE_DESCRIPTION', 'If left blank, default title will be used'));
```
Sorry, should have caught this last time. 

The rationale for this is explained in https://github.com/silverstripe/silverstripe-linkfield/pull/126#discussion_r1413228980

2023-12-04 02:19 UTC, GuySartorelli commented on src/Models/PhoneLink.php
> +    }
```suggestion
```
Not needed - the implementation in `Link` is better.

2023-12-04 02:19 UTC, GuySartorelli commented on src/Models/FileLink.php
> +    }
Or else do something more similar to what's happening in `SiteTreeLink` since both use a relation to populate the URL

2023-12-04 02:19 UTC, GuySartorelli commented on tests/php/Models/Extensions/ExternalLinkExtension.php
> +namespace SilverStripe\LinkField\Tests\Models\Extensions;
```suggestion
namespace SilverStripe\LinkField\Tests\Extensions;
```
And move the `Extensions/` directory out of the `Models/` directory.

2023-12-04 02:19 UTC, GuySartorelli commented on tests/php/Models/LinkTest.php
> +                'PageLink1'
```suggestion
                'identifier' => 'page-link-1',
                'class' => SiteTreeLink::class,
                'expected' => 'PageLink1'
```
This makes it way clearer what each of these values represents. Please do this to all scenarios in this method.

2023-12-04 02:19 UTC, GuySartorelli commented on tests/php/Models/LinkTest.php
> +                ''
This is a bad expected result - we should have some default text here. The change in https://github.com/silverstripe/silverstripe-linkfield/pull/126#discussion_r1413295006 should resolve this scenario.

2023-12-04 02:19 UTC, GuySartorelli commented on tests/php/Models/LinkTest.php
Please also add a test scenario where a SiteTreeLink has no page relation, and therefore falls back to the localisation text.

2023-12-04 02:19 UTC, GuySartorelli commented on src/Models/Link.php
> +            $titleField->setDescription(_t('LinkField.LINK_FIELD_TITLE_DESCRIPTION', 'If left blank, default title will be used'));
```suggestion
            $titleField->setDescription(_t('LinkField.LINK_FIELD_TITLE_DESCRIPTION', 'If left blank, an appropriate default title will be used on the front-end'));
```

Just changing the wording a bit to more fully satisfy the following acceptance criterion:

> Feedback is provided to the user that they can leave LinkField title field blank.

By saying the default is "appropriate" is has more of a "you can leave this blank if you want to" feel to it.

2023-12-04 03:40 UTC, sabina-talipova commented on src/Models/EmailLink.php
> +    }
Updated

2023-12-04 03:40 UTC, sabina-talipova commented on src/Models/ExternalLink.php
> +    }
Updated

2023-12-04 03:46 UTC, sabina-talipova commented on src/Models/FileLink.php
> +    }
Updated

2023-12-04 03:46 UTC, sabina-talipova commented on src/Models/FileLink.php
> +        return $file->exists() ? (string) $file->getFilename() : '';
Updated

2023-12-04 03:48 UTC, sabina-talipova commented on src/Models/PhoneLink.php
> +    }
Updated

2023-12-04 03:51 UTC, sabina-talipova commented on src/Models/Link.php
> +            $titleField->setDescription(_t('LinkField.LINK_FIELD_TITLE_DESCRIPTION', 'If left blank, default title will be used'));
Updated

2023-12-04 03:56 UTC, sabina-talipova commented on tests/php/Models/Extensions/ExternalLinkExtension.php
> +namespace SilverStripe\LinkField\Tests\Models\Extensions;
Updated

2023-12-04 03:56 UTC, sabina-talipova commented on src/Models/Link.php
> +            $titleField->setDescription(_t('LinkField.LINK_FIELD_TITLE_DESCRIPTION', 'If left blank, default title will be used'));
Updated

2023-12-04 03:57 UTC, sabina-talipova commented on src/Models/Link.php
> +        if ($this->Title && $this->getURL()) {
Updated

2023-12-04 03:57 UTC, sabina-talipova commented on README.md
> +*app/src/ExternalLinkExtension*
Updated

2023-12-04 20:56 UTC, sabina-talipova commented on tests/php/Models/LinkTest.php
> +                ''
Updated

2023-12-04 20:56 UTC, sabina-talipova commented on tests/php/Models/LinkTest.php
Updated

2023-12-04 21:12 UTC, sabina-talipova commented on tests/php/Models/LinkTest.php
> +                'PageLink1'
Updated

2023-12-04 21:57 UTC, GuySartorelli approved these changes
Looks great, works well locally. Does everything it should do.

2023-12-04 21:58 UTC, merged