API Add new Owner relation for handling permissions
silverstripe/silverstripe-linkfield pull request #127
Opened 2023-12-04 04:53 UTC by GuySartorelli

## Dependencies
This PR requires https://github.com/silverstripe/silverstripe-framework/pull/11084 to function and for tests to go green but an installer CI run is linked in the issue.

## Issues
- https://github.com/silverstripe/silverstripe-linkfield/issues/5

2023-12-05 03:51 UTC, GuySartorelli commented on src/Models/FileLink.php
> + */
This isn't related but it needed to be added to avoid the PHPDoc for `Link` (which says "don't touch me" essentially) from leaking through to this class.

2023-12-05 03:51 UTC, GuySartorelli commented on src/Models/Link.php
> + * instance.
Rewording this so it makes more sense.

2023-12-05 03:52 UTC, GuySartorelli commented on src/Models/Link.php
> +    ];
See the associated framework PR and docs PR for more about this weird `has_one` syntax.

2023-12-05 03:53 UTC, GuySartorelli commented on src/Models/Link.php
> +    }
We're double handling `has_one` relations to link by storing the `has_one` _in the link as well_.

This allows us to use the `Owner` relation to check permissions, and to link to the owner in reports, etc.

The double handling is mitigated here by returning `null` if the owner says it doesn't know about the link.

2023-12-07 01:20 UTC, emteknetnz requested changes

2023-12-07 01:20 UTC, emteknetnz commented on README.md
> +        'HasManyLinksTwo' => Link::class . '.Owner',
I know it's best practice though does anyone actually suffixed on the the relationships?  This would only be required if there were multiple polymorphoic has_one's on Link correct?

I'd prefer to keep things simpler and more 'standard' (for the average user) which is to not have the relation suffix

2023-12-07 01:20 UTC, emteknetnz commented on README.md
> +        'HasManyLinksTwo' => Link::class . '.Owner',
Also means we don't need two has_many relationships for this example

2023-12-07 01:20 UTC, emteknetnz commented on src/Models/Link.php
> +            DataObjectSchema::HASONE_IS_MULTIRECIPROCAL => true,
I've suggested changing this in the framework PR

2023-12-10 20:41 UTC, GuySartorelli commented on README.md
> +        'HasManyLinksTwo' => Link::class . '.Owner',
> Also means we don't need two has_many relationships for this example

I think it's important to document having multiple has_many relations works without creating new has_one relations, or people might default to doing what they have always had to do and add more has_one relations via yaml.

> I'd prefer to keep things simpler and more 'standard' (for the average user) which is to not have the relation suffix

Our documentation should always follow best practices. It's embarrassing if someone follows our documentation and then the relation validation service complains that they've done it wrong.

2023-12-10 22:15 UTC, GuySartorelli commented on src/Models/Link.php
> +            DataObjectSchema::HASONE_IS_MULTIRECIPROCAL => true,
Done

2023-12-11 21:18 UTC, emteknetnz approved these changes

2023-12-11 21:18 UTC, emteknetnz requested changes
Needs rebase

2023-12-11 21:37 UTC, GuySartorelli commented
Rebased and conflicts resolved

2023-12-12 01:14 UTC, emteknetnz approved these changes

2023-12-12 01:14 UTC, merged