NEW Allowed link types
silverstripe/silverstripe-linkfield pull request #137
Opened 2023-12-07 00:21 UTC by sabina-talipova

## Description
- Added a new trait `AllowedLinkClassesTrait` that adds methods to set available link types or exclude them.
- The `Registry::class` has been removed.
- Files and methods for working with GraphQL have also been removed
- Added a service class to generate available existing Link classes

## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/15

2023-12-11 11:40 UTC, maxime-rainville requested changes
That's a good solid first pass. I tested it locally and it works great.

There wasn't an explicit AC for this, but I think logically we should have an exception thrown if you try to save a link of a type that is disallowed for the field. e.g. Your LinkField is configured to only allow EmailLink, but you do a manual AJAX query to save a SiteTreeLink into it.

2023-12-11 11:40 UTC, maxime-rainville commented on README.md
> +    private static $many_many = [
I don't think we'll have many-many support for links.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +    public static function generateAllLinkTypes(): array
Generally, when we make an injectable service, we make it's method instance method, rather than static.

```suggestion
    public function generateAllLinkTypes(): array
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +    public static function byKey(string $key): ?Link
```suggestion
    public function byKey(string $key): ?Link
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +    public static function keyByClassName(string $classname): ?string
```suggestion
    public function keyByClassName(string $classname): ?string
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +class LinkTypeService
```suggestion
/**
 * Class to manage which Link type can be added to LinkField form field.
 */
class LinkTypeService
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Models/Link.php
> +        $type = LinkTypeService::byKey($typeKey);
```suggestion
        $type = LinkTypeService::create()->byKey($typeKey);
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Models/Link.php
> +        $typeKey = LinkTypeService::keyByClassName(static::class);
```suggestion
        $typeKey = LinkTypeService::create()->keyByClassName(static::class);
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Models/Link.php
> +    public function getShortCode(): string
I would add a description.

Initially, I gave each link type a short code because I wasn't sure they would always match to an actual Link DataObject.

I think there's a simplicity argument for using the fully qualified name of Link classes instead of short code. But I'm not overly fuss about this part.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +    public static function definitionToType(string $className): Link
```suggestion
    public function definitionToType(string $className): Link
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +     * @throws InvalidArgumentException
Maybe add a description of the purpose of this method.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +
I would be inclined to let the Injector do its job here.

For example, I could use the Injector to map an alias for a link type. With that initial condition, that wouldn't work even if my alias maps to an actual link type via the injector.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +                _t(
We don't generally translate exception we don't expect the end user to see.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +trait AllowedLinkClassesTrait
Add a description.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +    public function list(): array
This method looks very out of place here. Having a method called `list` is very confusing. It doesn't look like it's returning a array of Link data object either.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +    protected $allowed_types = [];
```suggestion
    private $allowed_types = [];
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +        if (!is_array($types) || empty($types) || !$this->validateTypes($types)) {
We don't need to explicitly test that this is an array. If you call the method with something other than an array, you'll get an exception right away.
```suggestion
        if (empty($types) || !$this->validateTypes($types)) {
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +        if (is_array($types) || !empty($types)) {
```suggestion
        if (!empty($types)) {
```

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +    public function setDisabledTypes(array $types): static
I think the interaction between `setAllowedTypes` and `setDisabledTypes` could be very confusing. I'm not sure what a reasonnable developer should expect when chaining those methods. My instinct would be to only have `setAllowedTypes`.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +            if (is_subclass_of($class, Link::class)) {
Seems to me that this should throw an exception if you give it something that doesn't exists.

2023-12-11 11:40 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
I would be inclined to put this trait in the Form folder because it's so tightly tied to the fields.

2023-12-11 18:53 UTC, sabina-talipova commented on README.md
> +    private static $many_many = [
Link::class doesn't have relations with Page::class and follow this docs user cannot use `has_many = 'Second::class'` relation in First::class without having `has_one = 'First::class'` in the Second::class. [See](https://docs.silverstripe.org/en/5/developer_guides/model/relations/#has-many).

2023-12-11 19:05 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +    public static function generateAllLinkTypes(): array
Updated

2023-12-11 19:05 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +    public static function byKey(string $key): ?Link
Updated

2023-12-11 19:05 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +    public static function keyByClassName(string $classname): ?string
Updated

2023-12-11 19:09 UTC, sabina-talipova commented on src/Models/Link.php
> +        $type = LinkTypeService::byKey($typeKey);
Updated

2023-12-11 19:09 UTC, sabina-talipova commented on src/Models/Link.php
> +        $typeKey = LinkTypeService::keyByClassName(static::class);
Updated

2023-12-11 19:10 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +    public static function definitionToType(string $className): Link
Updated

2023-12-11 19:11 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
> +    protected $allowed_types = [];
Updated

2023-12-11 19:12 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
> +        if (!is_array($types) || empty($types) || !$this->validateTypes($types)) {
Updated

2023-12-11 19:12 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
> +        if (is_array($types) || !empty($types)) {
Updated

2023-12-11 19:19 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
> +    public function setDisabledTypes(array $types): static
Updated

2023-12-11 19:20 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
Updated

2023-12-11 20:02 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +class LinkTypeService
Updated

2023-12-11 22:01 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +                _t(
Updated. I removed this method and moved some of the logic to the trait.

2023-12-11 22:02 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
> +    public function list(): array
Updated. I moved logic to the `getTypesProps`.

2023-12-11 22:18 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
> +            if (is_subclass_of($class, Link::class)) {
I decided that it would be better if a complete list of all types of links was returned if the user passed something wrong or not a subclass of the Link class as a parameter.

2023-12-11 22:18 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +
Updated. I removed this method and moved some of the logic to the trait.

2023-12-11 22:20 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +     * @throws InvalidArgumentException
Updated. I removed this method and moved some of the logic to the trait.

2023-12-11 22:51 UTC, sabina-talipova commented on src/Models/Link.php
> +    public function getShortCode(): string
Updated. This keys are really helpful on front-end side

2023-12-11 22:51 UTC, sabina-talipova commented on src/Traits/AllowedLinkClassesTrait.php
> +trait AllowedLinkClassesTrait
Updated

2023-12-12 22:23 UTC, maxime-rainville commented on README.md
> +    private static $many_many = [
That problem should have been fixed by this. https://github.com/silverstripe/silverstripe-linkfield/pull/127/

2023-12-13 03:31 UTC, maxime-rainville requested changes
My biggest concern is that this won't work with Elemental.

I left a link to how to react props so it works with Elemental. If it doesn't make sense let me know, and we can go through it together.

2023-12-13 03:31 UTC, maxime-rainville commented on README.md
> +The user can control and specify the links allowed for creation in each link field. The `setAllowedTypes` method only includes link types that have been provided as parameters.
```suggestion
## Controlling what type of links can be created in a LinkField

By default, all `Link` subclasses can be created by a LinkField. This includes any custom `Link` subclasses defined in your projects or via third party module.

Developers can control the link types allowed for individual `LinkField`. The `setAllowedTypes` method only allow link types that have been provided as parameters.
```

2023-12-13 03:31 UTC, maxime-rainville commented on README.md
> +}
I think we can shrink this example and still have it legible.

```suggestion
$fields->addFieldsToTab(
    'Root.Main',
    [
        MultiLinkField::create('PageLinkList')
            ->setAllowedTypes([ SiteTreeLink::class ]),
        Link::create('EmailLink')
            ->setAllowedTypes([ EmailLink::class ]),
    ],
);
```

2023-12-13 03:31 UTC, maxime-rainville commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +     * Set allowed types for LinkField
```suggestion
     * Set allowed types for LinkField
     * @param string[] $types
```

2023-12-13 03:31 UTC, maxime-rainville commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +     * Validate types that they are subclasses of Link
```suggestion
     * Validate types that they are subclasses of Link
     * @param string[] $types
```

2023-12-13 03:31 UTC, maxime-rainville commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +        array_map(function (Link $type, string $key) use (&$typesList) {
You're not using `array_map` the way it's meant to be use here. Normally, `array_map` should have a 1-to-1 equivalence between the starting array and final array.

I think what you want to use here is `array_reduce`.

2023-12-13 03:31 UTC, maxime-rainville commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +        }, $types, array_keys($types));
I think this is more concise.

```suggestion
$typesList = [];
        $typeDefinitions = $this->genarateAllowedTypes();

        foreach ($typeDefinitions as $key => $class) {
            /** Link $type */
            $type = Injector::inst()->get($class);
            $typesList[$key] = [
                'key' => $key,
                'title' => $type->LinkTypeTile(),
                'handlerName' => $type->LinkTypeHandlerName(),
            ];
        }
```

2023-12-13 03:31 UTC, maxime-rainville commented on src/Models/Link.php
> +use SilverStripe\LinkField\Form\LinkField;
This import is not used.
```suggestion
```

2023-12-13 03:31 UTC, maxime-rainville commented on src/Models/Link.php
> +    public function getShortCode(): string
Happy to use the shortcode if we think there's value in it. A couple things thought.

## LinkTypeTile
`LinkTypeTile` is probably meant to be spelled `LinkTypeTitle`. This method is an artefact from when we had a LinkType interface and Link Types didn't need to be DataObject.

I would suggest deleting this method and using `i18n_singular_name` wherever we would have used `LinkTypeTile`

## ClassInfo::shortName()
We should use `ClassInfo::shortName($this)` for the short code instead of the user friendly name. I don't think it matters if we live the `Link` bit in there since the short code won't be displayed to the user in the end.

2023-12-13 03:31 UTC, maxime-rainville commented on tests/php/Traits/AllowedLinkClassesTraitTest.php
> +    public function allowedTypesDataProvider() : array
Some of those test case will fail if the project has a custom link type.

If I define a `FooLink` that extend `Link`, it will be returned in the list of allowed Link types and will cause this unit test to break.

2023-12-13 03:31 UTC, maxime-rainville commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +    public function getTypesProps(): string
The field doesn't currently work in Elemental.

When you load the LinkField in an Elemental block, the field gets bootstrap in a  different way than with Entwine.

The props have to be passed added to the return array of `getSchemaData`

You can look at this class for a good example: https://github.com/maxime-rainville/silverstripe-react/blob/0.1/src/ReactFormField.php

2023-12-13 03:31 UTC, maxime-rainville commented on src/Models/Link.php
> +    public function getShortCode(): string
This method is not covered by unit test.

2023-12-13 03:31 UTC, maxime-rainville commented on src/Services/LinkTypeService.php
> +class LinkTypeService
There's no unit test for this service.

2023-12-13 03:31 UTC, maxime-rainville commented on src/Traits/AllowedLinkClassesTrait.php
> +            if (is_subclass_of($class, Link::class)) {
If you're passing something that doesn't map to an actual Link DataObject, there's a high likelihood that there's a mistake in your code.

Logically, we should throw an exception in that scenario.

2023-12-14 19:13 UTC, sabina-talipova commented on README.md
> +The user can control and specify the links allowed for creation in each link field. The `setAllowedTypes` method only includes link types that have been provided as parameters.
Updated

2023-12-14 19:14 UTC, sabina-talipova commented on README.md
> +}
Updated

2023-12-14 19:15 UTC, sabina-talipova commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +     * Set allowed types for LinkField
Updated

2023-12-14 19:21 UTC, sabina-talipova commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +     * Validate types that they are subclasses of Link
Updated

2023-12-14 19:41 UTC, sabina-talipova commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +        array_map(function (Link $type, string $key) use (&$typesList) {
Updated

2023-12-14 19:43 UTC, sabina-talipova commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +        }, $types, array_keys($types));
Updated

2023-12-14 19:43 UTC, sabina-talipova commented on src/Models/Link.php
> +use SilverStripe\LinkField\Form\LinkField;
Updated

2023-12-14 19:49 UTC, sabina-talipova commented on src/Models/Link.php
> +    public function getShortCode(): string
Updated

2023-12-14 21:40 UTC, sabina-talipova commented on src/Services/LinkTypeService.php
> +class LinkTypeService
Updated

2023-12-14 22:25 UTC, sabina-talipova commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +    public function getTypesProps(): string
Updated. 
@maxime-rainville, could you test this with `private static bool $inline_editable = true;`

2023-12-14 22:27 UTC, sabina-talipova commented on tests/php/Traits/AllowedLinkClassesTraitTest.php
> +    public function allowedTypesDataProvider() : array
Updated

2023-12-17 23:45 UTC, sabina-talipova commented
https://github.com/silverstripe/silverstripe-linkfield/pull/137#discussion_r1424807464
Updated.

2023-12-18 02:11 UTC, sabina-talipova commented on src/Models/Link.php
> +    public function getShortCode(): string
Replaced `LinkTypeTile` with `$type->i18n_singular_name()`.

2023-12-18 05:09 UTC, maxime-rainville requested changes
It's almost there. Just a few ambiguities left to address.

2023-12-18 05:09 UTC, maxime-rainville commented on src/Models/Link.php
> +        return strtolower(str_replace([' ', 'Link'], '', ClassInfo::shortName($this))) ?? '';
This is a minor tweak.
- `ClassInfo::shortName` won't return spaces, so you don't need to remove spaces.
- It would a bit safer to only remove the `Link` part if it's at the end of the class name. So using `rtrim` would be a bit safer here.



```suggestion
        return strtolower(rtrim(ClassInfo::shortName($this), 'Link')) ?? '';
```

2023-12-18 05:09 UTC, maxime-rainville commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +    public function getTypesProps(): string
Works great and both usecase.

2023-12-18 05:09 UTC, maxime-rainville commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +    public function setAllowedTypes(array $types): static
What's our thinking when an empty array is passed to this method?
- Do we want to throw an exception?
- Do we want to unset any restriction and go back to allowing all Link types?

2023-12-18 05:09 UTC, maxime-rainville commented on templates/SilverStripe/LinkField/Form/LinkField.ss
> +<div data-field-id="$ID" data-schema-component="$SchemaComponent" class="entwine-linkfield" data-types="$TypesProps"></div>
That doesn't need to be handle here and now, but we'll probably want to pass all our props in a single attribute here. Otherwise, every time we'll need to make our bootstrapping logic more complex to handle things like read only state.

That's more of a comment. Nothing to action at this moment.

2023-12-18 05:09 UTC, maxime-rainville commented on tests/php/Services/LinkTypeServiceTest.php
> +     * @dataProvider allLinkTypesDataProvider
If you have only one test case, you shouldn't be using a data provider.

2023-12-18 19:03 UTC, sabina-talipova commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +    public function setAllowedTypes(array $types): static
I put my comment here https://github.com/silverstripe/silverstripe-linkfield/pull/137#issuecomment-1859327356.
I think empty array is invalid argument.

2023-12-18 19:09 UTC, sabina-talipova commented on src/Models/Link.php
> +        return strtolower(str_replace([' ', 'Link'], '', ClassInfo::shortName($this))) ?? '';
Updated

2023-12-18 19:17 UTC, sabina-talipova commented on tests/php/Services/LinkTypeServiceTest.php
> +     * @dataProvider allLinkTypesDataProvider
Updated

2023-12-19 23:09 UTC, maxime-rainville approved these changes
Happiness has been achieved.

2023-12-19 23:09 UTC, merged