ENH Tidy up permissions
silverstripe/silverstripe-linkfield pull request #141
Opened 2023-12-18 02:25 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/103

2023-12-19 02:47 UTC, emteknetnz commented on tests/php/Controllers/LinkFieldControllerTest.php
> -            // 'Valid update existing record' => [
A lot of these items in the data provider were previously merged while commented out, I've uncommented them

2023-12-19 23:13 UTC, GuySartorelli requested changes
## canCreate

With `canCreate` returning false, it still looks like I can add links: 
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/c222a047-f65e-4397-a202-ffa0cda1d160)

The modal is set to readonly, but I shouldn't even be able to get to the modal.

## canView for file and sitetree

It feels a bit weird that the "File Link:" and "SiteTree Link:" are just left blank - maybe we should have a "Cannot view file/page" or similar message there in red instead?

Also, do we have opinions about how the modal should treat those?
i.e:
- the treedropdown is still editable and shows the name of the page
    - Should it be editable if the user doesn't have view access to the page currently stored there?
    - Should the page title be visible in that field?
- The file upload field is still editable, but shows nothing (as though no file was saved)
    - Should it be editable?
    - Should it provide some feedback that there _is_ a file saved there, but the current user just isn't allowed to see it?

2023-12-19 23:13 UTC, ChloeSartorelli commented on babel.config.json
> +}
This isn't needed and was intentionally removed in https://github.com/silverstripe/silverstripe-linkfield/pull/120 - these two presets are already defined in the global webpack config.
See https://github.com/silverstripe/webpack-config/blob/5832637ef465be20afd50407cdae0185880166b5/js/modules.js#L15-L25

2023-12-19 23:13 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +      <LinkPickerMenu types={typeArray} onSelect={handleSelect} canCreate={canCreate} />
We're not even rendering the menu if we can't create, so we don't need to pass through this prop - the menu can just assume that if it's rendered it's allowed to create.

2023-12-19 23:13 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.js
> +        <div className="link-picker__cannot-create">Cannot create link</div>
Make this text translatable.

2023-12-20 21:02 UTC, emteknetnz commented on babel.config.json
> +}
Breaks with the jest test if this is removed, when we run `yarn test` we get

`SyntaxError: /path/to/vendor/silverstripe/linkfield/client/src/components/LinkPicker/tests/LinkPickerTitle-test.js: Support for the experimental syntax 'jsx' isn't currently enabled (21:32):`

2023-12-20 21:06 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +        <div className="link-picker__cannot-create">Cannot create link</div>
Updated

2023-12-20 21:40 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +      <LinkPickerMenu types={typeArray} onSelect={handleSelect} canCreate={canCreate} />
Removed and removed from LinkPickerMenu

2023-12-20 23:03 UTC, emteknetnz commented
- Have added a trait to LinkField/MultiLinkField that gets the Owner object from the Form, this allows us to check canCreate() on the Owner rather than using $field->Readonly()
- Have added a 'Cannot view file/page' styles messages instead of empty string
- Re the 'editable' bits for treedropdown and file upload - This PR adds a 'Cannot create link' if it fails a canCreate() check - this means you can't open the modal

2023-12-21 00:23 UTC, GuySartorelli commented on babel.config.json
> +}
Oh, weird! I wonder if that's why I added it in the various modules when I did the CMS 5 upgrade...
Too bad we can't add comments to json files.

2023-12-21 00:41 UTC, GuySartorelli requested changes
If I set `Link::canCreate()` to return false, I still get the option to open the modal. The changes I've requested in the code should fix this.

> Re the 'editable' bits for treedropdown and file upload - This PR adds a 'Cannot create link' if it fails a canCreate() check - this means you can't open the modal

This isn't about whether I can create a link. The scenarios is this:
- I already have a link to a file or to a page
- I do not have `canView()` permissions for the file/page that is being _linked to_
- I click on the link to edit it (which I _can do_ - I _do_ have edit permissions for the link itself)
  - The modal is fully editable. See https://github.com/silverstripe/silverstripe-linkfield/pull/141#pullrequestreview-1788110436 for how that modal behaves.

2023-12-21 00:41 UTC, GuySartorelli commented on src/Form/MultiLinkField.php
> +        $attributes['data-can-create'] = $this->getOwner()->canCreate();
We don't care if we can create a page - we care if we can create a link, which is:
```php
$this->getOwner()->canEdit() && Link::singleton()->canCreate()
```

We don't need to know if we can _create_ the owner. We just need to know if we can edit the owner, or create a link. If EITHER of those is false, we can't create the link. But creating the owner is irrelevant - the owner is _already_ created.

2023-12-21 00:41 UTC, GuySartorelli commented on src/Form/MultiLinkField.php
> +        $attributes['data-can-create'] = $this->getOwner()->canCreate();
Please also update this anywhere else you're doing a canCreate for links (e.g.`getSchemaStateDefaults()` above and in `LinkField`).
Might make sense to add it to the trait.

2023-12-21 00:41 UTC, GuySartorelli commented on src/Models/FileLink.php
> +            return _t('LinkField.FILE_DOES_NOT_EXIST', 'File does not exist');
```suggestion
            return _t(__CLASS__ . '.FILE_DOES_NOT_EXIST', 'File does not exist');
```
Same with any other PHP translation strings you're adding.
Some of the pre-existing ones are not set up like this, but they will be. See https://github.com/silverstripe/silverstripe-linkfield/issues/140

2023-12-21 00:42 UTC, GuySartorelli commented
I haven't tested this in a gridfield record or in an elemental block yet - just testing on a page until everything is working correctly in that context, then I'll check other contexts.

2023-12-21 02:57 UTC, emteknetnz commented on src/Models/FileLink.php
> +            return _t('LinkField.FILE_DOES_NOT_EXIST', 'File does not exist');
Updated

2023-12-21 03:30 UTC, GuySartorelli requested changes
Nearly there.

I've spun off my UX inconsistency concerns into a separate card: https://github.com/silverstripe/silverstripe-linkfield/issues/147

2023-12-21 03:30 UTC, GuySartorelli commented on src/Form/LinkField.php
> +        $data['canCreate'] = $this->getOwner()->canEdit() && Link::singleton()->canCreate();
```suggestion
        $data['canCreate'] = $this->getOwner()->canEdit();
```
You made a good point while we were discussing this in person - we have to respect the actual type of link being created - if we can create a `PhoneLink` but not `Link` then we need to respect that. You're doing that with the change to `AllowedLinkClassesTrait` so we should remove the `canCreate()` check from here.

You can also remove the `canEdit` (and this entire prop and its functionality) if you want - if owner's `canEdit()` method returns `false` then  the field will be set to readonly (which is being handled separately in https://github.com/silverstripe/silverstripe-linkfield/issues/11) so this prop won't matter in that scenario anyway.

We should probably also add some logic (assuming it's not there already) so that when there are _no_ available link types for the field, it has a nice message instead of a weirdly empty link type menu - though I'd be okay with that being spun off separately.

2023-12-21 03:30 UTC, GuySartorelli commented on src/Form/LinkField.php
> +        $data['canCreate'] = $this->getOwner()->canEdit() && Link::singleton()->canCreate();
Please also change this in the other places that pass this prop.

2023-12-21 04:31 UTC, emteknetnz commented on src/Form/LinkField.php
> +        $data['canCreate'] = $this->getOwner()->canEdit() && Link::singleton()->canCreate();
Updated

Have added AC to the [readonly card](https://github.com/silverstripe/silverstripe-linkfield/issues/11) to revisit the canEdit() logic, decide what to do with it then

Have created [new card](https://github.com/silverstripe/.github/issues/177) to handle the empty list scenario

2023-12-21 20:08 UTC, GuySartorelli approved these changes
LGTM, works well locally

2023-12-21 20:08 UTC, merged