ENH Save relations on link creation
silverstripe/silverstripe-linkfield pull request #146
Opened 2023-12-20 03:13 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/145

2023-12-21 20:11 UTC, GuySartorelli requested changes
Can you please rebase? The diff is a little weird at the moment, looks like tests are being removed but I don't think they are.

2023-12-21 21:02 UTC, emteknetnz commented
Done

2023-12-21 22:42 UTC, GuySartorelli requested changes
This PR has changed the order in which allowed links classes are displayed. The old order was better as it seems to be from top to bottom the most to least likely type of link to be added.
Before:
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/76ed2616-4752-47d6-aedf-ee813d93b902)
After:
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/936b435a-cd97-4db7-9049-250d921ef08b)

Other than that, *mostly* just questions rather than actually requesting changes this time around.

2023-12-21 22:42 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +        ownerRelation={ownerRelation}
```suggestion
```
No need for props since we have the context.

2023-12-21 22:42 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        }
I wonder if this should be in the `Link` model's `onAfterDelete()` instead, so it just happens any time a link is deleted, regardless of how it's deleted?
Not fussed either way but thought I'd raise it in case you think that's a better approach.

2023-12-21 22:42 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        }
Do we need to do this for every edit? Seems like it should just be on create.

2023-12-21 22:42 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        }
Probably also add a comment "not needed for has_many because that's stored directly on the link"
I know that's sort-of self-explanatory but I spend a few seconds going "wait why is has_many not being dealt with here?"

2023-12-21 22:42 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        $ownerRelation = $this->ownerRelationFromRequest();
Do we really need to check the owner from request at this stage? The link knows who its owner is already (`$link->Owner()`)

2023-12-21 22:42 UTC, GuySartorelli commented on src/Form/MultiLinkField.php
> -    }
We're deleting this but keeping the one in `LinkField` without any changes? What's the reasoning there?

2023-12-21 22:42 UTC, GuySartorelli commented on tests/php/Form/LinkFieldTest.php
Why is this being deleted? That method is still there.

2023-12-21 22:42 UTC, GuySartorelli commented on src/Form/Traits/LinkFieldGetOwnerTrait.php
> +        }
Use `ElementalAreaController::removeNamespacesFromFields()` instead.
```suggestion
        if ($owner instanceof  BaseElement) {
            $someVariableName = ElementalAreaController::removeNamespacesFromFields([$relation => ''], $owner->ID);
            $relation = array_keys($someVariableName)[0];
        }
```
I haven't tested that code but something like that should work.

2023-12-21 22:42 UTC, GuySartorelli commented on src/Form/Traits/LinkFieldGetOwnerTrait.php
> +        }
We probably also need a unit test for this

2023-12-21 22:48 UTC, GuySartorelli commented
I get "Invalid Owner" when I'm trying this in a record which _does already exist_ in a gridfield.
Happens for has_many _and_ has_one and for all link types.

2023-12-21 22:52 UTC, GuySartorelli commented
Obviously doesn't work when trying to add a link to a record that hasn't been saved to the DB yet - but we'll handle that in a separate card, it's not in scope for this.

2023-12-21 23:06 UTC, emteknetnz commented
Link order changed in this PR - https://github.com/silverstripe/silverstripe-linkfield/pull/137

2023-12-21 23:07 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +        ownerRelation={ownerRelation}
Removed

2023-12-21 23:11 UTC, emteknetnz commented on tests/php/Form/LinkFieldTest.php
Have restroed

2023-12-21 23:17 UTC, emteknetnz commented on tests/php/Form/LinkFieldTest.php
Method shouldn't be there

2023-12-21 23:18 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> -    }
Have deleted LinkField::saveInto()

2023-12-21 23:22 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        }
I think I prefer it in the controller, we're using that to related the two objects, seems sensible to also unrelated the objects in the controller too

Also this in only for has_one relations, if we put in in Link::onAfterDelete() it'll try and do it for has_many's as well which it shouldn't

2023-12-21 23:26 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $ownerRelation = $this->ownerRelationFromRequest();
Have added an line comment
```
        // Get owner using ownerFromRequest() rather than $link->Owner() so that validation is run
        // on the owner params before updating the database
```

2023-12-21 23:29 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        }
Have added a check to see that `$owner->"{$ownerRelation}ID" === 0`, meaning it will only do this onCreate()

Have added inline comment `// Only do this for has_one, not has_many, because that's stored directly on the Link record`

2023-12-21 23:56 UTC, emteknetnz commented on src/Form/Traits/LinkFieldGetOwnerTrait.php
> +        }
Done

2023-12-22 00:26 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        }
We have `$operation = 'create';` to check if the link is being created - so we should probably explicitly check that and _only_ do this if `$operation === 'create'`

2023-12-22 00:27 UTC, GuySartorelli requested changes
Just https://github.com/silverstripe/silverstripe-linkfield/pull/146#discussion_r1434609859 left

2023-12-22 01:29 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        }
Updated

2023-12-22 01:41 UTC, GuySartorelli approved these changes
LGTM

2023-12-22 01:41 UTC, merged