ENH Change clear text to delete
silverstripe/silverstripe-linkfield pull request #155
Opened 2024-01-08 23:16 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/149

2024-01-08 23:51 UTC, GuySartorelli requested changes
Works well locally. Just one small change.

2024-01-08 23:51 UTC, GuySartorelli commented on client/lang/en.js
> +    "LinkField.Delete": "Delete"
```suggestion
    "LinkField.DELETE": "Delete"
```
I would normally ignore this, but it's being referenced with all caps in the code so needs to be all caps here.

2024-01-08 23:52 UTC, GuySartorelli commented
I just had a thought - and feel free to say it's out of scope or not worth doing. But should this say "Archive" when links are versioned, and "Delete" when they're not? That _is_ more accurate, but I'm on the fence as to whether it's valuable enough of a distinction to be worth adding the complexity.

2024-01-09 03:03 UTC, emteknetnz commented
Have added in archived text functionality

2024-01-09 20:14 UTC, GuySartorelli approved these changes
Great! Works locally.

2024-01-09 20:14 UTC, merged