ENH Show save record first text on unsaved owners
silverstripe/silverstripe-linkfield pull request #159
Opened 2024-01-09 22:03 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/148

Looks like this on unsaved owners

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/de1f2835-83d9-4aba-b6c2-35127ad61f30)

2024-01-09 23:13 UTC, GuySartorelli requested changes
Works well locally - just a small change to the text and some questions about some small changes.

2024-01-09 23:13 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +import React, { useState, useEffect, createContext, Component } from 'react';
What is this change for?

2024-01-09 23:13 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +export { LinkField as Component };
What is this change for? Can the test not use the default export?

2024-01-09 23:13 UTC, GuySartorelli commented on client/lang/en.js
> +    "LinkField.SAVE_RECORD_FIRST": "Save record first"
```suggestion
    "LinkField.SAVE_RECORD_FIRST": "Save the record before adding links"
```
This is a message for a content author rather than a developer, so it pays to be a little more verbose.
You'll need to update it everywhere else too.

2024-01-09 23:13 UTC, GuySartorelli commented on client/lang/en.js
> +    "LinkField.SAVE_RECORD_FIRST": "Save record first"
I'm on the fence between this and "Cannot add links until the record has been saved", so take your pick between those (or some variation of those)

2024-01-09 23:15 UTC, GuySartorelli requested changes

2024-01-09 23:15 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.scss
> +  padding-top: 7px;
Convert padding to `rem` units, to match other padding in the CMS.

2024-01-10 00:26 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.scss
> +  padding-top: 7px;
px is much more common, and far more intuitive

Doing a regex search in `./vendor/silverstripe/**/*.scss` for:

`padding:.+rem` - 12 results in 7 files

`padding:.+px` - 86 results in 36 files

2024-01-10 00:28 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.scss
> +  padding-top: 7px;
Fair enough. I only looked at elements in the DOM near this element. Given there's a mix I guess it doesn't matter too much (until we go and change the font size but then this won't be the only area that needs fixing so it's a bit moot)

2024-01-10 00:31 UTC, emteknetnz commented on client/lang/en.js
> +    "LinkField.SAVE_RECORD_FIRST": "Save record first"
Updated

2024-01-10 00:31 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +import React, { useState, useEffect, createContext, Component } from 'react';
Removed

2024-01-10 00:32 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +export { LinkField as Component };
Nope, because it gets wired up to redux. This is a standard pattern used for doing jest tests.

2024-01-10 00:43 UTC, GuySartorelli approved these changes
LGTM, works well locally.

2024-01-10 00:43 UTC, merged