FIX Console warning about required type
silverstripe/silverstripe-linkfield pull request #163
Opened 2024-01-10 20:38 UTC by sabina-talipova

## Description
- Updated property required type for props `types`.
- If `$this->getOwner()->canEdit()` returns boolean value, then `$attributes['data-can-create']` is populated with `'data-can-create'` instead of boolean value.

## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/160

2024-01-10 20:56 UTC, emteknetnz requested changes
Note: I haven't tested locally

Should revert the using of string booleans because they're confusing and instead just rely on native Silverstripe behaviour.  Seems like the actual bug is coming from the use of `types` being an array instead of an object

2024-01-10 20:56 UTC, emteknetnz commented on src/Form/LinkField.php
> +        $attributes['data-can-create'] = $this->getOwner()->canEdit() ? 'true' : 'false';
I don't like the use of string booleans here, it gets confusing.  Revert this and just do things how Silverstripe does them natively

2024-01-10 20:56 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +        $attributes['data-can-create'] = $this->getOwner()->canEdit() ? 'true' : 'false';
Revert so that we're not using string booleans

2024-01-10 20:56 UTC, emteknetnz commented on client/src/entwine/LinkField.js
> +        types: this.data('types') ?? {},
Revert so that we're not using string booleans

2024-01-10 21:41 UTC, sabina-talipova commented on src/Form/LinkField.php
> +        $attributes['data-can-create'] = $this->getOwner()->canEdit() ? 'true' : 'false';
Updated

2024-01-10 21:41 UTC, sabina-talipova commented on src/Form/MultiLinkField.php
> +        $attributes['data-can-create'] = $this->getOwner()->canEdit() ? 'true' : 'false';
Updated

2024-01-10 21:43 UTC, sabina-talipova commented on client/src/entwine/LinkField.js
> +        types: this.data('types') ?? {},
I leave this part with new changes.

2024-01-10 21:55 UTC, sabina-talipova commented on client/src/entwine/LinkField.js
> +        types: this.data('types') ?? {},
If `canEdit()` returns true, then `data-can-create` attribute exists and `inputField.data('can-create')`  = `data-can-create`, if `canEdit()` returns false, then `inputField.data('can-create')`  = `undefined`. So we can use this in JS to return `true` instead of return a string `data-can-create`.

2024-01-11 02:26 UTC, emteknetnz approved these changes

2024-01-11 02:27 UTC, emteknetnz requested changes
Need to rebase to fix merge conflicts

2024-01-11 02:54 UTC, sabina-talipova commented
Rebased.

2024-01-11 05:28 UTC, emteknetnz approved these changes
Tested locally works good

2024-01-11 05:28 UTC, merged