MNT Use FQCN for PHP translations
silverstripe/silverstripe-linkfield pull request #164
Opened 2024-01-10 20:42 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/140

JS short classname namespace remains as it's the standard used in other modules e.g. admin

2024-01-10 22:10 UTC, sabina-talipova commented
Small question, should we also update en.yml file? Or will it have been updated automatically?

2024-01-11 02:13 UTC, emteknetnz commented
Good point. I've just run the text collector task on linkfield and committed the results

2024-01-11 03:41 UTC, GuySartorelli requested changes

2024-01-11 03:41 UTC, ChloeSartorelli commented on lang/en.yml
> +  SilverStripe\LinkField\Form\Traits\AllowedLinkClassesTrait:
Change references to these in the trait from `__CLASS__` to be the FCQN of the trait hardcoded, because:

https://www.php.net/manual/en/language.constants.magic.php
> When used in a trait method, __CLASS__ is the name of the class the trait is used in. 

In other words the call to `_t()` will pass in the name of the class (not the trait) - but here the key is the trait (not the class)

2024-01-11 05:29 UTC, emteknetnz commented on lang/en.yml
> +  SilverStripe\LinkField\Form\Traits\AllowedLinkClassesTrait:
Oh good spot :-)

2024-01-11 20:06 UTC, GuySartorelli commented on lang/en.yml
> +  SilverStripe\LinkField\Form\Traits\AllowedLinkClassesTrait:
OH, nice! I should have looked at that list I linked to a little longer, I didn't notice that option.

2024-01-11 20:07 UTC, GuySartorelli approved these changes
LGTM

2024-01-11 20:07 UTC, merged