ENH MutliLinkField sorting
silverstripe/silverstripe-linkfield pull request #166
Opened 2024-01-10 23:56 UTC by emteknetnz

2024-01-11 05:12 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.scss
> -    background: $gray-100;
Styling is currently a real mess, I've removed it because it was super obnoxious

I've created a new card to properly handle hover states https://github.com/silverstripe/silverstripe-linkfield/issues/168

2024-01-15 20:52 UTC, GuySartorelli requested changes
The bottom border of the last item in the list is missing:
Before:
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/47aab936-c77d-4020-8107-a30601245362)

This PR:
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/5da24916-a24f-44b8-9bd7-2c5f7a968f0a)

2024-01-15 21:05 UTC, GuySartorelli commented
I took this after rebasing so I don't have the scroll popping issue.

[Screencast from 16-01-24 10:00:44.webm](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/63c35011-9d04-4134-bedd-13306ba9d5d3)

There are two issues here. 

## Flickering

I think we shouldn't bother trying to show the loading component here because that flickering is just very visually distracting and doesn't have any clear benefit.

At some point that decision looks like it was made for elemental as well, because elemental doesn't show the loading component when sorting.

## Briefly rendered in the wrong order

Very briefly after letting go of the item I'm dragging, it pops back into its _original_ position, and then pops into its _new_ position after loading.

We should immediately render it in its new position after dropping, and only pop it back to its original position if something goes wrong with the network request to save the new sort order.

2024-01-15 22:00 UTC, GuySartorelli requested changes

2024-01-15 22:00 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +    { !isMulti && <div>{ renderLinks() }</div>}
Put all of this into a new function (with a traditional `if` statement) to keep things nice and tidy - it's quite hard to read scan-read this code as it is here.
Probably call it something like `renderLinksList()`

2024-01-15 22:00 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +    { !isMulti && <div>{ renderLinks() }</div>}
```suggestion
    { !isMulti && <div>{ links }</div>}
```
I presume this was the point of turning it into a variable

2024-01-15 22:00 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPicker.scss
> -    background: $gray-100;
I was originally going to say not to remove this since hover states are going to be treated separately - but removing that is actually a genuine improvement.

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            || isset($data['Sort'])
Why do we need this?
What if someone wants `Sort` to be a field that can be edited in the modal for their project, so they add it in?

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            $this->jsonError(400, _t(__CLASS__ . '.INVALID_TOKEN', 'Invalid CSRF token'));
It feels weird telling probably-someone-doing-something-they-shouldn't what they got wrong... do we give such verbose responses about invalid tokens anywhere other than linkfield?

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        $newLinkIDs = array_values($newLinkIDs);
Can you please explain to me why this is needed? A JSON array will always be 0-indexed anyway, won't it?

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        unset($newLinkIDs[0]);
Why are we adding `null` and then removing it? This feels like a hacky way to do something - though I'm not sure what it's doing?

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            }
If the link we can't edit isn't one of the links changing sort order, we shouldn't throw the error.
e.g:
- we have 4 links
- the 4th (last) link in the list can]t be edited
- we swap the top two links around

In that scenario we aren't editing the 4th link, so we don't care if we can edit it or not.

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            if (is_null($ownerID)) {
Some day we should really standardise `is_null` vs `=== null` (I think the latter is clearer) - but for now we haven't standardised that so I'll leave this alone :p

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            if (is_null($ownerID)) {
```suggestion
            // Validate that all links are in the same relation with the same owner
            // This protects against malicious actors manually executing requests.
            if (is_null($ownerID)) {
```
Just add a comment saying why we're doing this - 'cause these won't happen under normal execution.

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            }
```suggestion
            if (is_null($ownerID)) {
                $ownerID = $link->OwnerID;
                $ownerRelation = $link->OwnerRelation;
            } elseif ($link->OwnerID !== $ownerID || $link->OwnerRelation !== $ownerRelation) {
                $this->jsonError(400, _t('LinkField.BAD_DATA', 'Bad data'));
            }
```
Simplifying this since it's really part of the same check.

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        }
If the stuff in  was so that this `$sort` is 1-indexed:
1. Why 1-index it? What's wrong with 0-indexing?
2. If there's a really good reason to 1-index it, just change `$sort` here to `$index` and have a `$sort = $index + 1` because that's much clearer than what's going on up there.

2024-01-15 22:00 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        $form->Fields()->removeByName('Sort');
Should remove in `getCMSFields()` of `Link` instead.
```suggestion
```

2024-01-15 22:00 UTC, GuySartorelli commented on src/Models/Link.php
> +    private static $default_sort = '"Sort"';
```suggestion
    private static $default_sort = 'Sort';
```
Shouldn't need `"` here iirc. It's not passed into a raw SQL method.

2024-01-15 22:00 UTC, GuySartorelli commented on src/Models/Link.php
> +        // Esnure a Sort value is set
```suggestion
        // Ensure a Sort value is set
```

2024-01-15 22:00 UTC, GuySartorelli commented on src/Models/Link.php
> +        }
What's the intention here? Please add a comment to the code so it's clear going forward why we want this.

2024-01-15 22:03 UTC, GuySartorelli commented
Also needs rebase please

2024-01-16 23:02 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            || isset($data['Sort'])
It's to prevent a malicious integer overflow attack, have added comment

2024-01-16 23:06 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            $this->jsonError(400, _t(__CLASS__ . '.INVALID_TOKEN', 'Invalid CSRF token'));
We in in CSRFMiddleware in graphql, though beyond Graphql I don't think we do.  This can be useful to have this sort of thing as a dev message for developers.  I don't it makes things any easier for malicious users to do bad things so I think it's net positive.  All of LinkFieldController is already like this so best to keep as is for consistency. Was probably overkill making all the error messages translatable though :-)

2024-01-16 23:09 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $newLinkIDs = array_values($newLinkIDs);
Won't if you pass it in as an associate array defining integer indexes

2024-01-16 23:13 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        unset($newLinkIDs[0]);
It's so that we get a 1-index instead of a 0-index.  Basically it's more intuitive and standard to have a Sort value of 1 rather than 0.  Elemental also uses a 1-index

I've added a comment about this.

2024-01-16 23:18 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            }
Updated

2024-01-16 23:18 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            if (is_null($ownerID)) {
Updated

2024-01-16 23:20 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            }
Updated

2024-01-16 23:27 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        }
Already made a comment about about the 1-index
Have changed to `$sort = $i + 1`

2024-01-16 23:29 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $form->Fields()->removeByName('Sort');
Updated

2024-01-16 23:29 UTC, emteknetnz commented on src/Models/Link.php
> +    private static $default_sort = '"Sort"';
Updated

2024-01-16 23:29 UTC, emteknetnz commented on src/Models/Link.php
> +        // Esnure a Sort value is set
Updated

2024-01-16 23:31 UTC, emteknetnz commented on src/Models/Link.php
> +        }
It's so that newly created Links on MultiLinkFields are properly sorted. Have added comment

2024-01-17 00:18 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            || isset($data['Sort'])
I still don't understand this... can you please provide either some code so I can do this myself and see what happens (so I can see first hand what we're trying to avoid), or else explain further?

2024-01-17 01:06 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            || isset($data['Sort'])
If you set 'Sort' = the max value of integer, you'll no longer be able to create links on that relation because of the ->max('Sort') + 1 logic in LinkField::onBeforeWrite()

2024-01-17 01:09 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> -import LinkType from 'types/LinkType';
This is unrelated refactoring to remove an unused import

2024-01-17 01:09 UTC, emteknetnz commented on package.json
> +  "name": "silverstripe-linkfield",
This is unrelated refactoring to use the correct repo name

2024-01-17 01:10 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +    private static string $required_permission_codes = 'CMS_ACCESS_CMSMain';
This is required to make the controller accessible to non-admin users, came up during design review

2024-01-17 01:28 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +    { !isMulti && <div>{ renderLinks() }</div>}
Wasn't done, but it either looks tidier now or my brain has gotten used to it from seeing it a couple times. Either way, I'll allow this to remain not done.

2024-01-17 01:37 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            || isset($data['Sort'])
Okay, that makes sense.

~~It doesn't look like that would do anything here though? Since `$data` isn't actually directly used anywhere, other than specifically for `$data['File']['Files'][0]` which is obviously not going to include anything in `$data['Sort']`.~~

Ahh nevermind, `$form` would also contain that data and `$form->saveInto($link);` would save it in.
This feels like a bit of an odd hack for a super unlikely edgecase to me - but that said, I don't think it's likely to bite us in the butt either having it nor omitting it, and since it's here now it may as well stay.

2024-01-17 01:37 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            $this->jsonError(400, _t(__CLASS__ . '.INVALID_TOKEN', 'Invalid CSRF token'));
> I don't it makes things any easier for malicious users to do bad things

I'd argue that saying "You have an invalid CSRF token" is making it easier for malicious users to do bad things - they forgot the token, or had a bad token, and we're telling them that's what was wrong with their request which will make it really obvious what they need to change to perform a successful attack.

I don't feel super strongly about this so I'll let you decide if you want to leave it in, or if that context is enough to make you want to remove it.

2024-01-17 02:05 UTC, GuySartorelli requested changes
The actual sorting works really well now - I like that it's constrained to the parent and the vertical axis.

But now when I add new links, they don't appear until I refresh the page:
[Screencast from 17-01-24 15:03:47.webm](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/caa6285c-7cdc-4d06-92d9-ae430b2ef7f8)

2024-01-17 02:05 UTC, ChloeSartorelli commented on src/Controllers/LinkFieldController.php
> +        $newLinkIDs = array_values($newLinkIDs);
But the array we're dealing with is an array from the JSON body content of a request. Which we're sending as an array.

I'm guessing that you're trying to protect against someone making a manual request which has a JSON *object*, which would resolve here as an associative array?

If that's the case, I think it's a lot more sensible to let JSON objects resolve to `stdclass`, and then check `if (!is_array($newLinkIDs)) $this->jsonError(400);` 'Cause as soon as someone's doing that, it's bad data that we shouldn't try to _guess_ what it should have been (which resetting the array with `array_values()` is doing).

2024-01-17 02:05 UTC, ChloeSartorelli commented on src/Controllers/LinkFieldController.php
> +        $newLinkIDs = (array) $json['newLinkIDs'];
```suggestion
        $json = json_decode($request->getBody() ?? '', false);
        // If someone's passing a JSON object or other non-array here, they're doing something wrong
        if (!is_array($newLinkIDs)) {
            $this->jsonError(400);
        }
        
        $newLinkIDs = $json->newLinkIDs;
```
See discussion in https://github.com/silverstripe/silverstripe-linkfield/pull/166#discussion_r1452757193

2024-01-17 02:05 UTC, ChloeSartorelli commented on client/src/components/LinkPicker/LinkPicker.scss
> +    border-top-right-radius: 0.23rem;
Split these into their own `.link-picker__link--is-first,  .link-picker__link--is-sorting {` blocks.
When looking to find out where css is coming from, doing a code search for the full css class (e.g. search for `link-picker__link--is-first`).

Using the `&--` syntax makes this difficult, and unless the person doing the search thinks to check for that, they simply won't find the css in their search.

2024-01-17 02:14 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            $this->jsonError(400, _t(__CLASS__ . '.INVALID_TOKEN', 'Invalid CSRF token'));
Leave it in

2024-01-17 02:21 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.scss
> +    border-top-right-radius: 0.23rem;
Updated

2024-01-17 02:34 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $newLinkIDs = (array) $json['newLinkIDs'];
Updated

2024-01-17 04:15 UTC, GuySartorelli approved these changes
Looks great, works well locally.

2024-01-17 04:15 UTC, merged