ENH Add Readonly field status
silverstripe/silverstripe-linkfield pull request #172
Opened 2024-01-16 00:48 UTC by sabina-talipova

## Description

2024-01-16 20:44 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +        $isReadOnly = Injector::inst()->get($ownerClass)->getCMSFields()->dataFieldByName($ownerRelation)?->isReadonly();
This method gets Owner (e.g. Page) fields and check is this LinkField is read only.

2024-01-16 21:29 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +        return $isReadOnly ?? false;
`isReadOnly ` can be `null` in some cases.

2024-01-16 22:17 UTC, GuySartorelli commented
I'm not doing an actual review of this yet - just answering the question in the note:
> There is some problem here, how this should work if the user can edit the page, but `LinkField` is set to read only. Which should take precedence over `canEdit` or `ReadOnly`? Since if the field is read only, then a user with `canEdit` permission will not be able to create a link. Should there be a super user who can create links? Based on this discussion: https://github.com/silverstripe/silverstripe-linkfield/pull/141#discussion_r1433406199

Readonly is more important than `canEdit`. It doesn't matter if we can edit anything if the field has been set to readonly - readonly explicitly means we're not allowed to edit the field, even if we have edit permissions for the model or the model's owner.

2024-01-17 02:11 UTC, emteknetnz requested changes
I haven't tested locally yet

I really dislike the how 'readonly' has been stuffed into the value of 'canCreate'.  It makes things much harder to understand what's going on.

Instead you should make 'readonly' its own separate key / prop

2024-01-17 02:11 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.scss
> +  &.readonly {
```suggestion
  &--readonly {
```
Safer to use a BEM class rather than a generic/global `readonly` that may accidentally get values set from somewhere else

You'll need to update this is bunch of places in this PR

2024-01-17 02:11 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    {(canDelete && canCreate) &&
This logic looks wrong, shouldn't have a `canCreate` check for a delete button

2024-01-17 02:11 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        if (strpos($ownerRelation, '_Readonly') !== false) {
Why are we doing this with $ownerRelation?  Owner relation should be what's set in the private static $has_many, not the `_Readonly` added to form fields when they are set to read only mode?

2024-01-17 02:11 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $ownerClass = $request->getVar('ownerClass') ?: $request->postVar('OwnerClass');
Create a new private method getOwnerClassFromRequest() so that it's consistent with the rest of the file and throw a 404 error if the owner class !is_a DataObject

2024-01-17 02:11 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $isReadOnly = Injector::inst()->get($ownerClass)->getCMSFields()->dataFieldByName($ownerRelation)?->isReadonly();
```suggestion
        return (bool) Injector::inst()->get($ownerClass)->getCMSFields()->dataFieldByName($ownerRelation)?->isReadonly();
```

2024-01-17 02:11 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        return $isReadOnly ?? false;
```suggestion
```

2024-01-17 23:30 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    {(canDelete && canCreate) &&
Updated. I have to use `readonly`, since we should hide "Archive" button if user cannot edit link field.

2024-01-17 23:30 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPicker.scss
> +  &.readonly {
Updated

2024-01-17 23:30 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +        if (strpos($ownerRelation, '_Readonly') !== false) {
Updated

2024-01-17 23:30 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +        $ownerClass = $request->getVar('ownerClass') ?: $request->postVar('OwnerClass');
Updated

2024-01-17 23:30 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +        $isReadOnly = Injector::inst()->get($ownerClass)->getCMSFields()->dataFieldByName($ownerRelation)?->isReadonly();
Updated

2024-01-17 23:30 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +        return $isReadOnly ?? false;
Updated

2024-01-18 01:14 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +        $isReadOnly = Injector::inst()->get($ownerClass)->getCMSFields()->dataFieldByName($ownerRelation)?->isReadonly();
This doesn't take into account scenarios where the _form_ was set to readonly, which I believe is what happens when the user doesn't have edit permission for the owner record (e.g. a page).

2024-01-19 03:52 UTC, emteknetnz requested changes
I'm still able to sort links in a MultiLinkField when it's in a readonly state

Also needs a rebase

2024-01-19 03:52 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            $form->setMessage(_t(__CLASS__ . '.READ_ONLY_MESSAGE', 'You do not have enough permissions to edit this form'), 'info');
I'm not sure we should be setting a form message here. Can you find any other examples of us doing this?

If we do keep it, the message is wrong when the form has been manually set to read only rather than because of a lack of permissions

2024-01-19 03:52 UTC, emteknetnz commented on client/src/components/LinkPicker/tests/LinkPickerTitle-test.js
> +test('LinkPickerTitle render() should have readonly class if cannot edit', () => {
```suggestion
test('LinkPickerTitle render() should have readonly class if set to readonly', () => {
```

2024-01-19 03:52 UTC, emteknetnz commented on client/src/components/LinkPicker/tests/LinkPickerTitle-test.js
> +test('LinkPickerTitle render() should not have readonly class if can edit', () => {
```suggestion
test('LinkPickerTitle render() should not have readonly class if set to readonly', () => {
```

2024-01-22 19:57 UTC, sabina-talipova commented on client/src/components/LinkPicker/tests/LinkPickerTitle-test.js
> +test('LinkPickerTitle render() should have readonly class if cannot edit', () => {
Updated

2024-01-22 19:57 UTC, sabina-talipova commented on client/src/components/LinkPicker/tests/LinkPickerTitle-test.js
> +test('LinkPickerTitle render() should not have readonly class if can edit', () => {
Updated

2024-01-22 23:38 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +            $form->setMessage(_t(__CLASS__ . '.READ_ONLY_MESSAGE', 'You do not have enough permissions to edit this form'), 'info');
@emteknetnz, I could not find any similar example. I think it was new requirements from Design team. I moved logic only for readonly field.

2024-01-23 21:22 UTC, emteknetnz requested changes

2024-01-23 21:22 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        if ($this->isReadOnlyField()) {
This message feels even more out of place now

It will now only show if `$this->isReadOnlyField()` is explicitly called, though not if `$this->canEdit()` is false or if the owner page/element `canEdit()` returns false which seems worse because it's inconsistent.

We also don't show this message anywhere else in the CMS as far as we know

I think we should just remove this message, it's seems pretty obvious that the form is readonly because the background of all the form elements if grey

Perhaps raise a new card to add this to globally add this message to forms through the CMS instead?

2024-01-23 21:39 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
> +        if ($this->isReadOnlyField()) {
Updated

2024-01-23 22:30 UTC, emteknetnz requested changes
Merge conflicts, needs a rebase

2024-01-24 01:26 UTC, emteknetnz approved these changes

2024-01-24 01:27 UTC, merged