ENH Show a cannot create message when types is empty
silverstripe/silverstripe-linkfield pull request #174
Opened 2024-01-17 22:47 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/151

2024-01-17 22:47 UTC, emteknetnz commented on src/Form/Traits/AllowedLinkClassesTrait.php
> +    private array $allowedTypes = [];
Changing the casing in unrelated refactoring

2024-01-18 03:24 UTC, sabina-talipova requested changes
I've tested locally, works perfect. Looks good, just small question.

2024-01-18 03:24 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPicker.js
> +  if (!canCreate || typeArray.length === 0) {
Probably, we should divide when user cannot create link and when there is not available link types.

2024-01-18 04:19 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.js
> +  if (!canCreate || typeArray.length === 0) {
I'm not sure why we want to have separate logic here? The end result of both of seems like it should be the same, a message saying that you cannot create a link

What else would we do here if we split the logic?

2024-01-18 04:34 UTC, GuySartorelli commented on src/Form/Traits/AllowedLinkClassesTrait.php
> -            throw new InvalidArgumentException(
Still need to throw this exception if developers pass in an empty array - see acceptance criteria

2024-01-18 04:53 UTC, emteknetnz commented on src/Form/Traits/AllowedLinkClassesTrait.php
> -            throw new InvalidArgumentException(
Ah yup my bad, didn't need to change any PHP in the end, have reverted

2024-01-18 19:58 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPicker.js
> +  if (!canCreate || typeArray.length === 0) {
No, everything looks good to me.

2024-01-18 20:00 UTC, sabina-talipova approved these changes
LGTM.

2024-01-18 20:01 UTC, merged