ENH Add disabled field state
silverstripe/silverstripe-linkfield pull request #189
Opened 2024-01-24 23:26 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/181

2024-01-25 02:42 UTC, sabina-talipova requested changes
@emteknetnz, it looks like we should modify [LinkFieldController::isReadOnlyField](https://github.com/silverstripe/silverstripe-linkfield/blob/f5d54ac9a91cfcbbd42daa421d3e41f055266745/src/Controllers/LinkFieldController.php#L395C22-L401) to check `LinkField->isDisable()`. Currently if we click on any disable link field we still can open modal window and edit link content.

2024-01-25 03:49 UTC, emteknetnz commented
Updated

2024-01-25 03:50 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +        $ownerRelation = $this->getOwnerRelationFromRequest();
I've done some unrelated refactoring to ensure that all of the "ownerFrom*" methods are prefixed with "get" i.e. "getOwnerForm*"

Previously there was a mixture of methods with the prefix and those without

2024-01-25 03:51 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> -use SilverStripe\Security\Security;
This is unrelated refactoring to remove an unused import

2024-01-25 22:02 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
>              $form->makeReadonly();
Now, it works as expected with one small issue, it use `readonly` attribute instead of `disabled` for all inputs. 
If you test here `$form->transform(new DisabledTransformation());` all input fields in modal window will get proper attribute `disabled`. Probably, the logic for disabled form should be extracted from readonly logic. 

And another small issue that element with class `.link-picker__link` has attribute `aria-disabled="false"`, but I assume it should be `aria-disabled="true"` or it should be removed.

2024-01-25 22:06 UTC, sabina-talipova requested changes

2024-01-25 22:06 UTC, sabina-talipova commented on src/Controllers/LinkFieldController.php
>              $form->makeReadonly();
Now, it works as expected with one small issue, it use `readonly` attribute instead of `disabled` for all inputs. 
If you test here `$form->transform(new DisabledTransformation());` all input fields in modal window will get proper attribute `disabled`(but unfortunately it doesn't work with DropdownField). Probably, the logic for disabled form should be extracted from readonly logic. 

And another small issue that element with class `.link-picker__link` has attribute `aria-disabled="false"`, but I assume it should be `aria-disabled="true"` or it should be removed.

2024-01-26 02:17 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
>              $form->makeReadonly();
In the issue notes it says:

"We discussed whether disabled or readonly should have any practical difference. We concluded it wasn't really worth treating them as separate use cases."

Basically disabled is such a narrow use case it's not worth investing much time getting this working exactly as it should.

Given that I don't think we should spend any time fixing either of these small issues

2024-01-28 19:48 UTC, sabina-talipova approved these changes
Test locally. All works perfect.

2024-01-28 19:48 UTC, merged