ENH Improve hover active and focus state styling
silverstripe/silverstripe-linkfield pull request #191
Opened 2024-01-25 05:15 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/168

2024-01-26 02:07 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +        <span className="link-picker__delete btn btn-link" onClick={stopPropagation(() => !loading ? onDelete(id) : null)}>{deleteText}</span>
This has changed from a `<Button>` to a `<span>` because there's a error in yarn build that you cannot have a `<Button>` be a child of a `<Button>`

I've added the `btn btn-link` classes so that it still styles the same as the `<Button>`

2024-01-29 00:06 UTC, sabina-talipova requested changes

2024-01-29 00:06 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +        <span className="link-picker__delete btn btn-link" onClick={stopPropagation(() => !loading ? onDelete(id) : null)}>{deleteText}</span>
Everything looks good, just small issue.
When we change `<button>` to `<span>` we lose all available button functionality. So now we lose focus on Archive button and when we use keyboard we cannot press "Archive" button.
Probably we should add additional attributes ([see](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#basic_button_example)) and define onKeyDown method.
E.g. 
```js
<span role="button" tabIndex="0" className="link-picker__delete btn btn-link" onKeyDown={stopPropagation(() => !loading ? onDelete(id) : null)} onClick={stopPropagation(() => !loading ? onDelete(id) : null)}>{deleteText}</span>
```

2024-01-29 00:27 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +        <span className="link-picker__delete btn btn-link" onClick={stopPropagation(() => !loading ? onDelete(id) : null)}>{deleteText}</span>
Updated

2024-01-29 01:18 UTC, sabina-talipova requested changes
@emteknetnz, there are still some issues with "span like button":
- if we use keyboard and press "Archive" then select "Cancel" in confirmation window the Link edit modal window will be open after browser confirmation window.
- Small style issue with External links. 
![Screenshot 2024-01-29 at 2 02 10 PM](https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/0df16dfb-1ba2-44c6-83a7-f98ec045b4b5)

2024-01-29 03:28 UTC, sabina-talipova requested changes

2024-01-29 03:28 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +            preventDefaultPropogation(evt);
@emteknetnz , could you, please, update this method. Since we have a small issue with moving further.
Probably we should replace it with `stopPropagation` and add `evt.preventDefault()` after `onDelete(id)`

Before (Cannot select Button below)

https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/4f4fa81a-a02b-4259-9e5d-065f1a49d0f5

After:

https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/9b28bc61-dfb5-4f1c-b504-22fb90c908c4

2024-01-29 19:55 UTC, sabina-talipova approved these changes
LGTM. Tested locally, it works as expected.

2024-01-29 19:56 UTC, merged