ENH Set Published button dirty state when Link is an unpublished state
silverstripe/silverstripe-linkfield pull request #193
Opened 2024-01-30 01:36 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/152

I've tested this for:
- Links on Pages
- Links on Elemental
- Links on DataObjects managed by ModelAdmins

It will set the "Publish" button to a dirty state when the LinkPickerTitle has either a 'Draft' or a 'Modified' versionedState.  It won't change the state of "Save" button as LinkField constantly saves everything via AJAX.

Note that for Elemental this is only true if the Link if modifed via the link modal.  The "Save" button will still get a dirty state when new links are added or deleted.  This is due to existing logic in Elemental to that will trigger the jQuery changetracker which will alter both the Save and the Publish buttons.  There's nothing we can really do about this without a lot of hacking around it, and I don't think this is worth it since a dirty Save button is far from the worse thing ever.

2024-01-30 01:37 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  const handleDelete = (linkID, deleteType) => {
This is unrelated refactoring to follow the consistent naming of defining 'handle*' methods and passing them to 'on*' props

2024-01-31 04:04 UTC, sabina-talipova requested changes

2024-01-31 04:04 UTC, sabina-talipova commented on client/src/components/LinkField/LinkField.js
> +    });
Everything works perfect, as expected. But there is a small issue here. If somehow we pass empty string as class name then we get `Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.`. Probably we should check that `dataBtnAlternateRemove`, `dataBtnAlternateAdd `, `dataTextAlternate ` are not empty string before.

2024-01-31 21:45 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +    });
Have added a couple of `if (className) {` checks

2024-01-31 23:11 UTC, sabina-talipova approved these changes
LGTM. Tested locally.

2024-01-31 23:12 UTC, merged