ENH Improve keyboard support
silverstripe/silverstripe-linkfield pull request #200
Opened 2024-02-01 03:13 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/99

2024-02-01 23:10 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> -  onNonPublishedVersionedState,
This is unrelated refactoring to remove a non-existant prop

2024-02-01 23:10 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> -import { injectGraphql } from 'lib/Injector';
This is unrelated refactoring to remove an unused import

2024-02-01 23:12 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.scss
> +    opacity: 0%;
Using opacity instead of display so that it can be tabbed to

2024-02-01 23:29 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> -          onKeyDown={(evt) => {
This is unrelated refactoring, moved to handleDeleteKeyDown()

2024-02-01 23:29 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  const handleDeleteKeyDown = (event) => {
This is unrelated refactoring, was previously an inline method in render() for onKeyDown

2024-02-08 21:44 UTC, sabina-talipova requested changes
Looks good, works perfect. Just tiny possible improvements.

2024-02-08 21:44 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPicker.scss
I'm not sure if this is a big problem, but shouldn't we use the same style when focusing on linkfield elements? What is the opinion of the designers?
<img width="498" alt="Screenshot 2024-02-09 at 8 47 15 AM" src="https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/bd249d29-2891-4225-b7de-72237f905cd2">
<img width="498" alt="Screenshot 2024-02-09 at 8 57 36 AM" src="https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/83147887-7177-4783-855d-b1a7ed33aa21">

2024-02-08 21:44 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    </div> }
```suggestion
    { (isMulti && !readonly && !disabled) && <div className="link-picker__drag-handle"
        tabIndex="0"
        role="button"
        aria-pressed="false"
        aria-controls={idAttr}
        aria-label="Sort Links"
        onKeyDown={handleIconKeyDown}
    >
      <i
        className="font-icon-drag-handle"
        aria-hidden="true"
        focusable="false"
      ></i>
    </div> }
```

2024-02-08 21:44 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    </div> }
Probably, would be better to use as a button `div` element instead of `icon`. 
And also, please, add `aria-label="Sort Links"` since this element doesn't have any content that explains what this button does.

2024-02-08 21:44 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +      onKeyDown={handleButtonKeyDown}
This element also should have `aria-label` attribute with something like "Add link" or "Edit link".
Otherwise, screen reader reads it as something like this `DRAFT Phone number: 1234567833333 Archive`.
This is a good article about `area` attributes. https://www.sarasoueidan.com/blog/accessible-icon-buttons/

2024-02-08 21:44 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +          onKeyDown={handleDeleteKeyDown}
```suggestion
          onKeyDown={handleDeleteKeyDown}
          aria-label={deleteText}
```

2024-02-08 21:44 UTC, sabina-talipova commented on client/src/components/LinkField/LinkField.js
> +  useEffect(() => {
Just small question. Double execution of logic in `useEffect` won't it be a reason for some problems with `setInterval`?

2024-02-11 23:26 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  useEffect(() => {
No, it'll just create a separate reference to a new internal.

2024-02-11 23:28 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPicker.scss
I talked to design about this, they said they're happy with this as it's a default browser style and there's no need to override this as it's obvious what it's doing

2024-02-11 23:32 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +      onKeyDown={handleButtonKeyDown}
UpIdated

2024-02-11 23:42 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    </div> }
Updated

2024-02-12 03:00 UTC, sabina-talipova requested changes
@emteknetnz, could you please fix this one as well https://github.com/silverstripe/silverstripe-linkfield/pull/200/files#r1483616400

2024-02-12 03:08 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +          onKeyDown={handleDeleteKeyDown}
I added this on line 167

2024-02-12 06:47 UTC, emteknetnz commented
@sabina-talipova Have updated

2024-02-12 19:34 UTC, sabina-talipova approved these changes
LGTM. Test locally, works perfect.

2024-02-12 19:35 UTC, merged