NEW LinkField Behat tests
silverstripe/silverstripe-linkfield pull request #201
Opened 2024-02-05 00:07 UTC by sabina-talipova

## Description

## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/98

2024-02-07 23:53 UTC, sabina-talipova commented
Failed tests require https://github.com/silverstripe/silverstripe-frameworktest/pull/162

2024-02-08 04:03 UTC, emteknetnz requested changes
You've committed the two behat files with tabs instead of spaces. Please use 2 spaces per indent.

As per the frameworktest PR, copy in code form that PR as extensions and update this test to use those here

2024-02-08 04:03 UTC, emteknetnz commented on tests/behat/features/linkfield-in-elemental.feature
> +			# And I should see "Phone" in the "#Form_ElementForm_1_PageElements_1_ManyLinks_Holder .link-picker__link--is-first" element
```suggestion
```

2024-02-08 04:03 UTC, emteknetnz commented on tests/behat/features/create-edit-linkfield.feature
> +			Given I add an extension "SilverStripe\FrameworkTest\LinkField\Extensions\LinkPageExtension" to the "Page" class
Update this to the new namespace of the extension copied in from the frameworktest PR
Also add in the new ElementContent extension I've mentioned on the frameworktest PR

Do this for the other behat file as well

2024-02-08 04:03 UTC, emteknetnz commented on tests/behat/features/create-edit-linkfield.feature
> +			Then I fill in "Form_LinkForm_0_ExternalUrl" with "https://www.silverstripe.org"
Also add in a quick test here with an invalid URL to test that validation is working, then update it to a valid url

2024-02-08 04:03 UTC, emteknetnz commented on tests/behat/features/linkfield-in-elemental.feature
> +
```suggestion

```

2024-02-08 22:17 UTC, sabina-talipova commented on tests/behat/features/linkfield-in-elemental.feature
> +			# And I should see "Phone" in the "#Form_ElementForm_1_PageElements_1_ManyLinks_Holder .link-picker__link--is-first" element
Updated

2024-02-08 22:56 UTC, sabina-talipova commented on tests/behat/features/create-edit-linkfield.feature
> +			Given I add an extension "SilverStripe\FrameworkTest\LinkField\Extensions\LinkPageExtension" to the "Page" class
Updated

2024-02-08 22:56 UTC, sabina-talipova commented on tests/behat/features/create-edit-linkfield.feature
> +			Then I fill in "Form_LinkForm_0_ExternalUrl" with "https://www.silverstripe.org"
Updated

2024-02-08 22:58 UTC, sabina-talipova commented on tests/behat/features/linkfield-in-elemental.feature
> +
Updated

2024-02-09 00:33 UTC, sabina-talipova commented on tests/behat/features/create-edit-linkfield.feature
> +			Then I fill in "Form_LinkForm_0_ExternalUrl" with "https://www.silverstripe.org"
Updated

2024-02-09 01:28 UTC, sabina-talipova commented on tests/behat/features/create-edit-linkfield.feature
> +		Then I should see "Page is required" in the ".modal-content" element
Add test for validation

2024-02-09 01:29 UTC, sabina-talipova commented on tests/behat/features/create-edit-linkfield.feature
> +		And I fill in "Form_LinkForm_0_ExternalUrl" with "w1234@$%"
Add test for invalid URL

2024-02-09 01:30 UTC, sabina-talipova commented on tests/behat/features/linkfield-in-elemental.feature
> +    Then I click on the ".font-icon-block-content" element
I have to change this to class name since there are more than one "Content" button on the page

2024-02-09 01:31 UTC, sabina-talipova commented on tests/behat/features/create-edit-linkfield.feature
> +			And I go to "/dev/build?flush"
We should rebuild DB after new Extension was applied.

2024-02-09 01:36 UTC, sabina-talipova commented
Tests passed https://github.com/sabina-talipova/recipe-kitchen-sink/actions/runs/7838380470/job/21389726059

2024-02-12 04:08 UTC, emteknetnz requested changes
You still need to update the behat files to use spaces instead of tabs

2024-02-12 23:35 UTC, emteknetnz approved these changes
Will merge once the corresponding frameworktest PR is merge

2024-02-13 01:29 UTC, emteknetnz requested changes
You'll need to add "silverstripe/frameworktest": "^1" to "require-dev" in composer.json

2024-02-13 03:35 UTC, sabina-talipova commented
Updated. Sorry, I removed and forgot to return back.

2024-02-13 20:37 UTC, emteknetnz approved these changes

2024-02-13 20:37 UTC, merged