ENH Rename and move Title field
silverstripe/silverstripe-linkfield pull request #207
Opened 2024-02-07 22:20 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/179

2024-02-07 23:00 UTC, emteknetnz commented on tests/php/Models/LinkTest.php
> -    public function testGetUrl(string $identifier, string $class, string $expected): void
This is unrelated refactoring to move the data provider above the unit test to match the rest of the file

2024-02-07 23:01 UTC, emteknetnz commented on tests/php/Models/LinkTest.php
> -    function linkDefaultTitleDataProvider(): array
This is unrelated refactoring to rename this to `provideGetUrl()` to match our conventions

2024-02-07 23:01 UTC, emteknetnz commented on tests/php/Models/LinkTest.php
> +     * @dataProvider provideDefaultLinkTitle
This is unrelated refactoring to get this to match our naming conventions

2024-02-07 23:58 UTC, emteknetnz commented on lang/en.yml
> +    MISSING_DEFAULT_TITLE: '(No value provided)'
Since we're now always showing a title, this was the default provided for custom links without LinkText - I've updated it to something more sensible since it's more likely the custom link have a "value" rather that a "link (to a relation)"

2024-02-07 23:59 UTC, emteknetnz commented on src/Models/FileLink.php
> +            return _t(__CLASS__ . '.MISSING_DEFAULT_TITLE', '(File missing)');
This is unrelated refactoring to add brackets to "File missing" and "Page missing" default titles so that it matches "(No value provided)" for generic links

2024-02-08 00:18 UTC, emteknetnz commented on lang/en.yml
> +    MISSING_DEFAULT_TITLE: '(File missing)'
This is unrelated refactoring to add brackets to "File missing" and "Page missing" default titles so that it matches "(No value provided)" for generic links

2024-02-08 00:21 UTC, emteknetnz commented on tests/php/Controllers/LinkFieldControllerTest.php
> +            $this->assertSame('Phone', $formSchema['schema']['fields'][0]['children'][0]['children'][0]['name']);
These array index changes are required because we're move LinkText to the bottom in getCMSFields()

2024-02-08 00:58 UTC, GuySartorelli requested changes
Most of the way there, just a few things to tidy up

2024-02-08 00:58 UTC, ChloeSartorelli commented on README.md
> +
```suggestion
```

2024-02-08 00:58 UTC, ChloeSartorelli commented on README.md
> +You can manually rename this column in your database with the following:
```suggestion
You can manually rename this column in your database with the following code:
```

2024-02-08 00:58 UTC, ChloeSartorelli commented on README.md
> +## Migration form LinkField v3 to v4
```suggestion
## Migration from LinkField v3 to v4
```

2024-02-08 00:58 UTC, ChloeSartorelli commented on README.md
> +```
````suggestion
```

It's recommended to put this code in a `BuildTask` so that you can run it exactly once, and then remove that code in a future deployment.
````

2024-02-08 00:58 UTC, ChloeSartorelli commented on README.md
> +DB::get_conn()->getSchemaManager()->renameField('LinkField_Link', 'Title', 'LinkText');
```suggestion
use SilverStripe\LinkField\Models\Link;
use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\DB;

// Only run this once
// This will rename the `Title` database column to `LinkText` in all relevant tables
$linkTable = DataObject::getSchema()->baseDataTable(Link::class);
DB::get_conn()->getSchemaManager()->renameField($linkTable, 'Title', 'LinkText');
```

Don't hardcode table names.

2024-02-08 00:58 UTC, ChloeSartorelli commented on src/Models/SiteTreeLink.php
> +            $linkTextField?->setDescription(
Use `setTitleTip` here to override the text from `Link`

2024-02-08 01:47 UTC, emteknetnz commented on src/Models/SiteTreeLink.php
> +            $linkTextField?->setDescription(
Updated

2024-02-08 01:50 UTC, emteknetnz commented on README.md
> +DB::get_conn()->getSchemaManager()->renameField('LinkField_Link', 'Title', 'LinkText');
Updated

2024-02-08 01:50 UTC, emteknetnz commented on README.md
> +
Updated

2024-02-08 01:51 UTC, emteknetnz commented on README.md
> +You can manually rename this column in your database with the following:
Updated

2024-02-08 01:52 UTC, emteknetnz commented on README.md
> +## Migration form LinkField v3 to v4
Updated

2024-02-08 01:52 UTC, emteknetnz commented on README.md
> +```
Updated

2024-02-08 02:08 UTC, GuySartorelli approved these changes
LGTM, works well locally.

2024-02-08 02:08 UTC, merged