ENH Better versioned history
silverstripe/silverstripe-linkfield pull request #209
Opened 2024-02-08 05:26 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/10

2024-02-12 06:11 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> -import { injectGraphql } from 'lib/Injector';
The is unrelated refactoring to remove an unused import

2024-02-12 06:11 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> -  onNonPublishedVersionedState,
The is unrelated refactoring to remove a non-existent prop

2024-02-12 06:12 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> -          actions.toasts.error(i18n._t('LinkField.FAILED_TO_LOAD_LINKS', 'Failed to load links'))
Need to not show a red toast here because this will pop up when viewing old versions of an owner where the link has been deleted.  I've changed this to show an inline message when the link fails to load.

2024-02-12 06:13 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  onChange: PropTypes.func,
This should never have been a required field as it only makes sense in an entwine context

2024-02-12 06:15 UTC, emteknetnz commented on client/src/containers/LinkModalContainer.js
> +    return;
This should is to fix a console error where the state hasn't yet been updated from the call the setLinkModal, meaning that the `<LinkModal>` jsx object doesn't yet exist at time of render. Setting the state via this hook will trigger a rerender in which time `<LinkModal>` will not exist

2024-02-12 06:19 UTC, emteknetnz commented on client/lang/en.js
> +    "LinkField.FAILED_TO_LOAD_LINKS": "Failed to load link(s)",
This is a minor improvement to the message as it's used for both LinkField and for MultiLinkField

2024-02-12 06:20 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +  onChange = () => {},
This is a default value that's being set now that it's no longer a required prop

2024-02-12 06:23 UTC, emteknetnz commented on client/src/components/LinkField/tests/LinkField-test.js
> +test('LinkField will render link-picker if ownerID is not 0 and isMulti and has finished loading', async () => {
This jest test was technically wrong before - it shouldn't render a `.link-picker` element if it's non-isMulti and ownerID is not 0 - it should only render that if it's isMulti

2024-02-12 22:08 UTC, GuySartorelli requested changes
Still need to fulfil this acceptance critera (or deem it too hard for this card and open a separate card for them):
> Archived Admin uses the same behaviour as Versionned Admin when displaying link.

If I click on an archived page from archive admin, I see:
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/0c9f8fd0-1622-420e-9bfc-e1adfd2700fa)

Note that there was a link in both the "Has one link" and "Has many links one" field, but not the "Has many links two" field.

> LinkField on versioned history view correctly identify if a Link was attached to the page, but the Link was deleted.

This doesn't seem to work.
1. Create a link on a page
1. Publish the page
1. Archive the link
1. Make a change to the page and publish it again
1. View the version of the page which did have the link

For me it shows "Failed to load link(s)"

## Issue with archived history
When I archive a page (which has links on it), then restore the page from archived, then in the history tab I try to view the archive version, I get an infinite loading component.

2024-02-13 03:22 UTC, emteknetnz commented
> Archived Admin uses the same behaviour as Versionned Admin when displaying link.

ArchivedAdmin support adds a level of complexity over the regular history viewer that I don't think is worth it. We need to support multiple permutations of owner and links archived and not-archived. The LinkFieldController which handles all the data isn't aware of this. We also need to add support for knowing if we're even in an archived admin which is very messy because of the special treatment given to SiteTree vs other dataobjects.  

> LinkField on versioned history view correctly identify if a Link was attached to the page, but the Link was deleted.

This relates to the point above.  Because the link was deleted then when attempting to fetch the link via LinkFieldController it will return a 404.  We could change the message from "Failed to load link(s)" to "Link was deleted" ... but then again that's an assumption because it may be 404'ing for a different reason. I'd say it's such a minor point we should just leave as is.

> Issue with archived history

I was unable to replicate this issue

2024-02-13 20:53 UTC, GuySartorelli requested changes
LGTM, definitely an improvement over how it was before. Just a bit of tidy up.

2024-02-13 20:53 UTC, GuySartorelli commented on src/Form/LinkField.php
> +use SilverStripe\VersionedAdmin\Controllers\HistoryViewerController;
Adding this but it's not used?

2024-02-13 20:53 UTC, GuySartorelli commented on src/Form/MultiLinkField.php
> +    }
You have this in the abstract field, I assume you just forgot to remove from here?

2024-02-13 23:22 UTC, emteknetnz commented on src/Form/LinkField.php
> +use SilverStripe\VersionedAdmin\Controllers\HistoryViewerController;
Updated

2024-02-13 23:22 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +    }
Updated

2024-02-14 00:27 UTC, GuySartorelli commented on src/Form/MultiLinkField.php
> +use SilverStripe\VersionedAdmin\Controllers\HistoryViewerController;
```suggestion
```

2024-02-14 01:15 UTC, emteknetnz commented on src/Form/MultiLinkField.php
> +use SilverStripe\VersionedAdmin\Controllers\HistoryViewerController;
Updated

2024-02-14 20:45 UTC, GuySartorelli approved these changes
LGTM

2024-02-14 20:45 UTC, merged