FIX Archive record from live table on delete
silverstripe/silverstripe-linkfield pull request #214
Opened 2024-02-08 23:14 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/213

2024-02-08 23:16 UTC, emteknetnz commented on tests/php/Controllers/LinkFieldControllerTest.php
> -        $this->assertTrue(true);
This is unrelated refactoring to remove a pointless assertion

2024-02-08 23:18 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +                    $liveOwner->write();
I'm not sure if we should use write() here, or should just do something closer to raw sql that bypasses the ORM

2024-02-12 01:48 UTC, GuySartorelli requested changes

2024-02-12 01:48 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +            }
This incorrectly published changes which are in draft.
To reproduce:
1. Create a link
2. Publish the page
3. Make some content change on the page and save (but don't publish)
4. Archive the link

Reloading the page will show a published state for the page (i.e. publish button is not green).
Visiting the history will show the published state has the draft changes in it.
HOWEVER! Viewing the page in the front-end shows the old published content (not the draft content that got sort-of-maybe-published?)

Not sure if that's a bug with versioned or if this is just being done wrong or what, but something's not right.

2024-02-12 02:59 UTC, emteknetnz commented on src/Controllers/LinkFieldController.php
> +            }
Updated to use a SQLUpdate instead

2024-02-12 20:50 UTC, GuySartorelli requested changes

2024-02-12 20:50 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +                    ->execute();
This feels a bit hacky.
It's also not consistent with what happens when you archive related records in other situations. I don't think we should be doing this part.

The ORM already knows how to handle the scenario where a related record doesn't exist anymore. We don't need to try to handle that here.

If the old ID is causing errors in the UI, we need to instead swallow those errors (an outdated ID is fine, we just treat is as though the ID wasn't there in literally every other scenario in the CMS)

2024-02-12 20:50 UTC, GuySartorelli commented on src/Controllers/LinkFieldController.php
> +                    ->execute();
Should have realised this last time, sorry about that.

2024-02-13 00:35 UTC, GuySartorelli approved these changes
Looks great, works well locally.

There's some bad toasts when looking in the history tab, but that can be handled in https://github.com/silverstripe/silverstripe-linkfield/issues/10

2024-02-13 00:35 UTC, merged