ENH LinkField Jest tests
silverstripe/silverstripe-linkfield pull request #217
Opened 2024-02-13 00:22 UTC by sabina-talipova

## Description

## Parent issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/197

2024-02-13 20:51 UTC, emteknetnz requested changes

2024-02-13 20:51 UTC, emteknetnz commented on client/src/components/LinkField/tests/LinkField-test.js
> +describe('Render existing links', () => {
Don't use describe(), it's unnecessary.  Just use flat test().  When we did the large refactor on jest tests we went with the principles in this article - https://kentcdodds.com/blog/avoid-nesting-when-youre-testing which last linked from the react testing library docs

Remove describe() throughout this PR

2024-02-13 20:51 UTC, emteknetnz commented on client/src/components/LinkField/tests/LinkField-test.js
> +    await act(async () => {
Instead of using `act()`, use `await screen.findByText('Page title');`. You may need to import screen from react-testing-library. Update all references to act() in the PR

If there' no text to find try one of the other screen find* methods - https://testing-library.com/docs/queries/about/

If nothing there will work then just use act()

2024-02-13 22:06 UTC, sabina-talipova commented on client/src/components/LinkField/tests/LinkField-test.js
> +describe('Render existing links', () => {
Updated

2024-02-13 22:24 UTC, sabina-talipova commented on client/src/components/LinkField/tests/LinkField-test.js
> +    await act(async () => {
Updated

2024-02-13 23:17 UTC, emteknetnz requested changes

2024-02-13 23:17 UTC, emteknetnz commented on client/src/components/LinkPicker/tests/LinkPickerMenu-test.js
> +  await act(async () => {
Can this be converted to use await screen.findByText() ?

2024-02-13 23:17 UTC, emteknetnz commented on client/src/components/LinkPicker/tests/LinkPickerMenu-test.js
> +  await act(async () => {
Can this be converted to use await screen.findByText() ?

2024-02-13 23:17 UTC, emteknetnz commented on client/src/components/LinkField/tests/LinkField-test.js
> +import { render, screen, act } from '@testing-library/react';
```suggestion
import { render, screen } from '@testing-library/react';
```

2024-02-13 23:17 UTC, emteknetnz commented on client/src/components/LinkPicker/tests/LinkPickerMenu-test.js
> +import { render, fireEvent, act } from '@testing-library/react';
```suggestion
import { render, fireEvent, screen } from '@testing-library/react';
```
Assuming that act() can be replace with screen.findByText()

2024-02-13 23:34 UTC, sabina-talipova commented on client/src/components/LinkField/tests/LinkField-test.js
> +import { render, screen, act } from '@testing-library/react';
We use `act` [here](https://github.com/silverstripe/silverstripe-linkfield/blob/78aa111e4f0989f00488e536e56926a5fb273c8a/client/src/components/LinkField/tests/LinkField-test.js#L190-L193). 
Comment says `// Short wait - we can't use screen.find* because we're waiting for something to be removed, not added to the DOM`. If we replace `act` with `findText` test is failed.

2024-02-14 00:13 UTC, emteknetnz requested changes
Change commit and PR title prefix from ENH to MNT

2024-02-14 00:33 UTC, sabina-talipova commented on client/src/components/LinkPicker/tests/LinkPickerMenu-test.js
> +  await act(async () => {
Updated

2024-02-14 00:33 UTC, sabina-talipova commented on client/src/components/LinkPicker/tests/LinkPickerMenu-test.js
> +  await act(async () => {
Updated

2024-02-14 00:34 UTC, sabina-talipova commented on client/src/components/LinkPicker/tests/LinkPickerMenu-test.js
> +import { render, fireEvent, act } from '@testing-library/react';
Updated

2024-02-14 01:14 UTC, emteknetnz requested changes
We don't need waitFor() everywhere :-) Please only add it where it's actually required.

2024-02-14 01:22 UTC, sabina-talipova commented
Updated

2024-02-14 01:56 UTC, emteknetnz approved these changes

2024-02-14 01:56 UTC, merged