NEW Globally disallow link types
silverstripe/silverstripe-linkfield pull request #219
Opened 2024-02-13 05:34 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/212

2024-02-13 06:06 UTC, emteknetnz commented on src/Form/AbstractLinkField.php
> +        $allowedTypes = $this->generateAllowedTypes();
This is unrelated refactoring to remove the confusing `$typeDefinitions` variable

2024-02-13 06:09 UTC, emteknetnz commented on src/Models/Link.php
> -    private function getLinkTypes(): array
This is method is unused

2024-02-13 06:15 UTC, emteknetnz commented on tests/php/Form/AbstractLinkFieldTest.php
> +class AbstractLinkFieldTest extends SapphireTest
I renamed this file and associated fixture files from `LinkFieldTest`

2024-02-13 06:15 UTC, emteknetnz commented on tests/php/Form/AbstractLinkFieldTest.php
> +
Below this line is new test code, above this line was existing code

2024-02-13 21:57 UTC, sabina-talipova requested changes
Looks good. Tested locally. Just tiny enhancement.

2024-02-13 21:57 UTC, sabina-talipova commented on README.md
> +If you wish to globally disable one of the default `Link` subclasses for all `LinkField` instances, then this can be done using the following YAML configuration, using the FQCN of the relevant defaul
```suggestion
If you wish to globally disable one of the default `Link` subclasses for all `LinkField` instances, then this can be done using the following YAML configuration, using the FQCN (Fully-Qualified Class Name) of the relevant default `Link` subclass you wish to disable:
```
It would be nice to clarify, since we have not used this abbreviation before in the text.

2024-02-13 23:20 UTC, emteknetnz commented on README.md
> +If you wish to globally disable one of the default `Link` subclasses for all `LinkField` instances, then this can be done using the following YAML configuration, using the FQCN of the relevant defaul
Updated

2024-02-14 01:37 UTC, sabina-talipova approved these changes
LGTM. Locally tested.

2024-02-14 01:37 UTC, merged