DOC Provide proper developer documentation
silverstripe/silverstripe-linkfield pull request #224
Opened 2024-02-15 03:21 UTC by GuySartorelli

## Description

- Moves readme docs into the docs/en/ dir where it belongs
- Adds missing docs

Note that this PR assumes the primary place for actually viewing the docs will be from the developer docs, but makes a best-effort approach to making them usable from GitHub as well.
To this end, API links use the developer docs `api:` style, but docs to other developer docs sections use absolute URLs.

## Issues

- https://github.com/silverstripe/silverstripe-linkfield/issues/27

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

2024-02-15 03:22 UTC, GuySartorelli commented on docs/en/08_gotchas.md
This file and the migrating dir intentionally have late-numbered prefixes. This allows future pages to be added before them without having to rename them.

2024-02-15 03:23 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
This and all other migrating/upgrading docs are unaltered, since updating these guides is going to be handled in a separate card.

2024-02-15 21:33 UTC, emteknetnz requested changes

2024-02-15 21:33 UTC, emteknetnz commented on docs/en/01_basic_usage.md
> +    ];
I'm confused - how exactly doing suffixing `.Owner` make a difference here?

I thought all the OwnerRelation stuff was an alternative and better way to handle the dot suffixing

2024-02-15 21:33 UTC, emteknetnz commented on docs/en/03_templates.md
> +<% end_if %>
```suggestion
<% if $HasManyLinks %>
    <ul>
        <% loop $HasManyLinks %>
            <li>$Me</li>
        <% end_loop %>
    </ul>
<% end_if %>
```

2024-02-15 21:33 UTC, emteknetnz commented on docs/en/03_templates.md
> +</ul>
```suggestion
<ul>
    <% loop $HasManyLinks %>
        <li>
            <a href="$URL" <% if $OpenInNew %>target="_blank" rel="noopener noreferrer"<% end_if %>>$Title</a>
        </li>
    <% end_loop %>
</ul>
```

2024-02-15 21:34 UTC, GuySartorelli commented on docs/en/01_basic_usage.md
> +    ];
No, the point was never to remove dot notation. The point was that two `has_many` relations can share a single `has_one` relation to store the data in.

Dot notation is still required so the ORM knows which `has_one` relation stores the data.

2024-02-16 01:26 UTC, GuySartorelli commented on docs/en/03_templates.md
> +<% end_if %>
Done

2024-02-16 01:26 UTC, GuySartorelli commented on docs/en/03_templates.md
> +</ul>
Done

2024-02-18 20:25 UTC, emteknetnz approved these changes

2024-02-18 20:25 UTC, merged