ENH Additional behat tests
silverstripe/silverstripe-linkfield pull request #226
Opened 2024-02-15 21:39 UTC by sabina-talipova

## Description

## Manual testing steps

## Issues

- #

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-02-15 22:44 UTC, emteknetnz requested changes

2024-02-15 22:44 UTC, emteknetnz commented on tests/behat/src/FeatureContext.php
> +    public function iTypeInField(string $data)
```suggestion
    public function iTypeInTheField(string $data)
```
Method name should match Given regex

This method should be put into behat-extension BasicContext

2024-02-15 22:44 UTC, emteknetnz commented on tests/behat/src/FeatureContext.php
> +    public function isCurrentActiveElement(string $selector)
```suggestion
    /**
     * @Given /^the active element should be "([^"]+)"$/
     */
    public function theActiveElementShouldBe(string $selector)
```
Updated both Given regex and the method name to be a little more standard

You'll need to update references in feature files too

This method should be put into behat-extension BasicContext

2024-02-15 22:44 UTC, emteknetnz commented on tests/behat/src/FeatureContext.php
> +    public function theHasALinkInLinkField(string $selector)
```suggestion
    public function iFocusOnTheElement(string $selector)
```

Method name should match Given regex

This method should be put into behat-extension BasicContext

2024-02-15 22:44 UTC, emteknetnz commented on tests/behat/src/FeatureContext.php
> +class FeatureContext extends SilverStripeContext
Move the methods in this class to behat-extension BasicContext and delete this file

2024-02-15 22:44 UTC, emteknetnz commented on behat.yml
> -        - SilverStripe\Framework\Tests\Behaviour\FeatureContext
Just leave this in

2024-02-15 22:44 UTC, emteknetnz commented on behat.yml
> +        - SilverStripe\LinkField\Tests\Behat\FeatureContext
```suggestion
```

2024-02-15 22:44 UTC, emteknetnz commented on behat.yml
>          - SilverStripe\BehatExtension\Context\FixtureContext:
Could you change the FixtureContext bit to have the **exact** same indentation as [this](https://github.com/silverstripe/silverstripe-admin/blob/2/behat.yml#L21) - it's very weird and it's like that for some reason that I forget, though I do know it definately works

2024-02-15 22:44 UTC, emteknetnz commented on tests/behat/features/accessability-linkfield.feature
> +      And I go to "/dev/build?flush"
```suggestion
    Given I add an extension "SilverStripe\FrameworkTest\LinkField\Extensions\LinkPageExtension" to the "Page" class
    And I go to "/dev/build?flush"
```
Use the same indentation for all the statements within Background/Scenario - that's generally what's done in other feature files in the code base

The this for the entire file

2024-02-15 22:44 UTC, emteknetnz commented on tests/behat/features/accessability-linkfield.feature
> +      # Test accessability of the LinkField drag and drop
```suggestion
      # Test accessibility of the LinkField keyboard sorting
```
Drag and drop is using the mouse :-)

2024-02-15 22:44 UTC, emteknetnz commented on tests/behat/features/accessability-linkfield.feature
> +      # Test accessability of the modal form
```suggestion
      # Test accessibility of the modal form
```

2024-02-16 00:31 UTC, sabina-talipova commented on tests/behat/src/FeatureContext.php
> +    public function iTypeInField(string $data)
Updated. Moved in `behat-extension`. [See](https://github.com/silverstripe/silverstripe-behat-extension/pull/263/files)

2024-02-16 00:31 UTC, sabina-talipova commented on tests/behat/src/FeatureContext.php
> +    public function isCurrentActiveElement(string $selector)
Updated. Moved in `behat-extension`. [See](https://github.com/silverstripe/silverstripe-behat-extension/pull/263/files)

2024-02-16 00:31 UTC, sabina-talipova commented on tests/behat/src/FeatureContext.php
> +    public function theHasALinkInLinkField(string $selector)
Updated. Moved in `behat-extension`. [See](https://github.com/silverstripe/silverstripe-behat-extension/pull/263/files)

2024-02-16 00:31 UTC, sabina-talipova commented on tests/behat/src/FeatureContext.php
> +class FeatureContext extends SilverStripeContext
Updated.

2024-02-16 00:32 UTC, sabina-talipova commented on behat.yml
> -        - SilverStripe\Framework\Tests\Behaviour\FeatureContext
Updated.

2024-02-16 00:32 UTC, sabina-talipova commented on behat.yml
> +        - SilverStripe\LinkField\Tests\Behat\FeatureContext
Updated

2024-02-16 00:33 UTC, sabina-talipova commented on behat.yml
>          - SilverStripe\BehatExtension\Context\FixtureContext:
Updated.

2024-02-16 00:33 UTC, sabina-talipova commented on tests/behat/features/accessability-linkfield.feature
> +      And I go to "/dev/build?flush"
Updated.

2024-02-16 00:33 UTC, sabina-talipova commented on tests/behat/features/accessability-linkfield.feature
> +      # Test accessability of the LinkField drag and drop
Updated

2024-02-16 00:33 UTC, sabina-talipova commented on tests/behat/features/accessability-linkfield.feature
> +      # Test accessability of the modal form
Updated.

2024-02-16 01:46 UTC, sabina-talipova commented
Test passed: https://github.com/sabina-talipova/recipe-kitchen-sink/actions/runs/7924765855/job/21636895068

2024-02-18 20:30 UTC, emteknetnz approved these changes
Approved, will merge when https://github.com/silverstripe/silverstripe-behat-extension/pull/263 is merged and tagged

2024-02-18 22:56 UTC, emteknetnz commented
Have merged and released behat-extenstion pr, re-running behat tests on this pr now

2024-02-18 23:05 UTC, merged