DOC Link field User manual
silverstripe/silverstripe-linkfield pull request #234
Opened 2024-02-20 01:07 UTC by sabina-talipova

## Description

## Manual testing steps

## Issues

- #

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-02-21 20:53 UTC, GuySartorelli requested changes

2024-02-21 20:53 UTC, GuySartorelli commented on docs/en/userguide/01_about_link_field.md
This page needs to be called `index.md` - see https://github.com/silverstripe/silverstripe-blog/blob/4/docs/en/userguide/index.md as an example.

2024-02-21 20:53 UTC, GuySartorelli commented on docs/en/userguide/01_User_manual/01_links_types.md
Remove the `01_User_manual` directory and just have these right next to `index.md`

2024-02-21 20:53 UTC, GuySartorelli commented on docs/en/userguide/01_about_link_field.md
> +[CHILDREN Folder=01_User_manual]
```suggestion
[CHILDREN includeFolders]
```
This will link to all sibling pages, and the `index.md` for and subfolders (which there won't be any initially but could be in the future)

2024-02-21 22:59 UTC, sabina-talipova commented on docs/en/userguide/01_about_link_field.md
Updated

2024-02-21 22:59 UTC, sabina-talipova commented on docs/en/userguide/01_User_manual/01_links_types.md
Updated

2024-02-21 22:59 UTC, sabina-talipova commented on docs/en/userguide/01_about_link_field.md
> +[CHILDREN Folder=01_User_manual]
Updated

2024-02-21 23:22 UTC, sabina-talipova commented
Failed CI step is unrelated to this PR

2024-02-22 03:58 UTC, GuySartorelli requested changes

2024-02-22 03:58 UTC, ChloeSartorelli commented on docs/en/userguide/index.md
> +> Make sure that your SilverStripe CMS installation has the [LinkField](https://addons.silverstripe.org/add-ons/silverstripe/linkfield/) module installed.
addons doesn't exist anymore. Link to packagist.

2024-02-22 03:58 UTC, ChloeSartorelli commented on docs/en/userguide/index.md
> +# Creating links in the CMS with LinkField module
```suggestion
# Managing links in the CMS
```

2024-02-22 03:58 UTC, ChloeSartorelli commented on docs/en/userguide/index.md
> +title: Creating links in the CMS
```suggestion
title: Managing links in the CMS
```

2024-02-22 03:58 UTC, ChloeSartorelli commented on docs/en/userguide/index.md
> +summary: How to use the Link Field module to create links in the CMS.
```suggestion
summary: How to use the Link Field module to manage links in the CMS.
```

2024-02-22 03:58 UTC, ChloeSartorelli commented on docs/en/userguide/01_links_types.md
> +# Basic types of links
```suggestion
# Link types
```
Having a "basic types" suggests there's also an "advanced types", which there isn't.
You'll need to change anywhere else that refers to this as well.

2024-02-22 03:58 UTC, ChloeSartorelli commented on docs/en/userguide/index.md
> +In this section, we will delve into the process of creating links using the versatile LinkField module. This module offers the flexibility to generate links of diverse types, such as "Page on this si
```suggestion
In this section, we will show the process of managing links using the LinkField module. This module provides a clean interface for creating and managing links in the CMS.
```
We're not trying to sell the module here, and we want people to be able to quickly find the information they need. I've reduced this to just a really basic explanation of what the module does, because by the time someone's reading this their digital agency has probably already installed the module for them and they're just looking for information about how to use the thing.

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/index.md
> +There are two primary types of Link field functionalities: one for crafting a single link and another for managing multiple links of similar or varying types. Each type of Link field will be comprehe
```suggestion
There are two main types of link field: one for managing a single link and another for managing multiple links. Each type of Link field will be discussed in the ["Essential functionalities associated with the Link field"](01_User_manual/02_work_with_link_field.md) section.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/index.md
> +The module streamlines the link creation process by providing a user-friendly form that includes all essential fields necessary for link generation. Additionally, it enables sorting capabilities and
```suggestion
The module streamlines the link creation process by providing a user-friendly form that includes all essential fields necessary for link management.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +title: Essential functionalities associated with the link field
```suggestion
title: Using the link field
```
It's really about "how do I use this" rather than "what can this thing do?"
Please also change the title below and any references to this page.

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +summary: How to work with the Link field and Multi Link field in the CMS.
```suggestion
summary: How to work with the link field and multi-ink field in the CMS.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +Previous sections provided fundamental knowledge for creating links. In contrast, this section will delve into the specifics of Likfeld, offering insights into its functionalities like sorting and de
```suggestion
Previous sections provided fundamental knowledge for creating links. In contrast, this section will delve into the specifics of link field, offering insights into its functionalities like sorting and deletion, essential for effective link management.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +The LinkField module offers two primary types of fields: one for creating a single link and the other for generating multiple links. While there are some differences in how these fields operate, let'
```suggestion
The LinkField module offers two primary types of fields: one for managing a single link and the other for managing multiple links. While there are some differences in how these fields operate, let's first outline the key aspects that are common to both types of fields.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +## Single Link field
```suggestion
## Single link field
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +## Multi Link field
```suggestion
## Multi link field
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +The Single LinkField module is designed for managing individual links. To create a new link, users can click on the "Add link" button and select the desired link type from the dropdown menu. This act
```suggestion
The single link field is designed for managing individual links. To create a new link, users can click on the "Add link" button and select the desired link type from the dropdown menu. This action opens a modal window where users can input the necessary information for creating the link. For detailed information about the default link types, please refer to the ["Link Types"](./01_links_types.md) section.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +To view more detailed information or make changes to an existing link, users need to click the Link field button again. This action opens the modal window where adjustments can be made. If no changes
```suggestion
To view more detailed information or make changes to an existing link, click anywhere on the link details. This opens the modal window where adjustments can be made. If no changes are required, users can simply close the modal window.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +The MultiLink Field functions similarly to the Single Link Field but offers notable advantages. Users can create various links and easily manage them within a single field. Additionally, they can con
```suggestion
The multi link field functions similarly to the single link field, but with multiple links. Users can create various links and easily manage them within a single field. Additionally, they can sort the links as needed. The order of links in the field will be the order they're displayed on the front end.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +## Disabled or Read only links
```suggestion
## Disabled or read-only links
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +## Delete Link
```suggestion
## Delete links
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +To view more detailed information or make changes to an existing link, users need to click the Link field button again. This action opens the modal window where adjustments can be made. If no changes
This paragraph should probably go after "let's first outline the key aspects that are common to both types of fields"

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +Once a new link is created, basic information about it will be displayed in the Link field.
This paragraph should probably go after "let's first outline the key aspects that are common to both types of fields"

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +> Once created, the user is unable to modify the link type. To establish a different type of link, the user must initiate a new creation process from the beginning.
```suggestion
> Once created, the user is unable to modify the link type. To change a link to a different type, the user must delete the existing link and create a new one.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +> Any information entered is automatically saved upon the creation of a new link or when updates are made to the link data by the user.
```suggestion
Any information entered is automatically saved upon the creation of a new link or when updates are made to the link data by the user.
```
I don't think this needs a big callout - it's just more regular information about links.

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +> Any information entered is automatically saved upon the creation of a new link or when updates are made to the link data by the user.
Add something after this about needing to publish the page to publish links.

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +The user has the ability to remove an existing link by clicking on the "Archive" button. Upon doing so, the link will be deleted, and the change will be automatically saved.
```suggestion
You can remove an existing link by clicking on the "Archive" button.
```
Probably most of the places where these docs say "the user" should be swapped to "you", but I'm not too worried about the ones I haven't specifically called out.

Removed the bit about the link being deleted - it's not deleted, just archived. So that's covered by saying "the archive button".

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +At times, it's necessary to limit certain users' access to creating, editing or removing links. Consequently, editing capabilities for these links will be disabled, rendering them available to users
```suggestion
If a user doesn't have the right permissions for editing a link (usually because they can't edit the page the link is on), editing capabilities for these links will be disabled. This is usually referred to as read-only mode. In read-only mode, links cannot be edited, archived, or reordered - but all of the information about them can be viewed.
```

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/02_work_with_link_field.md
> +## Disabled or Read only links
This section should probably go after "let's first outline the key aspects that are common to both types of fields" (before the single field stuff)

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/01_links_types.md
> +- [Validation error](#validation-error)
```suggestion
```
We don't tend to add lists of content like this. Some old pages do, but we don't do it with new pages.
Eventually I'd like for us to generate a table of contents automatically (pending whatever happens with dotorg)

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/01_links_types.md
> +![A screenshot of the form "Link to a file"](./_images/validation_error.png)
This should be moved to `02_work_with_link_field.md` - it's more about working with links, rather than about the link types.

2024-02-22 03:58 UTC, GuySartorelli commented on docs/en/userguide/01_links_types.md
> +As you may have observed, each link type includes a "Link Text" field. This field is optional. If left empty during link creation, the default title associated with the link type will be used when th
This should be moved to `02_work_with_link_field.md` - it's more about working with links, rather than about the link types.

2024-02-22 19:10 UTC, sabina-talipova commented on docs/en/userguide/index.md
> +> Make sure that your SilverStripe CMS installation has the [LinkField](https://addons.silverstripe.org/add-ons/silverstripe/linkfield/) module installed.
Updated

2024-02-22 19:11 UTC, sabina-talipova commented on docs/en/userguide/index.md
> +# Creating links in the CMS with LinkField module
Updated

2024-02-22 19:11 UTC, sabina-talipova commented on docs/en/userguide/index.md
> +title: Creating links in the CMS
Updated

2024-02-22 19:11 UTC, sabina-talipova commented on docs/en/userguide/index.md
> +summary: How to use the Link Field module to create links in the CMS.
Updated

2024-02-22 19:12 UTC, sabina-talipova commented on docs/en/userguide/01_links_types.md
> +# Basic types of links
Updated

2024-02-22 19:13 UTC, sabina-talipova commented on docs/en/userguide/index.md
> +In this section, we will delve into the process of creating links using the versatile LinkField module. This module offers the flexibility to generate links of diverse types, such as "Page on this si
Updated

2024-02-22 19:14 UTC, sabina-talipova commented on docs/en/userguide/index.md
> +There are two primary types of Link field functionalities: one for crafting a single link and another for managing multiple links of similar or varying types. Each type of Link field will be comprehe
Updated

2024-02-22 19:14 UTC, sabina-talipova commented on docs/en/userguide/index.md
> +The module streamlines the link creation process by providing a user-friendly form that includes all essential fields necessary for link generation. Additionally, it enables sorting capabilities and
Updated

2024-02-22 19:15 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +title: Essential functionalities associated with the link field
Updated

2024-02-22 19:16 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +summary: How to work with the Link field and Multi Link field in the CMS.
Updated

2024-02-22 19:16 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +Previous sections provided fundamental knowledge for creating links. In contrast, this section will delve into the specifics of Likfeld, offering insights into its functionalities like sorting and de
Updated

2024-02-22 19:17 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +The LinkField module offers two primary types of fields: one for creating a single link and the other for generating multiple links. While there are some differences in how these fields operate, let'
Updated

2024-02-22 19:17 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +## Single Link field
Updated

2024-02-22 19:17 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +## Multi Link field
Updated

2024-02-22 19:18 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +The Single LinkField module is designed for managing individual links. To create a new link, users can click on the "Add link" button and select the desired link type from the dropdown menu. This act
Updated

2024-02-22 19:18 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +To view more detailed information or make changes to an existing link, users need to click the Link field button again. This action opens the modal window where adjustments can be made. If no changes
Updated

2024-02-22 19:19 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +The MultiLink Field functions similarly to the Single Link Field but offers notable advantages. Users can create various links and easily manage them within a single field. Additionally, they can con
Updated

2024-02-22 19:20 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +## Disabled or Read only links
Updated

2024-02-22 19:20 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +## Delete Link
Updated

2024-02-22 19:22 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +To view more detailed information or make changes to an existing link, users need to click the Link field button again. This action opens the modal window where adjustments can be made. If no changes
Updated

2024-02-22 19:23 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +Once a new link is created, basic information about it will be displayed in the Link field.
Updated

2024-02-22 19:23 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +> Once created, the user is unable to modify the link type. To establish a different type of link, the user must initiate a new creation process from the beginning.
Updated

2024-02-22 19:24 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +> Any information entered is automatically saved upon the creation of a new link or when updates are made to the link data by the user.
Updated

2024-02-22 19:25 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +The user has the ability to remove an existing link by clicking on the "Archive" button. Upon doing so, the link will be deleted, and the change will be automatically saved.
Updated

2024-02-22 19:26 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +At times, it's necessary to limit certain users' access to creating, editing or removing links. Consequently, editing capabilities for these links will be disabled, rendering them available to users
Updated

2024-02-22 19:27 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +## Disabled or Read only links
Updated

2024-02-22 19:27 UTC, sabina-talipova commented on docs/en/userguide/01_links_types.md
> +- [Validation error](#validation-error)
Updated

2024-02-22 19:29 UTC, sabina-talipova commented on docs/en/userguide/01_links_types.md
> +![A screenshot of the form "Link to a file"](./_images/validation_error.png)
Updated

2024-02-22 19:29 UTC, sabina-talipova commented on docs/en/userguide/01_links_types.md
> +As you may have observed, each link type includes a "Link Text" field. This field is optional. If left empty during link creation, the default title associated with the link type will be used when th
Updated

2024-02-22 20:03 UTC, sabina-talipova commented on docs/en/userguide/02_work_with_link_field.md
> +> Any information entered is automatically saved upon the creation of a new link or when updates are made to the link data by the user.
Updated

2024-02-22 20:43 UTC, sabina-talipova commented on docs/en/userguide/01_links_types.md
> +As you may have observed, each link type includes a "Link Text" field. This field is optional. If left empty during link creation, the default title associated with the link type will be used when th
I left it as is. Since in my opinion logically "Title" is related to `Link` not `LinkField`.

2024-02-22 20:45 UTC, sabina-talipova commented on docs/en/userguide/01_links_types.md
> +![A screenshot of the form "Link to a file"](./_images/validation_error.png)
I left it as is. Validation error also part of Link, but not `LinkField`

2024-02-22 20:48 UTC, GuySartorelli commented on docs/en/userguide/01_links_types.md
> +As you may have observed, each link type includes a "Link Text" field. This field is optional. If left empty during link creation, the default title associated with the link type will be used when th
From the titles of the pages, I gather the content is about "types of links" and "how to use the functionality this module provides" respectively, not "link model" and "linkfield model" which are technical implementation details most users won't be aware of.

2024-02-22 21:37 UTC, GuySartorelli commented on docs/en/userguide/01_links_types.md
> +As you may have observed, each link type includes a "Link Text" field. This field is optional. If left empty during link creation, the default title associated with the link type will be used when th
Doesn't matter enough for it to go through another round of peer review though.

2024-02-22 21:37 UTC, GuySartorelli approved these changes
LGTM

2024-02-22 21:37 UTC, merged