ENH Pre-render the LinkField in entwine
silverstripe/silverstripe-linkfield pull request #241
Opened 2024-03-01 08:52 UTC by maxime-rainville

This PR is making the pre-rendered UI more pleasing by pre-rendering somethings.

2024-03-01 09:34 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
>          continue;
By not skipping the link entries for which we don't have data yet, we'll render a list of placeholder LinkPickerTitle. This will avoids having a big jump on the page once the data finally gets back to us.

2024-03-01 09:34 UTC, maxime-rainville commented on client/src/components/LinkField/LinkField.js
> -  const renderPicker = !loadingError && !inHistoryViewer && !saveRecordFirst && (isMulti || Object.keys(data).length === 0);
This was needed because a disabled LinkField with pe-existing data would briefly render a picker and a place holder link.

With this change, it only renders the picker.

2024-03-01 09:34 UTC, maxime-rainville commented on src/Form/MultiLinkField.php
> +        return ArrayList::create($this->dataValue());
This wraps the IDs in an ArrayList so the SS template can loop over them.

2024-03-01 09:34 UTC, maxime-rainville commented on templates/SilverStripe/LinkField/Form/LinkField_Spinner.ss
Maybe this should be in Admin instead. [CMSLoadingScreen.ss](https://github.com/silverstripe/silverstripe-admin/blob/2/templates/SilverStripe/Admin/Includes/CMSLoadingScreen.ss) contains the relevant markup, but it also contains other things that get in the way.

2024-03-02 03:09 UTC, GuySartorelli requested changes
Are the new templates always used for rendering those elements, or does react render them separately?
If the latter, this gives the false impression that you can change how the linkfield gets rendered by changing templates.

2024-03-03 20:51 UTC, maxime-rainville commented
Enwtine only.

Most of these templates were pre-existing, so you could easily have been confused into thinking that you could override them. If you did try to customise them, you would quickly notice that your changes a being nuked once React boots.

I can rename the templates and/or add extra comments to make it clear this is an Entwine only construct.

2024-03-03 22:10 UTC, GuySartorelli commented
> Enwtine only.

Linkfield is a react component, so that doesn't really make any sense

> Most of these templates were pre-existing, so you could easily have been confused into thinking that you could override them. If you did try to customise them, you would quickly notice that your changes a being nuked once React boots.

The existing ones **CAN** be overridden, but notably are used to bootstrap the react component.

The new templates mirror something that is rendered by react - so changing these templates will **only** change the display of a linkfield before any react is bootstrapped for the field if I'm not mistaken.

At the very very least these templates need comments at the top indicating that they are only for use in rendering the field before react has bootstrapped and will not affect the display of the rendered react component.

2024-03-03 22:24 UTC, maxime-rainville commented
Behat build is broken. I thought it was intermittent, but it seems to be a legit failure.

I'll add comments to the template while I'm at it.

2024-03-06 02:37 UTC, maxime-rainville commented on tests/behat/features/accessibility-linkfield.feature
> +    And I press the "Tab" key globally
I had to add an extra Tab here because for some reason the focus is not returned to the LinkField after the Modal is saved.

The expected course of action is:
- You close the Modal, the the LinkField has focus.
- The First Tab shift the focus to the Archive button
- The Second Tab shift the focus to the next LinkField.

With the current PR:
- You close the Modal, the the LinkField doesn't have focus.
- The First Tab shift the focus to the LinkField
- The Second Tab shift the focus to the Archive button
- The Third Tab shift the focus to the next LinkField.

After screaming at the thing for a couple hours, I concluded that the initial implementation doesn't really work most of the time any way: 
- Some fields won't return the focus to the right place.
- Some field will work on the first Modal edition, but not on the second.

I got a linkfield accessibility follow up card here: https://github.com/silverstripe/silverstripe-linkfield/issues/245

2024-03-06 20:45 UTC, emteknetnz requested changes
We shouldn't be adding templates to a react component

2024-03-06 20:45 UTC, emteknetnz commented on tests/behat/features/accessibility-linkfield.feature
> +    And I press the "Tab" key globally
> You close the Modal, the the LinkField doesn't have focus.

Sound like the PR has created a regression then? Before this PR `You close the Modal, the the LinkField has focus.` worked correctly with keyboard navigation (though not with mouse), though this behat test is using keyboard navigation so the fact you need to tab three times is wrong?

> Some fields won't return the focus to the right place.
> Some field will work on the first Modal edition, but not on the second.

Could you provide some details please

2024-03-06 20:45 UTC, emteknetnz commented on templates/SilverStripe/LinkField/Form/LinkField_Spinner.ss
> +  <div class="link-field__loading">
Why are we using templates here?  This won't work in an react context e.g. elemental

There's a spinner react component available, seems like that should be used instead

2024-03-06 20:45 UTC, emteknetnz commented on client/src/components/LinkField/tests/LinkField-test.js
> +    value: undefined
Why is this set to undefined instead of the default 123? A disabled LinkField could still have a value?

2024-03-07 01:09 UTC, maxime-rainville reviewed
I've addressed the feedback.

On the broader point of "adding templates to a react component", providing placeholder markup while waiting for some long running process to complete is a standard practice in most modern JS based application.

For example, here's what ZenHub does.
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/f9eb43d1-e56f-435c-80f0-7efd0080f7e0)

It provides a nicer UI for the user, avoid things jumping around on the page once the long process has completed and reassures the user that the site hasn't crash on them.

I appreciate we have not historically done this. Now is as good a time to start as any.

2024-03-07 01:09 UTC, maxime-rainville commented on templates/SilverStripe/LinkField/Form/LinkField_Spinner.ss
> +  <div class="link-field__loading">
The entire point of the PR is to render something while we wait for React to boot.

Elemental won't have that problem, because it's already powered by react.

2024-03-07 01:09 UTC, maxime-rainville commented on tests/behat/features/accessibility-linkfield.feature
> +    And I press the "Tab" key globally
Without this PR, the only time the focus works is:
- When creating a brand new link
- When exiting a modal to an empty link field

It does NOT work:
- When updating an existing Link
- When exiting the modal for a link that already exists
- When archiving a link

From where I stand, the focus is already busted anyway and needs to be redone. So I don't think we should hold this PR on this.

2024-03-07 01:09 UTC, maxime-rainville commented on client/src/components/LinkField/tests/LinkField-test.js
> +    value: undefined
The original version of the test was incorrect. A disabled LinkField with a value should not be rendering `Cannot create link` message. It should be rendering the Link in a disabled state.

I added a new test case. Now, we test:
- Disabled LinkField with link
- Disabled LinkField without link

I've removed the `doResolve` call from the "Disabled without" scenario because there's no actual AJAX call made in this instance

2024-03-07 01:09 UTC, maxime-rainville commented on client/src/components/LinkField/tests/LinkField-test.js
> +  expect(linkPicker[0]).toHaveAttribute('aria-disabled', 'false');
There's an `aria-disabled` attribute on the Disabled linkfield ... but its value is false. I'm not sure if that's actually what we want to do here.

I've added like this for now. We can revisit in the accessibility card.

2024-03-07 02:04 UTC, emteknetnz commented on client/src/components/LinkField/tests/LinkField-test.js
> +  expect(linkPicker[0]).toHaveAttribute('aria-disabled', 'false');
```suggestion
```
Adding it here make it look like this is the correct behaviour, even though we know it's wrong. If we're explicitly adding aria-disabled on the other card then we'll naturally add a unit test for it

2024-03-07 02:04 UTC, emteknetnz commented on tests/behat/features/accessibility-linkfield.feature
> +    And I press the "Tab" key globally
> When updating an existing Link
> When exiting the modal for a link that already exists

I have replicated locally, though it's a sporadic failure. Seems like a timing issue. 

> When archiving a link

This was never accounted for

2024-03-07 02:27 UTC, emteknetnz requested changes
There's little orange 'modified' badges showing before it's loaded as part of the 'loading animation' which should be there

This video showing me refreshing the page on my local

[linkfield-fout-after-2024-03-07_15.25.41.webm](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/de085926-a919-4857-9d83-490b4c56ec2a)


I can't help thinking we need to look at the spinner styling, the dark background on it make for a pretty jarring experience on my local where there's lots of "flashing" because the background is rendered for so little time. There already was some before this PR, though it's quite a lot worse afterwards

2024-03-07 03:24 UTC, GuySartorelli commented on templates/SilverStripe/LinkField/Form/LinkField_Spinner.ss
This template is missing the comment about how it's only for pre-react rendering, and will be discarded.

2024-03-07 03:46 UTC, maxime-rainville commented on templates/SilverStripe/LinkField/Form/LinkField_Spinner.ss
You're meant to be on leave, sir!

2024-03-09 10:43 UTC, maxime-rainville reviewed
Added the missing comment and cleaned the version state icon.

FYI this PR now depends on https://github.com/silverstripe/silverstripe-admin/pull/1705

2024-03-09 10:43 UTC, maxime-rainville commented on client/src/components/LinkField/tests/LinkField-test.js
> +  expect(linkPicker[0]).toHaveAttribute('aria-disabled', 'false');
Removed the test for false.

2024-03-09 10:43 UTC, maxime-rainville commented on client/src/constants/versionStates.js
> +const versionStates = {
Repeating the same strings over and over again seemed wrong and likely to lead to confusion. So I moved them to a constant.

2024-03-09 10:43 UTC, maxime-rainville commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  versionState: versionStates.unversioned,
This change addresses the problem where the place holder LinkPickerTitle would get a draft state icon.

2024-03-09 10:43 UTC, maxime-rainville commented on composer.json
> +        "silverstripe/admin": "^2.2"
We have a dependency on admin 2.2 because of the new spinner template.

2024-03-09 10:43 UTC, maxime-rainville commented on templates/SilverStripe/LinkField/Form/LinkField_Spinner.ss
Added the comments + moved the spinner to a dedicated template in admin so we don't need to repeat this over and over.

See https://github.com/silverstripe/silverstripe-admin/pull/1705

2024-03-10 22:20 UTC, emteknetnz commented on client/src/constants/versionStates.js
> +const versionStates = {
Could you please refrain from doing random refactoring half-way through a peer review. It adds unnecessary burden at the end of the person doing the peer review.

2024-03-10 22:25 UTC, emteknetnz approved these changes
Tested locally

2024-03-10 22:26 UTC, emteknetnz requested changes
Behat failures in CI

2024-03-12 05:31 UTC, maxime-rainville commented
Merging the admin PR fixed the behat build.

2024-03-12 20:45 UTC, emteknetnz approved these changes

2024-03-12 20:46 UTC, merged