NEW Add migration task from older versions of the module
silverstripe/silverstripe-linkfield pull request #244
Opened 2024-03-04 03:33 UTC by GuySartorelli

## Description

Provides a migration task and docs for upgrading from 2.x or 3.x to 4.x

## Manual testing steps

Docs TBD

## Issues

- https://github.com/silverstripe/silverstripe-linkfield/issues/228

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-03-05 02:03 UTC, GuySartorelli commented
Retargetted to `4.0` so it gets included in the initial stable release.

2024-03-12 23:28 UTC, GuySartorelli commented on src/Tasks/LinkFieldMigrationTask.php
> +    private function checkForBrokenLinks(): void
This method is surplus to requirements and was mostly done as a palette cleanser to keep me sane. If there is any doubt about the value of it or extensive changes are required, I'm happy to simply remove it.

2024-03-13 04:31 UTC, GuySartorelli commented on src/Tasks/LinkFieldMigrationTask.php
> +        // on an UPDATE, due to a missing feature in framework's ORM API.
I found a trick that lets me work around this - I can do a subselect within the update, and it lets me reference the table that the update is acting on.

I've decided that instead of refactoring this now to use that, I'll just submit this for review at this stage. I've taken long enough on the implementation already.

Reviewer, please decide between:
1. Optimising this now (will take ~1 day)
2. Creating a separate follow-up card to optimise this

It's the difference between making one query per relation, or one query per OWNER RECORD per relation. So it's a pretty significant difference and does need to be done at some stage.

2024-03-17 22:33 UTC, emteknetnz requested changes
Do a test I got this warning which is correct because I missed a step:

```
Migrating has_many relations.
has_one relation 'SilverStripe\LinkField\Models\Link.MyPage still exists. Cannot migrate has_many relation 'Page.MyPhoneLinks'.
```

However the rest of the script still processed and now my data is possibly is a weird state.  What should have happened is the script should have stopped immediately and told me to fix my issues.

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +    - If the `has_one` relation for the record which owns the links has a corresponding `belongs_to` relation in the `Link` model, remove the `belongs_to` relation.
```suggestion
    - If the `has_one` relation for the record which owns the links (e.g. `Page`) has a corresponding `belongs_to` relation on the `Link` model added via an extension, remove the `belongs_to` relation from the `Link` model.
```
It's a pretty confusing statement, I think this is correct and clarifies things?

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +    - For any `has_many` relations to links, update the dot notation to point to the `Owner` relation:
```suggestion
    - For any `has_many` relations to links on the record that owns the links (e.g. `Page`), update the dot notation to point to the `Owner` relation instead:
```

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +        - e.g. for the above, remove the `FirstHasOne` and `SecondHasOne` relations from the `Link` class. You may have applied these via yaml configuration or via an `Extension` class.
```suggestion
        - e.g. for the above, remove the `FirstHasOne` and `SecondHasOne` relations from the `Link` class. You may have applied these via an `Extension` class or via yaml configuration.
```
Extension is 100x more likely, so mention that first

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +1. Run the task
Will need to run flush first to get the yml config above to take effect

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +                # The class where the old has_one relation was declared
```suggestion
                # The class where the old has_one relation was declared, this will be either be Link or a Link subclass
```

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +                # The old name of the has_one relation
```suggestion
                # The old name of the has_one relation on Link or a Link subclass
```

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +        For example if a custom link has a `has-many` relation to some class, declare that class in skip hierarchies so it is not incorrectly identified as the owner of the link:
```suggestion
        For example if a custom link has a `has_many` relation to some class, declare that class in skip hierarchies so it is not incorrectly identified as the owner of the link:
```

2024-03-17 22:33 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +          skip_hierarchies_for_owner:
```suggestion
          skip_hierarchies_for_owner:
```
This is a really weirdly named config value

What's even is a hierarchy?

'for_owner' ... neither the Link nor the other class are owners?

Also why are they incorrectly identified as an owner ? If link has_many something ... then how could that be identified as an owner of the link?  If a Link has_one Page then then you'd expect that Page to be the Owner, though Link has_many Page I don't see how Page could be the Owner?

I don't know what to call this instead

2024-03-17 22:37 UTC, emteknetnz commented on src/Tasks/LinkFieldMigrationTask.php
> +        // on an UPDATE, due to a missing feature in framework's ORM API.
Neither? If this work fine as is then there's probably no need to optimise this

2024-03-17 22:37 UTC, emteknetnz commented on src/Tasks/LinkFieldMigrationTask.php
> +    private function checkForBrokenLinks(): void
Just leave it in

2024-03-17 22:40 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +          skip_hierarchies_for_owner:
I don't care what it's called. This name makes sense to me. The docs explain what it's for and nobody should be touching it without also using the guide so I think it's fine, but if you can suggest an alternative name I have no qualms about changing it.

> Also why are they incorrectly identified as an owner?

If something `has_one` link, or `has_one` polymorphic relation, it will be checked as a potential owner candidate. So first off let's just not check things we know can't be owners.

But then if there's no `has_many` (such as with things like `ChangeSet` or `ChangeSetItem`) then there's no way to tell that this `has_one` is *not* the owner of the link. So we have to explicitly tell the task to NOT set these as an owner.

2024-03-17 22:41 UTC, GuySartorelli commented on src/Tasks/LinkFieldMigrationTask.php
> +        // on an UPDATE, due to a missing feature in framework's ORM API.
This works with few links. This will fall flat on its face when there are thousands of links.
We should assume the worst case.

2024-03-17 22:49 UTC, GuySartorelli commented
> Do a test I got this warning which is correct because I missed a step:
> 
> ```
> Migrating has_many relations.
> has_one relation 'SilverStripe\LinkField\Models\Link.MyPage still exists. Cannot migrate has_many relation 'Page.MyPhoneLinks'.
> ```
> 
> However the rest of the script still processed and now my data is possibly is a weird state.  What should have happened is the script should have stopped immediately and told me to fix my issues. 

I don't think it matters too much, since you should create a snapshot before starting which you can roll back to. But it is friendlier to rollback for you in this case, since `has_many` is explicitly declared as opposed to the `has_one` stuff.
I'll make this rollback for you.

2024-03-17 22:53 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +    - If the `has_one` relation for the record which owns the links has a corresponding `belongs_to` relation in the `Link` model, remove the `belongs_to` relation.
Yup. Updated (and added yaml config as a way it may have been added)

2024-03-17 22:54 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +    - For any `has_many` relations to links, update the dot notation to point to the `Owner` relation:
Done except not adding "instead" because I'm not sure what it's instead _of_

2024-03-17 22:54 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +        - e.g. for the above, remove the `FirstHasOne` and `SecondHasOne` relations from the `Link` class. You may have applied these via yaml configuration or via an `Extension` class.
We have no data for that but I don't think it matters at all what order they're in so I changed it.

2024-03-17 22:55 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +1. Run the task
Updated

2024-03-17 22:57 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +                # The class where the old has_one relation was declared
Done

2024-03-17 22:57 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +                # The old name of the has_one relation
Done

2024-03-17 22:57 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +        For example if a custom link has a `has-many` relation to some class, declare that class in skip hierarchies so it is not incorrectly identified as the owner of the link:
Done

2024-03-19 03:19 UTC, emteknetnz requested changes

2024-03-19 03:19 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +          skip_hierarchies_for_owner:
Change the name to `classes_that_are_not_link_owners`, that's far more descriptive

2024-03-19 03:19 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +        For example if a custom link has a `has_many` relation to some class, declare that class in skip hierarchies so it is not incorrectly identified as the owner of the link:
```suggestion
    - Declare any classes that may have `has_one` relations to `Link`, but which do not *own* the link. Classes declared here will include any subclasses
        For example if a custom link has a `has_many` relation to some class which does not own the link, declare that class so it is not incorrectly identified as the owner of the link:
```

2024-03-19 03:22 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +        For example if a custom link has a `has_many` relation to some class, declare that class in skip hierarchies so it is not incorrectly identified as the owner of the link:
Done

2024-03-19 03:23 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +          skip_hierarchies_for_owner:
Done

2024-03-19 21:27 UTC, emteknetnz requested changes
Have tested locally, works good. Some minor docs changes to make.

One thing I noticed, though I'm not sure if it's worth fixing, is that links on a page that's draft in v3 of linkfield will be published when they're migrated. The page still remains draft though. Up to you if want to update the script so that links are only published if the owner is published

2024-03-19 21:27 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +1. Run `dev/build`
```suggestion
```
Just do a dev/build flush=1 below instead of doing them seperately

2024-03-19 21:27 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +                # The class where the old has_one relation was declared, this will be either be Link or a Link subclass
```suggestion
                # The class where the old has_one relation was declared
                # This will be either be Link or a Link subclass, not an extension applied to a Link class.
```

2024-03-19 21:27 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +        For example if a custom link has a `has_many` relation to some class which does not own the link, declare that class in skip hierarchies so it is not incorrectly identified as the owner of th
```suggestion
        For example if a custom link has a `has_many` relation to some class which does not own the link, declare that class here so it is not incorrectly identified as the owner of the link:
```

2024-03-19 21:27 UTC, emteknetnz commented on docs/en/09_migrating/00_upgrading.md
> +    - via a terminal: `sake dev flush=1`
```suggestion
1. Run dev/build flush=1 (use the method you will be using the for next step - i.e. if you're running the task via the terminal, make sure to flush via the terminal)
    - via the browser: `https://www.example.com/dev/build?flush=1`
    - via a terminal: `sake dev/build flush=1`
```
As noted above, just do dev/build and flush in the same step which is what people are used to doing

2024-03-19 21:35 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +1. Run `dev/build`
It makes more sense to me to have them separate, but it doesn't matter either way so I'll do this so we can get it merged.

Done.

2024-03-19 21:35 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +                # The class where the old has_one relation was declared, this will be either be Link or a Link subclass
Done

2024-03-19 21:35 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +        For example if a custom link has a `has_many` relation to some class which does not own the link, declare that class in skip hierarchies so it is not incorrectly identified as the owner of th
Done

2024-03-19 21:36 UTC, GuySartorelli commented on docs/en/09_migrating/00_upgrading.md
> +    - via a terminal: `sake dev flush=1`
Done - though I changed "Run dev/build flush=1" to "Run dev/build and flush your cache" to be more explicit about what it's doing

2024-03-19 21:37 UTC, GuySartorelli commented
Made requested changes - since they're all docs changes I haven't updated the CI run.

2024-03-19 22:48 UTC, emteknetnz approved these changes

2024-03-19 22:48 UTC, emteknetnz commented
Broken builds are expected

2024-03-19 22:48 UTC, merged