FIX Remove tabs with only gridfields
silverstripe/silverstripe-linkfield pull request #247
Opened 2024-03-07 22:15 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/243

2024-03-07 22:43 UTC, GuySartorelli requested changes
We shouldn't remove all gridfields. This is explicitly about removing the gridfield that fluent adds.
If people are adding other gridfields, they should still get hard errors telling them they shouldn't be doing that.

2024-03-08 04:57 UTC, emteknetnz commented
Updated

2024-03-08 06:19 UTC, GuySartorelli commented on src/Extensions/FluentLinkExtension.php
This feels like a massive over-complication... Why not just use `removeByName`?

2024-03-10 21:46 UTC, emteknetnz commented on src/Extensions/FluentLinkExtension.php
We could be that directly in getCMSFields(), though it's feels kind of icky having fluent specific code in there since fluents an optional module, I like having it in its own conditional extension so things are clearly separate

2024-03-10 21:51 UTC, GuySartorelli commented on src/Extensions/FluentLinkExtension.php
Right... I'm not suggesting doing this in `getCMSFields()` though. I'm suggesting doing this here in this extension. I don't understand why the logic is as complex as it is in this extension, when we know (and are even using already) the exact names of the tabs/fields we want to remove. Seems like we should just remove them, unless I'm missing something?

2024-03-10 22:04 UTC, emteknetnz commented on src/Extensions/FluentLinkExtension.php
Oh right I see what you mean. Have updated.

2024-03-10 22:41 UTC, GuySartorelli approved these changes
Works well locally, tested with has_one localised link.

2024-03-10 22:41 UTC, merged