ENH Use li for multi links
silverstripe/silverstripe-linkfield pull request #250
Opened 2024-03-13 01:37 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/245

- Changes MultiLinkField to use <ul><li> for links. Single LinkField continues to use <div>
- Refactoring DOM manipulation to use state instead
- Added inline comments to explain why `<LinkModalContainer>` in rendered in two different places

2024-03-28 07:18 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +      { /* This <LinkModalContainer> is only used for editing EXISTING links */ }
This isn't a debugging comment, this is useful context because there's 2x <LinkModalContainers> and I've labelled what each of themdo

2024-04-02 01:32 UTC, GuySartorelli requested changes

2024-04-02 01:32 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> +          </ul>
```suggestion
          <ol className="link-picker__list">
            <SortableContext
              items={linkIDs}
              strategy={verticalListSortingStrategy}
            >
              {links}
            </SortableContext>
          </ol>
```
Semantics is important here - and semantically since you can reorder the links and the order is important in the CMS context, `ol` should be used (regardless of the fact that in the frontend they're probably going to end up being in an unordered list)

2024-04-02 22:58 UTC, emteknetnz commented on client/src/components/LinkField/LinkField.js
> +          </ul>
Updated

2024-04-03 21:04 UTC, GuySartorelli approved these changes
LGTM

2024-04-03 21:04 UTC, merged