NEW Add migration task from gorriecoe/silverstripe-link
silverstripe/silverstripe-linkfield pull request #253
Opened 2024-03-14 01:43 UTC by GuySartorelli

## Description

Adds a migration task and guide for migrating from `gorriecoe/silverstripe-link` and `gorriecoe/silverstripe-linkfield`

## Manual testing steps

TBD

## Issues

- https://github.com/silverstripe/silverstripe-linkfield/issues/229

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-03-28 04:20 UTC, emteknetnz requested changes
Tested locally, seems really good, only some minor things

2024-03-28 04:20 UTC, emteknetnz commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +- The phone number for `PhoneLink` isn't validate, except to ensure there is a value present.
```suggestion
- The phone number for `PhoneLink` isn't validated, except to ensure there is a value present.
```

2024-03-28 04:20 UTC, emteknetnz commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    - If the models that have `has_one` or `has_many` relations to link don't already use `$owns` configuration for those relations, add that now. You may also want to set `$cascade_deletes` and `$ca
```suggestion
    - If the models that have `has_one` or `has_many` relations to link don't already use the `$owns` configuration for those relations, add that now. You may also want to set `$cascade_deletes` and `$cascade_duplicates` configuration. See [basic usage](../01_basic_usage.md) for more details.
```

2024-03-28 04:20 UTC, emteknetnz commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    - Declare any columns that you added to the gorriecoe link model which need to be migrated to the new base link table, for example if you added a custom sort column for your `has_many` relations:
I think it would make sense to move the yml config up much higher and be above where the `diff` examples are, because when you run through this you've removed all of the old config by this point, yet with the yml you're asked to define it, though you have nothing to refer to

2024-03-28 04:20 UTC, emteknetnz commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    +     private static array $owns = [
One thing I did noticed is that I had link to an unpublished page and another link to an unpublished file.  After migration the file was published, though the page was not.  The method of publishing is `$link->copyVersionToStage(Versioned::DRAFT, Versioned::LIVE);` in the trait.

Possibly it might be worth updating this so that the `$owns` config is put on post migration to stop this sort of unintentional publishing from happening.

2024-04-01 20:59 UTC, GuySartorelli commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    +     private static array $owns = [
Page owns link should not affect the published state of a file... there's nothing in the migration path as written that should be affecting the publish state of a file. Can you please clarify what you mean?

2024-04-01 21:01 UTC, GuySartorelli commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    - Declare any columns that you added to the gorriecoe link model which need to be migrated to the new base link table, for example if you added a custom sort column for your `has_many` relations:
I'd prefer to keep all of the migration task configuration in one chunk - are you suggesting moving all of the migration task configuration up above the rest of the setup?

I'm alright with doing that (and I'll update the v2/v3 to v4 migration docs while I'm at it) if that's what you want, but just want to clarify before doing it.

2024-04-01 21:02 UTC, GuySartorelli commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    - If the models that have `has_one` or `has_many` relations to link don't already use `$owns` configuration for those relations, add that now. You may also want to set `$cascade_deletes` and `$ca
Done

2024-04-01 21:02 UTC, GuySartorelli commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +- The phone number for `PhoneLink` isn't validate, except to ensure there is a value present.
Done

2024-04-01 21:15 UTC, emteknetnz commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    +     private static array $owns = [
Looks like I was confusing myself last week :-)

2024-04-01 21:19 UTC, emteknetnz commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    - Declare any columns that you added to the gorriecoe link model which need to be migrated to the new base link table, for example if you added a custom sort column for your `has_many` relations:
Yeah move the migration task config above the bit where it tells you to delete old stuff.  Because you need to refer to that old stuff when adding your migration task config

2024-04-01 21:51 UTC, GuySartorelli commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    - Declare any columns that you added to the gorriecoe link model which need to be migrated to the new base link table, for example if you added a custom sort column for your `has_many` relations:
Done.

I've also moved the "Take a backup of your database" into its own callout block to highlight that a bit better - it's easier to miss when its a step buried in a section like that, especially for experienced devs who may want to just skimread the docs and then figure it out themselves.

2024-04-01 22:27 UTC, emteknetnz approved these changes

2024-04-01 22:28 UTC, merged