ENH Improve component focusing
silverstripe/silverstripe-linkfield pull request #260
Opened 2024-03-21 04:14 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/245

2024-04-02 01:50 UTC, GuySartorelli requested changes
When I archive a link and then reorder links via the keyboard I get this error in the console:
> Assertion failed: Input argument is not an HTMLInputElement

I don't get that if I reorder with the mouse.

2024-04-02 01:50 UTC, GuySartorelli commented on client/src/components/LinkModal/LinkModal.js
> -  autoFocus: PropTypes.bool,
This prop is still being deconstructed from props in line 32

2024-04-02 01:50 UTC, GuySartorelli commented
Other than the specific problems above, it works great locally.

2024-04-02 23:02 UTC, emteknetnz commented on client/src/components/LinkModal/LinkModal.js
> -  autoFocus: PropTypes.bool,
I've removed it from line 32, it was unused

2024-04-02 23:05 UTC, emteknetnz commented
> When I archive a link and then reorder links via the keyboard I get this error in the console:

I'm unable to replicate this. Could you please double check this is still happening with the latest version of this PR and if so then demo it to me.

2024-04-03 21:10 UTC, GuySartorelli commented
Can't replicate that problem anymore, no idea what was causing it.
LGTM but has merge conflicts.

2024-04-03 22:31 UTC, emteknetnz commented
Done

2024-04-04 01:13 UTC, GuySartorelli approved these changes
LGTM

2024-04-04 01:13 UTC, merged