NEW LinkableMigrationTask for migrating sheadawson-lin kable links
silverstripe/silverstripe-linkfield pull request #261
Opened 2024-03-25 18:52 UTC by sabina-talipova

## Description

2024-04-07 20:18 UTC, sabina-talipova commented on src/Tasks/MigrationTaskTrait.php
> -    abstract private function classIsOldLink(string $class): bool;
The method `classIsOldLink` have been removed as redundant.

2024-04-08 02:16 UTC, GuySartorelli requested changes
Works great locally - some changes required.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/02_gorriecoe-migration.md
> +    - via a terminal: `sake dev/tasks/gorriecoe-to-linkfield-migration-task`
Good catch!

2024-04-08 02:16 UTC, ChloeSartorelli commented on src/Tasks/MigrationTaskTrait.php
> -    abstract private function classIsOldLink(string $class): bool;
Has this been tested with the gorriecoe migration task to make sure it doesn't cause problems there?

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +        if ($this->getName() !== 'testGetNeedsMigration') {
There is no `testGetNeedsMigration` method in this class

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'SelectedStyle' => 'Varchar',
I don't see a `SelectedStyle` field in https://github.com/sheadawson/silverstripe-linkable/blob/master/src/Models/Link.php

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'Phone' => 'Varchar(30)',
```suggestion
                'Title' => 'Varchar(255)',
                'Type' => 'Varchar',
                'URL' => 'Varchar(255)',
                'Email' => 'Varchar(255)',
                'Phone' => 'Varchar(255)',
```
According to https://github.com/sheadawson/silverstripe-linkable/blob/master/src/Models/Link.php

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                // Fields from the LinkSiteTree extension
```suggestion
                // Fields from LinkableSiteTreeExtension
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'CustomField' => 'Varchar',
`CustomField` isn't referenced in any tests or in the fixtures file?

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +            }
You haven't defined any pre-existing links in the fixtures file

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +            }
Probably this isn't needed anyway since we're doing `Link::get()->removeAll()` above so just remove this condition.

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +
```suggestion
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +    }
There's no need to use a `DataProvider` if you're only providing one test scenario.

Either add more test scenarios (e.g. `LinkFieldMigrationTaskTest` has 4 scenarios it's testing for this functionality) or fold this into the test method itself if no more scenarios need to be tested here.

2024-04-08 02:16 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +        $this->callPrivateMethod('insertBaseRows');
```suggestion
```
Set up some `Link` fixtures instead - this test doesn't need to run through this step, this all this step is doing is creating `Link` records and `setOwnerForHasOneLinks()` never looks at the old linkable table.

Alternatively, at a minimum, capture the `insertBaseRows` output separately and discard it, with a comment indicating that this test depends on the base rows being migrated first (see `testInsertTypeSpecificRows` as an example)

2024-04-08 02:16 UTC, ChloeSartorelli commented on src/Tasks/LinkableMigrationTask.php
> +    private static ?bool $is_enabled = true;
```suggestion
    private static ?bool $is_enabled = false;
```
Must be disabled by default

2024-04-08 02:16 UTC, ChloeSartorelli commented on src/Tasks/LinkableMigrationTask.php
> +    private static $segment = 'linkable-migration-task';
```suggestion
    private static $segment = 'linkable-to-linkfield-migration-task';
```
Not a big deal but just more consistent with the other two.
You'll need to update any references to this, e.g. in the migration docs

2024-04-08 02:16 UTC, ChloeSartorelli commented on src/Tasks/LinkableMigrationTask.php
> +     * Doesn't include
```suggestion
     * Doesn't include subclass columns - see link_type_columns
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on src/Tasks/GorriecoeMigrationTask.php
This task has a bunch of `use` statements in it that are no longer required

2024-04-08 02:16 UTC, ChloeSartorelli commented on src/Tasks/ModuleMigrationTaskTrait.php
> +     * The table name for the base gorriecoe link model.
```suggestion
     * The table name for the base link model from the module to migrate from.
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on src/Tasks/ModuleMigrationTaskTrait.php
> +    }
Keep this method in the separate classes.
It is duplication, but if there's something we've accidentally out of the migration, keeping this in the classes lets us add extra items in the middle of it that might only apply to one module but not the other.

Since this is a public method, we can't just remove it from the trait later.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +> Now we have 1 table for each type of Link, with a base `Link` table for all record.
Don't have so many callout blocks immediately after one another like this. It's hard to read, and it [fails linting](https://github.com/silverstripe/silverstripe-linkfield/actions/runs/8591479114/job/23540288569?pr=261)

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
Add a list of feature gaps - see the gorriecoe migration docs for an example.
We should make it clear what features from linkable do not have an equivalent in silverstripe/linkfield.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +> This migration task does not cover usages of `EmbeddedObject`.
This should be an item in the feature gap list instead of a callout block

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +> If you have subclassed `Sheadawson\Linkable\Models\Link`, there may be additional steps you need to take to migrate the data for your subclass.
Move this to below the feature gap list, to mirror its placement in the gorriecoe migration docs

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +> Now we have 1 table for each type of Link, with a base `Link` table for all record.
I think these details are a bit too low-level for this guide. It's not going to affect anyone who's not doing some weird custom queries - and those people will be a lot more cautious about tasks like this anyway.
```suggestion
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +> Be sure to check how the old module classes are referenced in config `yml` files (eg: `app/_config`). Update appropriately.
This seems like a good note to add to the gorriecoe migration docs as well.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Declare any `has_many` relations that need to be migrated:
`has_many` and `many_many` are not documented for linkable - we should add a warning that we have made assumptions about how these relations are set up, and that developers pay close attention to these during and after the migration to ensure everything has worked as they expect.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +> Search for instances of `LinkField::create` and `new LinkField`, and hopefully that should give you all of the places where you need to update field name references.
```suggestion
```
If I was going through a migration, I might read this tip, go update any `LinkField` references, and then skip this whole section. I think it's better to exclude this tip. Updating `LinkField` references is an explicit step below anyway.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +You should review how you are using the original `Link` model and `LinkField`, but if you don't have any customisations, then replacing the old with the new **might** be quite simple.
Add this to the gorriecoe migration docs too.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +You should review how you are using the original `Link` model and `LinkField`, but if you don't have any customisations, then replacing the old with the new **might** be quite simple.
```suggestion
You should review how you are using the original `Link` model and `LinkField`, but if you don't have any customisations, then replacing the old with the new might be quite simple.
```
Emphasis on "might" could make it seem like we're not too sure about our code

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +  ```
Updating `use` statements is literally part of the next step. No need to duplicate it.
```suggestion
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +1. If you have used imports (`use` statements), then your first step might just be to search for `use [old];` and replace
The first step in the gorriecoe migration docs is:

> If you added any database columns to the `Link` class for sorting `has_many` relations, or any `has_one` relations for storing them, remove the extension or yaml configuration for that now.

Does that not apply for linkable?

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Update the usage of link fields. The other key (less easy to automate) thing that you'll need to update is that the old `LinkField` required you to specify the related field with `ID` appended, wh
```suggestion
1. Update the usage of link field (and `GridField` if you were using that to manage `has_many` or `many_many` relations).
    - Note that the linkable module's `LinkField` required you to specify the related field with `ID` appended (e.g. `HasOneLinkID`), whereas the new `LinkField` requires you to specify the field without `ID` appended (e.g. `HasOneLink`).
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +    +             MultiLinkField::create('LinkListOne', 'List list one'),
```suggestion
    +             MultiLinkField::create('LinkListOne', 'List list one'),
    +             MultiLinkField::create('LinkListTwo', 'List list two'),
```
We're mentioning this relation everywhere else in the examples so we need to make sure to add a field for it.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +### Populate module
Reference the module by name (it's probably `silverstripe/populate` but double check that)

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +This is an area where you should spend some decent effort to make sure each implementation is outputting as you expect it to. There may be more "handy" methods that Linkable provided that no longer e
```suggestion
This is an area where you should spend some decent effort to make sure each implementation is outputting as you expect it to.
```
Don't need to mention that here - there should be a feature gap list above.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +## Replace template usages
This is a good idea. Please also cover the change of template file location for overriding default templates, and explicitly mention how the functionality in https://github.com/sheadawson/silverstripe-linkable?tab=readme-ov-file#customising-link-templates can be migrated - or simply state that we won't provide a migration path for that.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +
Add a step for updating linkfield settings such as [allowed link types](https://github.com/sheadawson/silverstripe-linkable?tab=readme-ov-file#limit-allowed-link-types) - see the gorriecoe migration docs for an example.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +### Custom links
Custom Links should be a subsection within a "Customising the migration" - see the gorriecoe migration docs for an example. At a very minimum it should mention that there's a bunch of extension points.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +    MyCustomType:
```suggestion
  # ...
  link_type_columns:
    # The name of the Type for your custom type as defined in gorriecoe/Link/Models/Link.types
```
Not super important but keeps things more consistent with the gorriecoe migration guide and gives a little more context

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +      # Only include columns that are defined in the $db configuration for your subclass
```suggestion
      # An mapping of column names from the old link to your new link subclass
      # Only include columns that are defined in the $db configuration for your subclass
```

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +    - If you're running the task in a terminal, you can add `skipBrokenLinks=1` as an argument: `sake dev/tasks/linkable-migration-task skipBrokenLinks=1`.
Add the warning from the gorriecoe migration docs about `many_many` - it applies to this migration as well.

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +> If your site is running Silverstripe CMS 4.x, upgrade to CMS 5 first.
```suggestion
> If your site is running Silverstripe CMS 4.x, upgrade to CMS 5 first. You will most likely need to use a fork of `sheadawson/silverstripe-linkable` that is compatible with Silverstripe CMS 5 as part of this upgrade.
```
The module isn't **actually** installable because it lists the wrong constraint for `silverstripe/vendor-plugin`

2024-04-08 02:16 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
Some of the same things that apply to the gorriecoe docs will apply here - e.g. the changes to Anchor

2024-04-09 19:43 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> If your site is running Silverstripe CMS 4.x, upgrade to CMS 5 first.
Updated

2024-04-09 19:44 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> Be sure to check how the old module classes are referenced in config `yml` files (eg: `app/_config`). Update appropriately.
Updated

2024-04-09 19:44 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +    +             MultiLinkField::create('LinkListOne', 'List list one'),
Updated

2024-04-09 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +### Custom links
Updated

2024-04-09 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +      # Only include columns that are defined in the $db configuration for your subclass
Updated

2024-04-09 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +    - If you're running the task in a terminal, you can add `skipBrokenLinks=1` as an argument: `sake dev/tasks/linkable-migration-task skipBrokenLinks=1`.
Updated

2024-04-09 22:25 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> If your site is running Silverstripe CMS 4.x, upgrade to CMS 5 first.
Updated

2024-04-09 22:25 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +    - If you're running the task in a terminal, you can add `skipBrokenLinks=1` as an argument: `sake dev/tasks/linkable-migration-task skipBrokenLinks=1`.
Updated

2024-04-09 22:25 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +      # Only include columns that are defined in the $db configuration for your subclass
Updated

2024-04-09 22:25 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +    MyCustomType:
Updated

2024-04-09 22:25 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +### Custom links
Updated

2024-04-09 22:26 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                // Fields from the LinkSiteTree extension
Updated

2024-04-09 22:26 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'CustomField' => 'Varchar',
Updated

2024-04-09 22:26 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +            }
Updated

2024-04-09 22:26 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +
Updated

2024-04-09 22:26 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +    }
Updated

2024-04-09 22:27 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +        $this->callPrivateMethod('insertBaseRows');
Updated

2024-04-09 22:27 UTC, sabina-talipova commented on src/Tasks/LinkableMigrationTask.php
> +    private static ?bool $is_enabled = true;
Updated

2024-04-09 22:27 UTC, sabina-talipova commented on src/Tasks/LinkableMigrationTask.php
> +    private static $segment = 'linkable-migration-task';
Updated

2024-04-09 22:28 UTC, sabina-talipova commented on src/Tasks/LinkableMigrationTask.php
> +     * Doesn't include
Updated

2024-04-09 22:28 UTC, sabina-talipova commented on src/Tasks/GorriecoeMigrationTask.php
Updated

2024-04-09 22:28 UTC, sabina-talipova commented on src/Tasks/ModuleMigrationTaskTrait.php
> +     * The table name for the base gorriecoe link model.
Updated

2024-04-09 22:35 UTC, sabina-talipova commented on src/Tasks/ModuleMigrationTaskTrait.php
> +    }
Updated

2024-04-09 22:35 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> Now we have 1 table for each type of Link, with a base `Link` table for all record.
Updated

2024-04-09 23:09 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
Updated

2024-04-09 23:19 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> This migration task does not cover usages of `EmbeddedObject`.
Updated

2024-04-09 23:20 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> If you have subclassed `Sheadawson\Linkable\Models\Link`, there may be additional steps you need to take to migrate the data for your subclass.
Updated

2024-04-09 23:20 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> Now we have 1 table for each type of Link, with a base `Link` table for all record.
Updated

2024-04-09 23:21 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Declare any `has_many` relations that need to be migrated:
Updated

2024-04-09 23:21 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +> Search for instances of `LinkField::create` and `new LinkField`, and hopefully that should give you all of the places where you need to update field name references.
Updated

2024-04-09 23:22 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +You should review how you are using the original `Link` model and `LinkField`, but if you don't have any customisations, then replacing the old with the new **might** be quite simple.
Updated

2024-04-09 23:22 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +You should review how you are using the original `Link` model and `LinkField`, but if you don't have any customisations, then replacing the old with the new **might** be quite simple.
Updated

2024-04-09 23:22 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +  ```
Updated

2024-04-09 23:31 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Update the usage of link fields. The other key (less easy to automate) thing that you'll need to update is that the old `LinkField` required you to specify the related field with `ID` appended, wh
Updated

2024-04-09 23:32 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +### Populate module
Updated

2024-04-09 23:39 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +This is an area where you should spend some decent effort to make sure each implementation is outputting as you expect it to. There may be more "handy" methods that Linkable provided that no longer e
Updated

2024-04-09 23:42 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +        if ($this->getName() !== 'testGetNeedsMigration') {
Updated

2024-04-09 23:42 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'SelectedStyle' => 'Varchar',
Updated

2024-04-09 23:43 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'Phone' => 'Varchar(30)',
Updated

2024-04-09 23:47 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +1. If you have used imports (`use` statements), then your first step might just be to search for `use [old];` and replace
Updated

2024-04-10 00:11 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +
Updated

2024-04-10 00:26 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +## Replace template usages
Updated

2024-04-10 19:31 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +    ```yml
Docs linting fails on this tag `yml`, I'm not sure that I can use required Upper case alternative. At least it doesn't work in my local env.

2024-04-11 03:00 UTC, GuySartorelli requested changes
Just about there.

There were a lot of pushes since the last review - I'm assuming that there weren't any changes unrelated to the changes I requested. If you did make other changes, please let me know so I can review them.

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Declare any `has_many` relations that need to be migrated:
Can you please tell me which line that's been added to? I can't find it.

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +    -     'title_display' => false,
Is `title_display` valid for linkable? It doesn't seem to be documented?

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +    - $linkField->setLinkConfig($linkConfig);
That method isn't correct according to [the linkable docs](https://github.com/sheadawson/silverstripe-linkable?tab=readme-ov-file#limit-allowed-link-types)

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +The link element structure is rendered using the `Link.ss` template. You can override this template by copying it to the theme or project folder and making the necessary changes. You still can also s
```suggestion
The link element structure is rendered using the `SilverStripe/LinkField/Models/Link.ss` template. You can override this template by copying it to the theme or project folder and making the necessary changes. You still can also specify a custom template to display the link by using the `renderWith()` method and passing the name of your custom template.
```
The path to the template is important.

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +The link element structure is rendered using the `Link.ss` template. You can override this template by copying it to the theme or project folder and making the necessary changes. You still can also s
```suggestion
The link element structure is rendered using the `Link.ss` template. You can override this template by copying it to the theme or project folder and making the necessary changes. You still can also specify a custom template to display the link by using the `renderWith()` method and passing the name of your custom template.

You can also provide templates for specific subclasses of `Link` - the file path for those templates is the FQCN for the link.
```

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +Also, when working on your own template, you should consider the following differences in variable names.
```suggestion
When working on your own template, you should consider the following differences in variable names.
```

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +### Custom links
There's still no mention in the main "customising the migration" section about the extension points?

2024-04-11 03:00 UTC, ChloeSartorelli commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'MySort' => 'Int',
These fields aren't *all* "directly from the Link class" - please add back the comments that indicate where each set of fields come from.

2024-04-11 03:00 UTC, ChloeSartorelli commented on src/Tasks/ModuleMigrationTaskTrait.php
> +     * The table name for the base gorriecoe link model.
Wasn't updated?

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +- Adding custom class to link. The `setCSSClass()` method does not exist in Linkfield. But you can still can add an Extension to the Link class or develop your own custom link class and implement the
```suggestion
- Adding custom css classes to link. The `setCSSClass()` method does not exist in Linkfield. You can still can add an `Extension` to the `Link` class or develop your own custom link class and implement the logic of this method.
```

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +- Customizing link templates. You can still call the `renderWith()` method and pass the name of your custom template, but `LinkField` no longer supports `templates` configuration.
```suggestion
- Customizing link templates. You can still call the `renderWith()` method and pass the name of your custom template, or use a template with the file path of the FQCN of the link subclass, but `LinkField` doesn't support the `templates` configuration.
```

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +- Limit allowed Link types. The `LinkField` module does not support the `allowed_types` configuration. Now, in order to set a limited list of link types available to the user, you should use the `Lin
```suggestion
- Limit allowed Link types. The `silverstripe/linkfield` module does not support the `allowed_types` configuration. Now, in order to set a limited list of link types available to the user, you should use the `Link::setAllowedTypes()` method.
```
`LinkField` is a class in the `silverstripe/linkfield` module.

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +- Limit allowed Link types. The `LinkField` module does not support the `allowed_types` configuration. Now, in order to set a limited list of link types available to the user, you should use the `Lin
Also mention the `Link.allowed_by_default` configuration here, which can be used to globally disallow certain link sublcasses from being used in `LinkField`.

2024-04-11 03:00 UTC, ChloeSartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +- `EmbeddedObject` field is not supported and you can no longer use the `EmbeddedObject` class as part of a LinkField.
```suggestion
- The `EmbeddedObject` and `EmbeddedObjectField` classes have no equivalent functionality in `silverstripe/linkfield`
```

2024-04-11 03:13 UTC, sabina-talipova commented
> There were a lot of pushes since the last review - I'm assuming that there weren't any changes unrelated to the changes I > requested. If you did make other changes, please let me know so I can review them.

No, there are not any new changes in the code, except one. I moved `performMigration()` from `ModuleMigrationTaskTrait` to the tasks, as you required.
I had to test remotely, since time to time some tests failed with unrelated error.

2024-04-11 19:44 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +### Custom links
Updated

2024-04-11 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +    -     'title_display' => false,
Updated

2024-04-11 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +    - $linkField->setLinkConfig($linkConfig);
Updated

2024-04-11 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +The link element structure is rendered using the `Link.ss` template. You can override this template by copying it to the theme or project folder and making the necessary changes. You still can also s
Updated

2024-04-11 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +The link element structure is rendered using the `Link.ss` template. You can override this template by copying it to the theme or project folder and making the necessary changes. You still can also s
Updated

2024-04-11 19:45 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +Also, when working on your own template, you should consider the following differences in variable names.
Updated

2024-04-11 19:46 UTC, sabina-talipova commented on tests/php/Tasks/LinkableMigrationTaskTest.php
> +                'MySort' => 'Int',
Updated

2024-04-11 19:46 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +- Adding custom class to link. The `setCSSClass()` method does not exist in Linkfield. But you can still can add an Extension to the Link class or develop your own custom link class and implement the
Updated

2024-04-11 19:46 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +- Customizing link templates. You can still call the `renderWith()` method and pass the name of your custom template, but `LinkField` no longer supports `templates` configuration.
Updated

2024-04-11 19:47 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +- Limit allowed Link types. The `LinkField` module does not support the `allowed_types` configuration. Now, in order to set a limited list of link types available to the user, you should use the `Lin
Updated

2024-04-11 19:47 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +- `EmbeddedObject` field is not supported and you can no longer use the `EmbeddedObject` class as part of a LinkField.
Updated

2024-04-11 19:52 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Declare any `has_many` relations that need to be migrated:
I followed the example of the Gorriecoe migration documentation and added a warning at the end of the text.

2024-04-11 21:33 UTC, GuySartorelli requested changes
Last few changes

2024-04-11 21:33 UTC, GuySartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +    +  allowed_by_default: false
This is back-to-front - here you're showing that they're the only allowed links in linkable, but they're being *excluded* in silverstripe/linkfield

2024-04-11 21:33 UTC, GuySartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Declare any `has_many` relations that need to be migrated:
The difference here is that with the Gorriecoe module `has_many` and `many_many` were explicitly supported. So all of the warnings from that module also apply, but we need an extra warning early-on that we're making assumptions about how people have set up their relations since there's no documented way to do it for linkable.

2024-04-11 21:33 UTC, GuySartorelli commented on docs/en/09_migrating/01_linkable-migration.md
> +    + $linkField->setAllowedTypes($allowedTypes);
```suggestion
      $linkField->setAllowedTypes($allowedTypes);
```
This would have already been there I think

2024-04-12 00:50 UTC, sabina-talipova commented on docs/en/09_migrating/01_linkable-migration.md
> +1. Declare any `has_many` relations that need to be migrated:
@GuySartorelli , please, have a look this block: https://github.com/silverstripe/silverstripe-linkfield/pull/261/files#diff-175a38f1b3d1d0a5d381bab10aa66cbcf785cf0290ac7a4097a34dc32942f197R63-R64

2024-04-12 01:07 UTC, GuySartorelli approved these changes
LGTM

2024-04-12 01:07 UTC, merged