ENH Better use of ARIA attributes
silverstripe/silverstripe-linkfield pull request #264
Opened 2024-03-28 06:14 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/245

2024-03-28 06:17 UTC, emteknetnz commented on client/src/components/LinkPicker/tests/LinkPickerTitle-test.js
> -test('keydown on dnd handler', async () => {
Removing this test because the aria-pressed attribute is now controlled by dndkit's attributes, not with custom code.  In a jest context this fails though real-life it works fine

2024-03-28 06:19 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +        aria-pressed={attributes['aria-pressed'] || false}
dndkit will set a value of undefined for aria-pressed when its not being sorted which is kind of odd and the attribute won't show at all, so I've given it a default value of false instead.

2024-04-02 01:58 UTC, GuySartorelli commented
> The Div containing the LinkField button has a role of button. The button inside there also has a the role of button.

While that has been resolved, we now have the situation where there's nothing indicating for screen readers that pressing enter/space on the link element itself will open the edit modal. That's what the `aria-role="button"` was there for.

2024-04-02 02:02 UTC, GuySartorelli requested changes
Seems to work well locally but I do have one concern below and one above.

2024-04-02 02:02 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPickerTitle.js
> -    {...attributes}
It seems a bit strange to not just be passing all the attributes in - are we 1000% sure we aren't accidentally ignoring attributes we want by doing this? What if the attributes change in a future release of the drag and drop library and we are then omitting something that it needs?

2024-04-02 23:12 UTC, emteknetnz commented
> While that has been resolved, we now have the situation where there's nothing indicating for screen readers that pressing enter/space on the link element itself will open the edit modal. That's what the aria-role="button" was there for.

We don't to define `role="button"` because for the link itself there's an html `<button>` which is bound to the onclick handler

2024-04-02 23:19 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> -    {...attributes}
Updated to pass in all attributes

2024-04-03 21:07 UTC, GuySartorelli commented
> > While that has been resolved, we now have the situation where there's nothing indicating for screen readers that pressing enter/space on the link element itself will open the edit modal. That's what the aria-role="button" was there for.
> 
> We don't to define `role="button"` because for the link itself there's an html `<button>` which is bound to the onclick handler

Ahhh yup my bad I missed that button somehow 😅

2024-04-03 21:08 UTC, GuySartorelli commented
LGTM but has a merge conflict

2024-04-03 22:31 UTC, emteknetnz commented
Done

2024-04-04 01:14 UTC, GuySartorelli commented
Last lot of conflicts.

2024-04-04 20:43 UTC, GuySartorelli approved these changes
LGTM, still works well in combination with the other merged PRs.

2024-04-04 20:44 UTC, merged