FIX Check canArchive() permission instead of canDelete()
silverstripe/silverstripe-linkfield pull request #315
Opened 2024-08-06 06:15 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/291

2024-08-06 22:24 UTC, GuySartorelli requested changes

2024-08-06 22:24 UTC, GuySartorelli commented on tests/php/Controllers/LinkFieldControllerTest.php
> +            // from any subclass of Link since we're unable to the use app/_config.php method
Why can't you just use `MyLinkSubclass::remove_extension(Versioned::class);` in the test?

2024-08-06 23:43 UTC, emteknetnz commented on tests/php/Controllers/LinkFieldControllerTest.php
> +            // from any subclass of Link since we're unable to the use app/_config.php method
Updated

2024-08-07 02:48 UTC, GuySartorelli approved these changes
LGTM

2024-08-07 02:48 UTC, merged