MNT Resolve deprecation warning in test
silverstripe/silverstripe-linkfield pull request #332
Opened 2024-09-10 03:50 UTC by GuySartorelli

See https://www.php.net/manual/en/migration83.deprecated.php about the deprecation
See https://www.php.net/manual/en/reflectionproperty.setvalue.php for the suggested solution

Not targeting `4.0` because this code doesn't exist on that branch.

## Issues
- https://github.com/silverstripe/.github/issues/309

2024-09-10 04:22 UTC, GuySartorelli commented
Prefer lowest failure is unrelated

2024-09-11 00:12 UTC, emteknetnz requested changes
We're missing the `setAccessible(true)` which should still be required according to [this comment](https://www.php.net/manual/en/reflectionclass.setstaticpropertyvalue.php#114740)

isCliOverride is a private static

Is the comments wrong? Or is the unit test just wrong?

2024-09-11 00:13 UTC, GuySartorelli commented
The comment says 
> Calling this method on a static property that is not public will return a ReflectionException stating the property does not exist

That's not happening, so it must be false.

2024-09-11 00:15 UTC, emteknetnz approved these changes

2024-09-11 00:15 UTC, merged