ENH Use symfony/validation logic
silverstripe/silverstripe-linkfield pull request #338
Opened 2024-09-24 05:46 UTC by GuySartorelli

Relies on changes in https://github.com/silverstripe/silverstripe-framework/pull/11399

## Issue
- https://github.com/silverstripe/.github/issues/193

2024-09-24 22:42 UTC, GuySartorelli commented on src/Models/ExternalLink.php
> +            $field->setAllowedProtocols(['http', 'https']);
Explicitly enforcing these protocols, even if the global config allows more protocols than this. We had decided originally this was explicitly what we wanted this link type to be used for. We can always loosen it later on if we want to.

2024-09-27 03:58 UTC, emteknetnz approved these changes

2024-10-02 02:30 UTC, emteknetnz requested changes
Behat failure

2024-10-02 02:56 UTC, GuySartorelli commented
Oops, I somehow missed a reference to the old `PasswordValidator`.
Should be fixed by https://github.com/silverstripe/silverstripe-behat-extension/pull/286

2024-10-02 05:39 UTC, emteknetnz requested changes
Still failing after merging behat-extension PR and re-running

2024-10-02 20:37 UTC, GuySartorelli commented
I must have been very distracted when doing that original framework PR lol. This behat failure is caused by a bug I introduced there.
Fixed by https://github.com/silverstripe/silverstripe-framework/pull/11414

2024-10-02 21:59 UTC, emteknetnz approved these changes

2024-10-02 21:59 UTC, merged