ENH Use getStatusFlags() instead of hardcoded statuses
silverstripe/silverstripe-linkfield pull request #351
Opened 2024-11-20 02:14 UTC by GuySartorelli

Status flags are made generic in https://github.com/silverstripe/silverstripe-framework/pull/11460

This PR uses the new `getStatusFlags()` method instead of building hardcoded status flags.

## Issue
- https://github.com/silverstripe/silverstripe-cms/issues/2947

2024-11-20 02:21 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPicker.scss
> -    background-color: #fff2ea;
Rely on styling in admin

2024-11-20 02:22 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPicker.scss
> +    }
Needs a gap between badges

2024-11-20 02:22 UTC, GuySartorelli commented on src/Models/Link.php
> +        return (string) $this->renderWith([static::class, Link::class]);
Unrelated change - my IDE was upset that the return type was string but this returns `DBHtmlText` - probably just because we're using strict mode here when we don't use it anywhere else.

2024-11-25 00:38 UTC, emteknetnz requested changes

2024-11-25 00:38 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  statusFlags,
How is this prop being passed in?  There's no corresponding PHP change in this PR?

2024-11-25 00:39 UTC, GuySartorelli commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  statusFlags,
Yes there is. See the `Link.php` file.

2024-11-26 00:15 UTC, emteknetnz approved these changes

2024-11-26 03:46 UTC, merged