Add table_name config to all models
silverstripe/silverstripe-linkfield pull request #39
Opened 2021-11-11 19:17 UTC by chrispenny

2021-11-14 22:11 UTC, mfendeksilverstripe requested changes
I think we should go with a less generic table names to prevent potential naming conflicts. I can definitely see table called `Link` having a conflict especially if a project is migrating from another module. I added `LinkFieldLink` prefix as the name of this module is `LinkField`.

2021-11-14 22:11 UTC, mfendeksilverstripe commented on src/Models/EmailLink.php
> +    private static $table_name = 'Link_EmailLink';
```suggestion
    private static $table_name = 'LinkFieldLink_EmailLink';
```

2021-11-14 22:11 UTC, mfendeksilverstripe commented on src/Models/ExternalLink.php
> +    private static $table_name = 'Link_ExternalLink';
```suggestion
    private static $table_name = 'LinkFieldLink_ExternalLink';
```

2021-11-14 22:11 UTC, mfendeksilverstripe commented on src/Models/FileLink.php
> +    private static $table_name = 'Link_FileLink';
```suggestion
    private static $table_name = 'LinkFieldLink_FileLink';
```

2021-11-14 22:11 UTC, mfendeksilverstripe commented on src/Models/Link.php
> +    private static $table_name = 'Link';
```suggestion
    private static $table_name = 'LinkFieldLink';
```

2021-11-14 22:11 UTC, mfendeksilverstripe commented on src/Models/SiteTreeLink.php
> +    private static $table_name = 'Link_SiteTreeLink';
```suggestion
    private static $table_name = 'LinkFieldLink_SiteTreeLink';
```

2021-11-15 19:48 UTC, mfendeksilverstripe requested changes
@chrispenny The changes look good but it seems some of the functionality is broken because of this change. This is my test setup (TNZ core after updating namespace references):

* Block page with a TextBlock / ButtonLink
* I switcher the block to NOT be inline editable
* navigated to the block edit form

Expected:

![Screen Shot 2021-11-16 at 8 45 37 AM](https://user-images.githubusercontent.com/26395487/141844456-a60ef4c6-804e-4c73-9551-8d0b15f4d8d8.png)

Actual:

![Screen Shot 2021-11-16 at 8 42 20 AM](https://user-images.githubusercontent.com/26395487/141844493-809ea665-648f-4b04-8c76-8666e928e031.png)

Maybe there are some class references in the React bundle as well?

2021-11-15 22:46 UTC, mfendeksilverstripe commented
@chrispenny Can you please check if you are able to save and retain link related changes? I can see that the UI now works but none of the changes I make are retained. Seems to be an issue on both inline edit and normal edit form cases.

Create a link

![Screen Shot 2021-11-16 at 11 41 11 AM](https://user-images.githubusercontent.com/26395487/141864603-0a766157-0791-4cc4-9e27-b0f9a6ebf209.png)

Hit save

![Screen Shot 2021-11-16 at 11 41 20 AM](https://user-images.githubusercontent.com/26395487/141864639-d88efd1c-fa84-4594-8f5b-9ed4d7934755.png)

Link doesn't show up even after page reload.

2021-11-16 00:44 UTC, chrispenny commented
Hi @mfendeksilverstripe,

These seem to be working ok for me.

Inline editor (text block):
![Screen Shot 2021-11-16 at 1 29 23 PM](https://user-images.githubusercontent.com/505788/141874118-bac036a3-6b5e-482b-98da-26cf6cdd9108.png)

Standard editor (cta block), straight after a publish:
![Screen Shot 2021-11-16 at 1 30 49 PM](https://user-images.githubusercontent.com/505788/141874124-71c37a72-066d-470b-828e-0e607b192db8.png)

Standard editor (cta block), after a refresh:
![Screen Shot 2021-11-16 at 1 31 01 PM](https://user-images.githubusercontent.com/505788/141874125-38c708ec-2700-429d-adce-939b40d67e78.png)

I don't believe I have done anything special other than a `dev/build` and appropriate flushes.

2021-11-16 01:08 UTC, mfendeksilverstripe approved these changes
Tested on local and it's working fine 👍 
thanks for contribution :)

2021-11-16 01:09 UTC, mfendeksilverstripe commented
@chrispenny Feel free to merge.

2021-11-16 01:39 UTC, merged