Update dependencies. Move to Github Actions
silverstripe/silverstripe-linkfield pull request #54
Opened 2023-02-27 19:00 UTC by chrispenny

2023-02-28 20:39 UTC, mfendeksilverstripe requested changes
Looking good overall 👍 , found a couple of minor issues though.

2023-02-28 20:39 UTC, mfendeksilverstripe commented on .github/workflows/main.yml
> +      js: false
This should not be disabled. The linting changes from `1` don't need to be carried over but we should have a JS pipeline running as it's considered part of the Github actions setup. My suggestion is to:

* enable JS pipeline
* carry over a sample JS test so we know the pipeline is running
* skip the linting changes to avoid merge conflicts

2023-02-28 20:39 UTC, mfendeksilverstripe commented on phpunit.xml.dist
> +    <testsuites>
Looks like you haven't carried over schema changes from `1`.

```
onfiguration: /home/runner/work/silverstripe-linkfield/silverstripe-linkfield/phpunit.xml.dist
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```

2023-02-28 21:53 UTC, maxime-rainville commented on src/Tasks/LinkableMigrationTask.php
> +    protected const TABLE_MAP_LINK = [
FYI We could get those table names with something like `DataObject::getSchema()->tableName(Link::class);`

That way, if some mad scientist decide to change the table name for their models, your script will still work.

2023-02-28 23:54 UTC, maxime-rainville requested changes
Did a quick code review and didn't see anything obviously wrong. I'm assuming that all of this code was more or less lifted from the v1 version of the module.

I tested that the core functionality of the module still works. I tested by adding a link to a page and by creating a Link block.

Didn't test the migration ... I don't have much context on how that other module work.

My main concern is what will happen with the data with the new table name?

2023-02-28 23:54 UTC, maxime-rainville commented on src/Models/Link.php
> +    private static $table_name = 'LinkField_Link';
This is definitively an improvement. However, when I run a `dev/build`, pre-existing data doesn't get moved to the new table. Do we have solution for that? Do we need to call this out somewhere for people upgrading form 1 to 2?

2023-03-01 18:14 UTC, chrispenny commented on src/Models/Link.php
> +    private static $table_name = 'LinkField_Link';
@maxime-rainville ^1.1 has the same table names:
https://github.com/silverstripe/silverstripe-linkfield/blob/1/src/Models/Link.php#L29

The issue is probably more for folks going from `dev-master`/`2.x-dev` to our official tag. I can certainly add some comments regarding this though. I'm not sure I want to go as far as to provide a migration task - since `dev-master` was flagged as experimental.

2023-03-01 19:08 UTC, chrispenny commented on .github/workflows/main.yml
> +      js: false
* Enabled JS testing
* Ignore all JS linting
* Brought across `sample-test.js`
* Updated dist files (apparently that breaks js tests if there is a `diff` in the build)

https://github.com/silverstripe/silverstripe-linkfield/pull/54/commits/71c50537d1e7299d39105453efbbd68b38e2f94b

2023-03-01 19:20 UTC, chrispenny commented on src/Tasks/LinkableMigrationTask.php
> +    protected const TABLE_MAP_LINK = [
Update here 😄 Thanks again!
https://github.com/silverstripe/silverstripe-linkfield/pull/54/commits/be7ece020e7c621410029409bc3c06ac32bbf18d

2023-03-01 19:45 UTC, mfendeksilverstripe requested changes
Thanks for the changes 👍 I have one minor concern with the frontend assets linting but other than that it's looking really good.

2023-03-01 19:45 UTC, mfendeksilverstripe commented on .eslintignore
> +client/
This effectively disables linting on the frontend files. I suggest to add a eslint ignore (which impacts the whole file) on top of each file instead with a comment that this should be re-enabled at some point. We can then reenable and fix file on case by case basis outside of scope of this PR.

2023-03-01 22:03 UTC, mfendeksilverstripe approved these changes
Awesome work 👍 I'm happy with the changes.

2023-03-02 09:35 UTC, maxime-rainville commented on src/Models/Link.php
> +    private static $table_name = 'LinkField_Link';
That's perfect. I'm happy with that.

2023-03-02 09:36 UTC, maxime-rainville approved these changes
Me happy!

2023-03-02 18:03 UTC, merged