SS5 front-end update
silverstripe/silverstripe-linkfield pull request #56
Opened 2023-03-03 01:29 UTC by blueo

updates to new webpack config
update dependencies
removed some unused dependences (i'm sure there are still some more)
tidy the files up a little

2023-03-03 01:52 UTC, GuySartorelli requested changes

2023-03-03 01:52 UTC, GuySartorelli commented on webpack.config.js
>  } = webpackConfig;
Just do `const { CssWebpackConfig, JavascriptWebpackConfig } = require('copy-webpack-plugin');` - though that's a nitpick, not a big deal if left as is

2023-03-03 01:52 UTC, GuySartorelli commented on webpack.config.js
>  const PATHS = {
For the paths, you only need to keep `ROOT`, any that are non-standard paths (which is none of these) and any that are used below explicitly (`SRC` and `DIST` only). See https://github.com/silverstripe/webpack-config/tree/2#usage

2023-03-03 01:52 UTC, GuySartorelli commented on package.json
> +    "build": "yarn && yarn lint && yarn test && NODE_ENV=production webpack --mode production --bail --progress",
```suggestion
    "build": "yarn && yarn lint && yarn test && rm -rf client/dist/* && NODE_ENV=production webpack --mode production --bail --progress",
```
Remove everything in dist before we start, so we know we don't have any extra garbage.

2023-03-03 01:52 UTC, GuySartorelli commented on package.json
> +    "@silverstripe/eslint-config": "1.0.0-alpha6",
```suggestion
    "@silverstripe/eslint-config": "^1.0.0-alpha6",
```
We want to make sure we get updates

2023-03-03 01:52 UTC, GuySartorelli commented on package.json
>      "@storybook/react": "^3.4.11",
Is there any storybook building in this module? Probably remove these.

2023-03-03 01:52 UTC, GuySartorelli commented on package.json
>      "copy-webpack-plugin": "^4",
copy plugin isn't used, remove it

2023-03-03 01:52 UTC, GuySartorelli commented on package.json
> +    "react-load-script": "^0.0.6",
react-load-script is abandoned https://www.npmjs.com/package/react-load-script

2023-03-03 01:52 UTC, GuySartorelli commented on package.json
>    },
```suggestion
  },
  "browserslist": [
    "defaults"
  ],
```
Make sure we're explicitly stating the browserset we support here

2023-03-03 01:52 UTC, GuySartorelli commented on package.json
>    }
For non-admin modules it's preferred to use a `babel.config.json` file to ensure jest is able to parse the admin imports correctly. See https://github.com/silverstripe/silverstripe-asset-admin/pull/1330/files#r1100908509
Looks like that's not a problem in this module for whatever reason so prooobably doesn't matter here, but just an FYI

2023-03-03 01:52 UTC, GuySartorelli commented on client/src/styles/bundle.scss
> -@import "link-variables";
Why is this removed?

2023-03-03 01:52 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
>      setNewTypeKey('');
```suggestion
    if (typeof onChange === 'function') {
      onChange(event, { id, value });
      setEditing(false);
      setNewTypeKey('');
    }
```
This is subjective though so take it or leave it

2023-03-03 01:52 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
>      setNewTypeKey('');
Also... are these lines even related to whether we have an onChange callback or not?
```js
setEditing(false);
setNewTypeKey('');
```

They feel separate.

2023-03-03 01:52 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> -  withApollo,
Instead of getting rid of this entirely, import it as `import { withApollo } from '@apollo/client/react/hoc';`
(forgot about this when you asked on slack but seeing it in context with code got my memory pumping)

2023-03-03 01:52 UTC, GuySartorelli commented on client/src/bundles/bundle.js
> +require('entwine/JsonField');
Consider changing these to `import` instead.

2023-03-03 01:52 UTC, GuySartorelli commented
Note, I haven't actually run this - these suggestions are based on a visual inspection of the code only.

2023-03-03 02:12 UTC, blueo commented on client/src/components/LinkField/LinkField.js
> -  withApollo,
yeah though it doesn't seem necessary? The component doesn't access the client instance from what I can see.

2023-03-03 02:13 UTC, blueo commented on client/src/components/LinkField/LinkField.js
>      setNewTypeKey('');
yeah good point - was mainly fixing a linting error will move these up

2023-03-03 02:14 UTC, blueo commented on client/src/styles/bundle.scss
> -@import "link-variables";
there was nothing in it so I figured it was unnecessary

2023-03-03 02:18 UTC, GuySartorelli commented on client/src/components/LinkField/LinkField.js
> -  withApollo,
Fair enough, if it's not needed it's not needed 👍

2023-03-03 02:19 UTC, GuySartorelli commented on client/src/styles/bundle.scss
> -@import "link-variables";
Makes sense

2023-03-03 02:48 UTC, maxime-rainville requested changes
Tested by adding a LinkField to a page and to a Content block.

The Page one works fine, but when I try to interact with the LinkField inside a block the modal doesn't show up and it looks stuck in some way. Replicated in FireFox and Chrome.

There's nothing in the JS console log.

[Screencast from 2023-03-03 15-43-04.webm](https://user-images.githubusercontent.com/1168676/222618906-3a881dcb-5fa0-469a-a467-b2263497726f.webm)

2023-03-03 04:06 UTC, maxime-rainville commented
After a select a type for my block, I get a never ending list of request to DynamicLink.

![image](https://user-images.githubusercontent.com/1168676/222628730-70c40dd8-9b34-4df0-ae72-9a3fa900f868.png)

2023-03-03 04:51 UTC, maxime-rainville commented
I created a test repo that adds a bunch of dummy LinkField https://github.com/maxime-rainville/silverstripe-linkfield-tester ... I suspect we'll problay nede somthing like this at some point to automate test.

I created a LinkField in the asset-admin Folder form. That form and the Elemental block form work slightly differently. So when creating a new field type, both context should be tested. The Folder LinkField allows you to select a link type and enter data, but that data is lost once try to save the modal. It behaves that way in CMS4 as well, so it's probably beyond the scope of this card to solve this.

2023-03-06 20:05 UTC, blueo commented
> After a select a type for my block, I get a never ending list of request to DynamicLink.
> 
> ![image](https://user-images.githubusercontent.com/1168676/222628730-70c40dd8-9b34-4df0-ae72-9a3fa900f868.png)

Yeah it seems the form loader mechanism is going into an infinite loop. Possibly because of having a nested form builder - the link field creates a dynamic form which updates the form state which triggers the elemental area form to re-render and on we go...

2023-03-06 22:44 UTC, blueo commented
OK so I think i've narrowed this down to how elemental is implemented. It seems that every time the formState is updated (eg by a form builder component being rendered AKA the linkfield) then the ElementalEditor will re render. The culprit appears to be this part https://github.com/silverstripe/silverstripe-elemental/blob/4/client/src/components/ElementEditor/ElementEditor.js#L138

If i replace it with the following it works
```javascript
function mapStateToProps(state, {areaId}) {
  if (!areaId) {
    return {};
  }

  const formNamePattern = loadElementFormStateName(areaId);
  const elementFormState = state.form.formState.element;

  if (!elementFormState) {
    return {};
  }

  const formState = elementFormState[formNamePattern]

  return {formState};
}
```

However this gets rid of the regex matching on the state Key. I couldn't see why this was needed - the original PR (https://github.com/silverstripe/silverstripe-elemental/pull/439) looks like originally had this implementation but then it changed.... anyone able to decipher the git history better than me? @maxime-rainville @GuySartorelli ?

2023-03-06 22:59 UTC, GuySartorelli commented
I took the liberty of changing your code snippet to a diff so it's really clear what you're changing there.

Looks like that regex was added in the PR you linked to - specifically in [this commit](https://github.com/silverstripe/silverstripe-elemental/pull/439/commits/d254223c13e22bcd2e2803c5c9c75f02ab66b807#diff-0c1ab3692e107d03408de5200c0d4a446265558530d0f2761f3a9ef1d35c73a6R39)

That said I don't have enough background in this area of the code to tell you anything about what that's doing or why it's there 😅

2023-03-06 23:02 UTC, blueo commented
> I took the liberty of changing your code snippet to a diff so it's really clear what you're changing there.
> 
> Looks like that regex _was_ added in the PR you linked to - specifically in [this commit](https://github.com/silverstripe/silverstripe-elemental/pull/439/commits/d254223c13e22bcd2e2803c5c9c75f02ab66b807#diff-0c1ab3692e107d03408de5200c0d4a446265558530d0f2761f3a9ef1d35c73a6R39), and then subsequent commits in the same PR changed how it's used slightly.
> 
> That said I don't have enough background in this area of the code to tell you anything about what that's doing or why it's there 😅

thanks - weirdly the very next commit has changed it - https://github.com/silverstripe/silverstripe-elemental/pull/439/commits/606ccab6d9049c1199d00cf4aff5a9d10dd1203d#diff-642820167278809b93baf09f49a985a9563af65057ca3ab441617f034c238d2eR87 perhaps I'll just make a PR there and see if any Behat tests fail :)

2023-03-07 20:29 UTC, blueo commented
the infinite loop issue is fixed by: https://github.com/silverstripe/silverstripe-elemental/pull/1044 so this will need to wait for that to merge

2023-03-07 20:54 UTC, blueo commented
@maxime-rainville what issue did you have with the files area? I seem to be able to add a linkfield there:
![image](https://user-images.githubusercontent.com/948122/223550181-c57602f4-c19f-47e9-a1f0-727830ee440c.png)
and it persists after saving

2023-03-07 21:41 UTC, GuySartorelli commented
The elemental bug fix is released as [5.0.0-beta2](https://github.com/silverstripe/silverstripe-elemental/releases/tag/5.0.0-beta2)

2023-03-09 20:12 UTC, merged