ENH Validation
silverstripe/silverstripe-linkfield pull request #85
Opened 2023-09-26 00:33 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-linkfield/issues/84

Multiple commits PR so don't squash merge

2023-09-26 00:35 UTC, emteknetnz commented on src/Form/PhoneField.php
> + * Text input field with validation for correct email format according to RFC 2822.
Need to update this since it's not an email field

2023-10-10 16:24 UTC, purplespider commented
For the `ExternalLink` field validation etc, can I suggest considering using https://github.com/burnbright/silverstripe-externalurlfield? (I feel that module should really be part of the core tbh).

2023-10-17 03:26 UTC, emteknetnz commented on src/Models/Link.php
> +        $validator = $this->getCMSCompositeValidator();
On second thought this is the wrong place to be calling getCMSCompositeValidator() - instead we should be calling it alongside the DataObject validation, rather that inside in

2024-01-30 21:06 UTC, GuySartorelli requested changes

2024-01-30 21:06 UTC, ChloeSartorelli commented on lang/en.yml
> +    INVALID: 'Please enter a valid URL'
```suggestion
```
This is in framework now.

2024-01-30 21:06 UTC, ChloeSartorelli commented on src/Models/EmailLink.php
> +        $validator->addValidator(RequiredFields::create(['Email']));
```suggestion
        $requiredFieldsValidators = $validator->getValidatorsByType(RequiredFields::class);
        if (empty($requiredFieldsValidators)) {
            $requiredFieldsValidator = RequiredFields::create(['Email']);
        } else {
            $requiredFieldsValidator = $requiredFieldsValidators[array_key_first($requiredFieldsValidators)];
        }
        $validator->addValidator($requiredFieldsValidator);
```
An alternative approach would be to add a `getOrCreateValidatorOfType()` method to `CompositeValidator` (similar to [`FieldList::findOrMakeTab()`](https://api.silverstripe.org/5/SilverStripe/Forms/FieldList.html#method_findOrMakeTab)) - or at least a `getValidatorByType()` (similar to [`GridFieldConfig::getComponentByType()`](https://api.silverstripe.org/5/SilverStripe/Forms/GridField/GridFieldConfig.html#method_getComponentByType))

You don't have to do this, but it does make the validator tidier and easier to work with in subclasses or extensions. I won't block merging if you don't make this change.

If you do make this change, please also make it in the other `getCMSCompositeValidator()` implementations.

2024-01-30 21:06 UTC, ChloeSartorelli commented on src/Models/ExternalLink.php
> +            $field->setTitle(_t(__CLASS__ . '.EXTERNAL_URL_FIELD', 'External URL'));
```suggestion
            $field = UrlField::create('ExternalUrl', $this->fieldLabel('ExternalUrl'));
```
This should have been done like this originally, since the field label localisation is provided (see `db_ExternalUrl`) - but I won't block merging if you don't make this change since it's not directly related to what this PR is for.

If you do make this change, please make it for other link types as well.

2024-01-30 22:59 UTC, emteknetnz commented on lang/en.yml
> +    INVALID: 'Please enter a valid URL'
Removed

2024-01-30 23:00 UTC, emteknetnz commented on src/Models/EmailLink.php
> +        $validator->addValidator(RequiredFields::create(['Email']));
Leaving as is

2024-01-30 23:00 UTC, emteknetnz commented on src/Models/ExternalLink.php
> +            $field->setTitle(_t(__CLASS__ . '.EXTERNAL_URL_FIELD', 'External URL'));
Leave as is

2024-01-31 02:26 UTC, GuySartorelli approved these changes
Looks good, will merge after framework PR.

2024-01-31 02:26 UTC, GuySartorelli commented on README.md
> +Custom links can have validation set using standard [model validation]([https://docs.silverstripe.org/en/5/developer_guides/forms/validation/#model-validation).
```suggestion
Custom links can have validation set using standard [model validation](https://docs.silverstripe.org/en/5/developer_guides/forms/validation/#model-validation).
```

2024-02-02 01:32 UTC, GuySartorelli requested changes

2024-02-02 01:32 UTC, GuySartorelli commented on README.md
> +Custom links can have validation set using standard [model validation]([https://docs.silverstripe.org/en/5/developer_guides/forms/validation/#model-validation).
Still need to fix this minor thing

2024-02-02 01:50 UTC, GuySartorelli commented
Works great on a page.

When I try in an inline-elemental block, the first time I try to create a link and trigger validation (i.e. an invalid link), the modal just closes and reopens.
Submitting again triggers validation and gives the message correctly, so it's just the first time submitting the modal form with an invalid link.

2024-02-04 20:53 UTC, emteknetnz commented on README.md
> +Custom links can have validation set using standard [model validation]([https://docs.silverstripe.org/en/5/developer_guides/forms/validation/#model-validation).
Updated

2024-02-04 20:55 UTC, emteknetnz commented on README.md
> +Custom links can have validation set using standard [model validation]([https://docs.silverstripe.org/en/5/developer_guides/forms/validation/#model-validation).
Updated

2024-02-05 00:31 UTC, emteknetnz commented
> When I try in an inline-elemental block, the first time I try to create a link and trigger validation (i.e. an invalid link), the modal just closes and reopens. Submitting again triggers validation and gives the message correctly, so it's just the first time submitting the modal form with an invalid link.

I've spend half a day debugging this.  This is seems like an extremely difficult issue to fix.  Core issue is that the ElementList.js (possibly higher up) is re-rendering on validation failure, causing the nested LinkField and nested FormBuilderModal to themselves re-render.

This can be validated by putting in the following into (silverstripe/silverstripe-elemental) ElementEditor.js and putting breakpoints in and causing the validation to fail

```js
  componentDidMount() {
    var x = 1;
  }

  componentDidUpdate() {
    var x = 1;
  }
```

What's causing the re-render seems like its in the "magical blackbox" territory of JS Injector which does a bunch of stuff in registerTransforms.js and possibly redux-form.  I don't really know.

2024-02-05 02:56 UTC, emteknetnz commented
Update: Max traced it to this [line](https://github.com/silverstripe/silverstripe-linkfield/blob/03ffff8497fe604828738f0a925ec27a37ffafa7/client/src/containers/LinkModalContainer.js#L18) - making it so that Injector isn't used fixes the issue and instead we just use `<LinkModal>` as per normal fixes issue

I've leave this code as is for now to give Max an opportunity to fix, though I'll raise a new issue to remove the Injector code if he's unable to fix and put into refinement

2024-02-05 03:05 UTC, GuySartorelli commented
For my money, passing the injected modal as a prop or memorising it seems likely to resolve this.

2024-02-05 03:12 UTC, emteknetnz commented
I had a quick try with

```js
// https://react.dev/reference/react/memo
import React, { memo } from 'react';

const LinkModal = memo(loadComponent(`LinkModal.${handlerName}`));
```

Didn't work

Passing in a prop (haven't tested) is kinda ugly because `<LinkModalContainer>` can come from either LinkField.js or LinkPicker.js

2024-02-05 04:54 UTC, GuySartorelli commented
Max came up with a solution. I've simplied it a lot, the only part that's really needed is setting the `loadComponent` result as state like so:

```js
import React, { useState } from 'react';

// ...
const [ LinkModal, setLinkModal ] = useState(null);

// ...
if (LinkModal === null) {
  setLinkModal(() => loadComponent(`LinkModal.${handlerName}`));
}
```

You can wrap setting the state in a call to `useEffect` as well if you like (using `[typeKey]` as the second argument) - but in my (admittedly limited) test that didn't seem necessary.

2024-02-06 21:26 UTC, GuySartorelli requested changes
Works great locally, just a tiny docs regression

2024-02-06 21:26 UTC, GuySartorelli commented on README.md
> +Custom links can have validation set using standard [model validation]([https://docs.silverstripe.org/en/5/developer_guides/forms/validation/#model-validation).
I saw that this had been fixed, but now it's unfixed?

2024-02-06 21:34 UTC, emteknetnz commented on README.md
> +Custom links can have validation set using standard [model validation]([https://docs.silverstripe.org/en/5/developer_guides/forms/validation/#model-validation).
Updated

2024-02-06 21:45 UTC, GuySartorelli approved these changes
LGTM

2024-02-06 21:45 UTC, merged