ENH Add versioning to Link
silverstripe/silverstripe-linkfield pull request #90
Opened 2023-09-26 20:40 UTC by emteknetnz

Issue

For this to work properly you also need to add the following to the project `Page` or whatever other DataObject has Link's added to it:

```php
$has_one = [
    'HasOneLink' => Link::class
];

$owns = [
    'HasOneLink'
];

$cascade_deletess = [
    'HasOneLink'
];

$cascade_duplicatess = [
    'HasOneLink'
];
```

2023-09-26 20:57 UTC, michalkleiner commented on _config.php
Does this file need any content at all?

2023-09-26 20:57 UTC, michalkleiner commented on src/Models/Link.php
> +        Versioned::class
```suggestion
        Versioned::class,
```

2023-09-26 22:26 UTC, emteknetnz commented on _config.php
I made this change just to pass phpcs. There's a bunch of other PRs linked in the parent issue that has the same change.

I'd delete it, but I'm doing lots of little PRs to keep it clear what's changing rather than one big PR. The file will probably get deleted in a final tidy up PR

2023-09-26 22:26 UTC, emteknetnz commented on src/Models/Link.php
> +        Versioned::class
Updated

2023-09-26 22:55 UTC, emteknetnz commented on tests/php/Models/LinkTest.php
> +        $image->setFromLocalFile(dirname(dirname(dirname(__FILE__))) . '/resources/600x400.png');
This doesn't affect versioning though it's required to run the unit test from the vendor folder

2023-09-26 22:56 UTC, emteknetnz commented on tests/php/Models/LinkTest.php
> -        $page->publishSingle();
I don't know why the previous unit test was publishing things and setting the stage to LIVE, it's not necessary for the purpose of what's being tested

2023-12-05 02:55 UTC, emteknetnz commented on tests/php/Models/LinkTest.php
> -            Versioned::set_stage(Versioned::LIVE);
Versioning doesn't have any impact on this test, and setting things to LIVE means we'd need to publish the Links before making assertions

2023-12-07 03:49 UTC, emteknetnz commented
Design feedback:
- Keep icons as they are
- Add versioned badges to the right of the descriptions, similar to what the site tree has
- `<span class="badge status-modified" title="Page has unpublished changes">Modified</span>`  `#cf3f00` `#fff2ea`
- Truncate description in PHP to a reasonable character limit and add '...' if needed
- Raise a card to implement text badges in elemental

2023-12-07 22:03 UTC, emteknetnz commented
Design review has done and approved

2023-12-10 23:17 UTC, sabina-talipova requested changes
Just tiny changes.

2023-12-10 23:17 UTC, sabina-talipova commented on README.md
> +    private static array $cascade_deletess = [
```suggestion
    private static array $cascade_deletes = [
```

2023-12-10 23:17 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  if (title.length > 30) {
```suggestion
  if (title && title.length > 30) {
```

2023-12-10 23:17 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    title = title.substring(0, 30) + '...';
Probably, we should decrease it up to 20 signs. "Modified" goes to the another string with long title.
<img width="472" alt="Screenshot 2023-12-11 at 11 53 54 AM" src="https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/dac5c73d-05b9-49fd-8b32-dcedcfa5d73b">

2023-12-11 01:32 UTC, emteknetnz commented on README.md
> +    private static array $cascade_deletess = [
Updated

2023-12-11 01:45 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    title = title.substring(0, 30) + '...';
During the design review we agreed on 30 so would prefer to keep it closer to that.

In split mode we need to go all the way down to 17 chars to get it to not wrap, which isn't enough chars IMO.

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/208ac3b1-4cb8-4786-8fc8-0955a27e6a09)

The bigger issue IMO that it goes over-bounds in split mode with 30 chars
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/ea8b558f-07b7-40c5-b411-79150222cebd)

Reducing this to 25 resolves this
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/dd0665c9-0779-4af3-91f4-d6660a251c8f)

I'll double check with design team if they're prefer 25 with wrap or 17 without wrap

2023-12-11 01:53 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    title = title.substring(0, 30) + '...';
Chatted with design team, agreed on 25 with wrap though ensure that badge isn't indented if it wraps

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/6044abd8-ed18-4d49-b5d3-e43cd7fd9f6f)

2023-12-11 01:53 UTC, emteknetnz commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +  if (title.length > 30) {
Updated

2023-12-11 01:58 UTC, michalkleiner commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    title = title.substring(0, 30) + '...';
Put 25 `M` characters and it will do the same.. Does it need to be character limit? CSS can put the ellipsis there automatically based on width of the container.

2023-12-11 03:19 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    title = title.substring(0, 30) + '...';
I think we can extract this issue in another ticket, since there is another similar issue with long external link. Probably, we should review link field styles.

2023-12-11 03:51 UTC, sabina-talipova commented on client/src/components/LinkPicker/LinkPickerTitle.js
> +    title = title.substring(0, 30) + '...';
Open new issue for UX issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/138

2023-12-11 05:21 UTC, sabina-talipova approved these changes
LGTM. Test locally. Works perfect.

2023-12-11 05:21 UTC, merged